class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['CHANGE OF COMMITTEE NAME', '3', '', ''],
            ['COMMITTEE NAME', '4', '', ''],
            ['CHANGE OF ADDRESS', '5', '', ''],
            ['STREET 1', '6', '', ''],
            ['STREET 2', '7', '', ''],
            ['CITY', '8', '', ''],
            ['STATE', '9', '', ''],
            ['ZIP', '10', '', ''],
            ['CHANGE OF COMMITTEE EMAIL', '11', '', ''],
            ['COMMITTEE EMAIL', '12', '', ''],
            ['CHANGE OF COMMITTEE WEB URL', '13', '', ''],
            ['COMMITTEE WEB URL', '14', '', ''],
            ['SUBMISSION DATE', '15', '', ''],
            ['SIGNATURE LAST NAME', '16', '', ''],
            ['SIGNATURE FIRST NAME', '17', '', ''],
            ['SIGNATURE MIDDLE NAME', '18', '', ''],
            ['SIGNATURE PREFIX', '19', '', ''],
            ['SIGNATURE SUFFIX', '20', '', ''],
            ['DATE SIGNED', '21', '', ''],
            ['COMMITTEE TYPE', '22', '5', ''],
            ['CANDIDATE ID NUMBER', '23', '5', ''],
            ['CANDIDATE LAST NAME', '24', '5', ''],
            ['CANDIDATE FIRST NAME', '25', '5', ''],
            ['CANDIDATE MIDDLE NAME', '26', '5', ''],
            ['CANDIDATE PREFIX', '27', '5', ''],
            ['CANDIDATE SUFFIX', '28', '5', ''],
            ['CANDIDATE OFFICE', '29', '5', ''],
            ['CANDIDATE STATE', '30', '5', ''],
            ['CANDIDATE DISTRICT', '31', '5', ''],
            ['PARTY CODE', '32', '5', ''],
            ['PARTY TYPE', '33', '5', ''],
            ['ORGANIZATION TYPE', '34', '5', 'e'],
            ['LOBBYIST/REGISTRANT PAC', '35', '5', 'e'],
            ['LOBBYIST/REGISTRANT PAC', '36', '5', 'f'],
            ['LEADERSHIP PAC', '37', '5', 'f'],
            ['AFFILIATED Committee ID NUM', '38', '6', ''],
            ['AFFILIATED Committee NAME', '39', '6', ''],
            ['AFFILIATED CANDIDATE ID NUM', '40', '6', ''],
            ['AFFILIATED LAST NAME', '41', '6', ''],
            ['AFFILIATED FIRST NAME', '42', '6', ''],
            ['AFFILIATED MIDDLE NAME', '43', '6', ''],
            ['AFFILIATED PREFIX', '44', '6', ''],
            ['AFFILIATED SUFFIX', '45', '6', ''],
            ['AFFILIATED STREET 1', '46', '6', ''],
            ['AFFILIATED STREET 2', '47', '6', ''],
            ['AFFILIATED CITY', '48', '6', ''],
            ['AFFILIATED STATE', '49', '6', ''],
            ['AFFILIATED ZIP', '50', '6', ''],
            ['AFFILIATED RELATIONSHIP CODE', '51', '6', ''],
            ['CUSTODIAN LAST NAME', '52', '7', ''],
            ['CUSTODIAN FIRST NAME', '53', '7', ''],
            ['CUSTODIAN MIDDLE NAME', '54', '7', ''],
            ['CUSTODIAN PREFIX', '55', '7', ''],
            ['CUSTODIAN SUFFIX', '56', '7', ''],
            ['CUSTODIAN STREET 1', '57', '7', ''],
            ['CUSTODIAN STREET 2', '58', '7', ''],
            ['CUSTODIAN CITY', '59', '7', ''],
            ['CUSTODIAN STATE', '60', '7', ''],
            ['CUSTODIAN ZIP', '61', '7', ''],
            ['CUSTODIAN TITLE', '62', '7', ''],
            ['CUSTODIAN TELEPHONE', '63', '7', ''],
            ['TREASURER LAST NAME', '64', '8', ''],
            ['TREASURER FIRST NAME', '65', '8', ''],
            ['TREASURER MIDDLE NAME', '66', '8', ''],
            ['TREASURER PREFIX', '67', '8', ''],
            ['TREASURER SUFFIX', '68', '8', ''],
            ['TREASURER STREET 1', '69', '8', ''],
            ['TREASURER STREET 2', '70', '8', ''],
            ['TREASURER CITY', '71', '8', ''],
            ['TREASURER STATE', '72', '8', ''],
            ['TREASURER ZIP', '73', '8', ''],
            ['TREASURER TITLE', '74', '8', ''],
            ['TREASURER TELEPHONE', '75', '8', ''],
            ['AGENT LAST NAME', '76', '8', ''],
            ['AGENT FIRST NAME', '77', '8', ''],
            ['AGENT MIDDLE NAME', '78', '8', ''],
            ['AGENT PREFIX', '79', '8', ''],
            ['AGENT SUFFIX', '80', '8', ''],
            ['AGENT STREET 1', '81', '8', ''],
            ['AGENT STREET 2', '82', '8', ''],
            ['AGENT CITY', '83', '8', ''],
            ['AGENT STATE', '84', '8', ''],
            ['AGENT ZIP', '85', '8', ''],
            ['AGENT TITLE', '86', '8', ''],
            ['AGENT TELEPHONE', '87', '8', ''],
            ['BANK NAME', '88', '9. a', ''],
            ['BANK STREET 1', '89', '9. a', ''],
            ['BANK STREET 2', '90', '9. a', ''],
            ['BANK CITY', '91', '9. a', ''],
            ['BANK STATE', '92', '9. a', ''],
            ['BANK ZIP', '93', '9. a', ''],
            ['BANK NAME', '94', '9. b', ''],
            ['BANK STREET 1', '95', '9. b', ''],
            ['BANK STREET 2', '96', '9. b', ''],
            ['BANK CITY', '97', '9. b', ''],
            ['BANK STATE', '98', '9. b', ''],
            ['BANK ZIP', '99', '9. b', ''],
    ]
