import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER CANDIDATE ID NUMBER', 'number': '2'},
            {'name': 'CANDIDATE LAST NAME', 'number': '3'},
            {'name': 'CANDIDATE FIRST NAME', 'number': '4'},
            {'name': 'CANDIDATE MIDDLE NAME', 'number': '5'},
            {'name': 'CANDIDATE PREFIX', 'number': '6'},
            {'name': 'CANDIDATE SUFFIX', 'number': '7'},
            {'name': 'CHANGE OF ADDRESS', 'number': '8'},
            {'name': 'CANDIDATE STREET 1', 'number': '9'},
            {'name': 'CANDIDATE STREET 2', 'number': '10'},
            {'name': 'CANDIDATE CITY', 'number': '11'},
            {'name': 'CANDIDATE STATE', 'number': '12'},
            {'name': 'CANDIDATE ZIP', 'number': '13'},
            {'name': 'CANDIDATE PARTY CODE', 'number': '14'},
            {'name': 'CANDIDATE OFFICE', 'number': '15'},
            {'name': 'CANDIDATE STATE', 'number': '16'},
            {'name': 'CANDIDATE DISTRICT', 'number': '17'},
            {'name': 'YEAR OF ELECTION 1900-2999', 'number': '18'},
            {'name': 'PCC COMMITTEE ID NUMBER', 'number': '19'},
            {'name': 'PCC COMMITTEE NAME', 'number': '20'},
            {'name': 'PCC STREET 1', 'number': '21'},
            {'name': 'PCC STREET 2', 'number': '22'},
            {'name': 'PCC CITY', 'number': '23'},
            {'name': 'PCC STATE', 'number': '24'},
            {'name': 'PCC ZIP', 'number': '25'},
            {'name': 'AUTH COMMITTEE ID NUMBER', 'number': '26'},
            {'name': 'AUTH COMMITTEE NAME', 'number': '27'},
            {'name': 'AUTH STREET 1', 'number': '28'},
            {'name': 'AUTH STREET 2', 'number': '29'},
            {'name': 'AUTH CITY', 'number': '30'},
            {'name': 'AUTH STATE', 'number': '31'},
            {'name': 'AUTH ZIP', 'number': '32'},
            {'name': 'CANDIDATE SIGNATURE LAST NAME', 'number': '33'},
            {'name': 'CANDIDATE SIGNATURE FIRST NAME', 'number': '34'},
            {'name': 'CANDIDATE SIGNATURE MIDDLE NAME', 'number': '35'},
            {'name': 'CANDIDATE SIGNATURE PREFIX', 'number': '36'},
            {'name': 'CANDIDATE SIGNATURE SUFFIX', 'number': '37'},
            {'name': 'DATE SIGNED', 'number': '38'},
    ]
        self.fields_names = self.hash_names(self.fields)
