import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER COMMITTEE ID NUMBER', 'number': '2'},
            {'name': 'COMMITTEE NAME', 'number': '3'},
            {'name': 'CHANGE OF ADDRESS', 'number': '4'},
            {'name': 'STREET 1', 'number': '5'},
            {'name': 'STREET 2', 'number': '6'},
            {'name': 'CITY', 'number': '7'},
            {'name': 'STATE', 'number': '8'},
            {'name': 'ZIP', 'number': '9'},
            {'name': 'ACTIVITY PRIMARY', 'number': '10'},
            {'name': 'ACTIVITY GENERAL', 'number': '11'},
            {'name': 'REPORT CODE', 'number': '12'},
            {'name': 'ELECTION CODE', 'number': '13'},
            {'name': 'DATE OF ELECTION', 'number': '14'},
            {'name': 'STATE OF ELECTION', 'number': '15'},
            {'name': 'COVERAGE FROM DATE', 'number': '16'},
            {'name': 'COVERAGE THROUGH DATE', 'number': '17'},
            {'name': 'TREASURER LAST NAME', 'number': '18'},
            {'name': 'TREASURER FIRST NAME', 'number': '19'},
            {'name': 'TREASURER MIDDLE NAME', 'number': '20'},
            {'name': 'TREASURER PREFIX', 'number': '21'},
            {'name': 'TREASURER SUFFIX', 'number': '22'},
            {'name': 'DATE SIGNED', 'number': '23'},
            {'name': 'Cash on Hand Beginning Period', 'number': '24-6.'},
            {'name': 'Total Receipts', 'number': '25-7.'},
            {'name': 'Subtotal', 'number': '26-8.'},
            {'name': 'Total Disbursements', 'number': '27-9.'},
            {'name': 'Cash on Hand Close of Period', 'number': '28-10.'},
            {'name': 'Debts to', 'number': '29-11.'},
            {'name': 'Debts by', 'number': '30-12.'},
            {'name': 'Expenditures Subject to Limits', 'number': '31-13.'},
            {'name': 'Net Contributions', 'number': '32-14.'},
            {'name': 'Net Operating Expenditures', 'number': '33-15.'},
            {'name': 'Federal Funds', 'number': '34-16.'},
            {'name': 'Individuals', 'number': '35-17(a)'},
            {'name': 'Political Party Committees', 'number': '36-17(b)'},
            {'name': 'Other Political Committees (PACs)', 'number': '37-17(c)'},
            {'name': 'The Candidate', 'number': '38-17(d)'},
            {'name': 'Total Contributions', 'number': '39-17(e)'},
            {'name': 'Transfers From Aff/Other Party Committees', 'number': '40-18.'},
            {'name': 'Received from or Guaranteed by Cand.', 'number': '41-19(a)'},
            {'name': 'Other Loans', 'number': '42-19(b)'},
            {'name': 'Total Loans', 'number': '43-19(c)'},
            {'name': 'Operating', 'number': '44-20(a)'},
            {'name': 'Fundraising', 'number': '45-20(b)'},
            {'name': 'Legal and Accounting', 'number': '46-20(c)'},
            {'name': 'Total offsets to Expenditures', 'number': '47-20(d)'},
            {'name': 'Other Receipts', 'number': '48-21.'},
            {'name': 'Total Receipts', 'number': '49-22.'},
            {'name': 'Operating Expenditures', 'number': '50-23.'},
            {'name': 'Transfers to Other Authorized Committees', 'number': '51-24.'},
            {'name': 'Fundraising Disbursements', 'number': '52-25.'},
            {'name': 'Exempt Legal & Accounting Disbursement', 'number': '53-26.'},
            {'name': 'Made or guaranteed by Candidate', 'number': '54-27(a)'},
            {'name': 'Other Repayments', 'number': '55-27(b)'},
            {'name': 'Total Loan Repayments Made', 'number': '56-27(c)'},
            {'name': 'Individuals', 'number': '57-28(a)'},
            {'name': 'Political Party Committees', 'number': '58-28(b)'},
            {'name': 'Other Political Committees', 'number': '59-28(c)'},
            {'name': 'Total Contributions Refunds', 'number': '60-28(d)'},
            {'name': 'Other Disbursements', 'number': '61-29.'},
            {'name': 'Total Disbursements', 'number': '62-30.'},
            {'name': 'Items on Hand to be Liquidated', 'number': '63-31.'},
            {'name': 'ALABAMA', 'number': '64'},
            {'name': 'ALASKA', 'number': '65'},
            {'name': 'ARIZONA', 'number': '66'},
            {'name': 'ARKANSAS', 'number': '67'},
            {'name': 'CALIFORNIA', 'number': '68'},
            {'name': 'COLORADO', 'number': '69'},
            {'name': 'CONNECTICUT', 'number': '70'},
            {'name': 'DELAWARE', 'number': '71'},
            {'name': 'DIST OF COLUMBIA', 'number': '72'},
            {'name': 'FLORIDA', 'number': '73'},
            {'name': 'GEORGIA', 'number': '74'},
            {'name': 'HAWAII', 'number': '75'},
            {'name': 'IDAHO', 'number': '76'},
            {'name': 'ILLINOIS', 'number': '77'},
            {'name': 'INDIANA', 'number': '78'},
            {'name': 'IOWA', 'number': '79'},
            {'name': 'KANSAS', 'number': '80'},
            {'name': 'KENTUCKY', 'number': '81'},
            {'name': 'LOUISIANA', 'number': '82'},
            {'name': 'MAINE', 'number': '83'},
            {'name': 'MARYLAND', 'number': '84'},
            {'name': 'MASSACHUSETTS', 'number': '85'},
            {'name': 'MICHIGAN', 'number': '86'},
            {'name': 'MINNESOTA', 'number': '87'},
            {'name': 'MISSISSIPPI', 'number': '88'},
            {'name': 'MISSOURI', 'number': '89'},
            {'name': 'MONTANA', 'number': '90'},
            {'name': 'NEBRASKA', 'number': '91'},
            {'name': 'NEVADA', 'number': '92'},
            {'name': 'NEW HAMPSHIRE', 'number': '93'},
            {'name': 'NEW JERSEY', 'number': '94'},
            {'name': 'NEW MEXICO', 'number': '95'},
            {'name': 'NEW YORK', 'number': '96'},
            {'name': 'NORTH CAROLINA', 'number': '97'},
            {'name': 'NORTH DAKOTA', 'number': '98'},
            {'name': 'OHIO', 'number': '99'},
            {'name': 'OKLAHOMA', 'number': '100'},
            {'name': 'OREGON', 'number': '101'},
            {'name': 'PENNSYLVANIA', 'number': '102'},
            {'name': 'RHODE ISLAND', 'number': '103'},
            {'name': 'SOUTH CAROLINA', 'number': '104'},
            {'name': 'SOUTH DAKOTA', 'number': '105'},
            {'name': 'TENNESSEE', 'number': '106'},
            {'name': 'TEXAS', 'number': '107'},
            {'name': 'UTAH', 'number': '108'},
            {'name': 'VERMONT', 'number': '109'},
            {'name': 'VIRGINIA', 'number': '110'},
            {'name': 'WASHINGTON', 'number': '111'},
            {'name': 'WEST VIRGINIA', 'number': '112'},
            {'name': 'WISCONSIN', 'number': '113'},
            {'name': 'WYOMING', 'number': '114'},
            {'name': 'PUERTO RICO', 'number': '115'},
            {'name': 'GUAM', 'number': '116'},
            {'name': 'VIRGIN ISLANDS', 'number': '117'},
            {'name': 'TOTALS', 'number': '118'},
            {'name': 'Federal Funds', 'number': '119-16.'},
            {'name': 'Individuals', 'number': '120-17(a)'},
            {'name': 'Political Party Committees', 'number': '121-17(b)'},
            {'name': 'Other Political Committees (PACs)', 'number': '122-17(c)'},
            {'name': 'The Candidate', 'number': '123-17(d)'},
            {'name': 'Total contributions (Other than Loans)', 'number': '124-17(e)'},
            {'name': 'Transfers From Aff/Other Party Committees', 'number': '125-18.'},
            {'name': 'Received from or Guaranteed by Cand.', 'number': '126-19(a)'},
            {'name': 'Other Loans', 'number': '127-19(b)'},
            {'name': 'Total Loans', 'number': '128-19(c)'},
            {'name': 'Operating', 'number': '129-20(a)'},
            {'name': 'Fundraising', 'number': '130-20(b)'},
            {'name': 'Legal and Accounting', 'number': '131-20(c)'},
            {'name': 'Total Offsets to Operating Expenditures', 'number': '132-20(d)'},
            {'name': 'Other Receipts', 'number': '133-21.'},
            {'name': 'Total Receipts', 'number': '134-22.'},
            {'name': 'Operating Expenditures', 'number': '135-23.'},
            {'name': 'Transfers to Other Authorized Committees', 'number': '136-24.'},
            {'name': 'Fundraising Disbursements', 'number': '137-25.'},
            {'name': 'Exempt Legal & Accounting Disbursement', 'number': '138-26.'},
            {'name': 'Made or Guaranteed by the Candidate', 'number': '139-27(a)'},
            {'name': 'Other Repayments', 'number': '140-27(b)'},
            {'name': 'Total Loan Repayments Made', 'number': '141-27(c)'},
            {'name': 'Individuals', 'number': '142-28(a)'},
            {'name': 'Political Party Committees', 'number': '143-28(b)'},
            {'name': 'Other Political Committees', 'number': '144-28(c)'},
            {'name': 'Total Contributions Refunds', 'number': '145-28(d)'},
            {'name': 'Other Disbursements', 'number': '146-29.'},
            {'name': 'Total Disbursements', 'number': '147-30.'},
            {'name': 'ALABAMA', 'number': '148'},
            {'name': 'ALASKA', 'number': '149'},
            {'name': 'ARIZONA', 'number': '150'},
            {'name': 'ARKANSAS', 'number': '151'},
            {'name': 'CALIFORNIA', 'number': '152'},
            {'name': 'COLORADO', 'number': '153'},
            {'name': 'CONNECTICUT', 'number': '154'},
            {'name': 'DELAWARE', 'number': '155'},
            {'name': 'DIST OF COLUMBIA', 'number': '156'},
            {'name': 'FLORIDA', 'number': '157'},
            {'name': 'GEORGIA', 'number': '158'},
            {'name': 'HAWAII', 'number': '159'},
            {'name': 'IDAHO', 'number': '160'},
            {'name': 'ILLINOIS', 'number': '161'},
            {'name': 'INDIANA', 'number': '162'},
            {'name': 'IOWA', 'number': '163'},
            {'name': 'KANSAS', 'number': '164'},
            {'name': 'KENTUCKY', 'number': '165'},
            {'name': 'LOUISIANA', 'number': '166'},
            {'name': 'MAINE', 'number': '167'},
            {'name': 'MARYLAND', 'number': '168'},
            {'name': 'MASSACHUSETTS', 'number': '169'},
            {'name': 'MICHIGAN', 'number': '170'},
            {'name': 'MINNESOTA', 'number': '171'},
            {'name': 'MISSISSIPPI', 'number': '172'},
            {'name': 'MISSOURI', 'number': '173'},
            {'name': 'MONTANA', 'number': '174'},
            {'name': 'NEBRASKA', 'number': '175'},
            {'name': 'NEVADA', 'number': '176'},
            {'name': 'NEW HAMPSHIRE', 'number': '177'},
            {'name': 'NEW JERSEY', 'number': '178'},
            {'name': 'NEW MEXICO', 'number': '179'},
            {'name': 'NEW YORK', 'number': '180'},
            {'name': 'NORTH CAROLINA', 'number': '181'},
            {'name': 'NORTH DAKOTA', 'number': '182'},
            {'name': 'OHIO', 'number': '183'},
            {'name': 'OKLAHOMA', 'number': '184'},
            {'name': 'OREGON', 'number': '185'},
            {'name': 'PENNSYLVANIA', 'number': '186'},
            {'name': 'RHODE ISLAND', 'number': '187'},
            {'name': 'SOUTH CAROLINA', 'number': '188'},
            {'name': 'SOUTH DAKOTA', 'number': '189'},
            {'name': 'TENNESSEE', 'number': '190'},
            {'name': 'TEXAS', 'number': '191'},
            {'name': 'UTAH', 'number': '192'},
            {'name': 'VERMONT', 'number': '193'},
            {'name': 'VIRGINIA', 'number': '194'},
            {'name': 'WASHINGTON', 'number': '195'},
            {'name': 'WEST VIRGINIA', 'number': '196'},
            {'name': 'WISCONSIN', 'number': '197'},
            {'name': 'WYOMING', 'number': '198'},
            {'name': 'PUERTO RICO', 'number': '199'},
            {'name': 'GUAM', 'number': '200'},
            {'name': 'VIRGIN ISLANDS', 'number': '201'},
            {'name': 'TOTALS', 'number': '202'},
    ]
        self.fields_names = self.hash_names(self.fields)
