class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['Date - General Election', '3', '', ''],
            ['Date - Day after General Election', '4', '', ''],
            ['Total Contributions (No Loans)', '5', '6a', ''],
            ['Total Contribution Refunds', '6', '6b', ''],
            ['Net Contributions', '7', '6c', ''],
            ['Total Operating Expenditures', '8', '7a', ''],
            ['Total Offsets to Operating Expenditures', '9', '7b', ''],
            ['NET Operating Expenditures.', '10', '7c', ''],
            ['Individuals Itemized', '11', '11', 'a i.'],
            ['Individuals Unitemized', '12', '11', 'a.ii'],
            ['Individuals Total', '13', '11', 'a.iii'],
            ['Political Party Committees', '14', '11', 'b'],
            ['All Other Political Committees (PACS)', '15', '11', 'c'],
            ['The Candidate', '16', '11', 'd'],
            ['Total Contributions', '17', '11', 'e'],
            ['Transfers From Other AUTH Committees', '18', '12', ''],
            ['Loans made or guarn. by the Candidate', '19', '13', 'a'],
            ['All Other Loans', '20', '13', 'b'],
            ['Total Loans', '21', '13', 'c'],
            ['Offsets to Operating Expenditures', '22', '14', ''],
            ['Other Receipts', '23', '15', ''],
            ['Total Receipts', '24', '16', ''],
            ['Operating Expenditures', '25', '17', ''],
            ['Transfers To Other AUTH Committees', '26', '18', ''],
            ['Loan Repayment By Candidate', '27', '19', 'a'],
            ['Loan Repayments, ALL Other Loans', '28', '19', 'b'],
            ['Total Loan Repayments', '29', '19', 'c'],
            ['Refund/Individuals Other than Political Committees', '30', '20', 'a'],
            ['Refund, Political Party Committees', '31', '20', 'b'],
            ['Refund, Other Political Committees', '32', '20', 'c'],
            ['Total Contributions Refunds', '33', '20', 'd'],
            ['Other Disbursements', '34', '21', ''],
            ['Total Disbursements', '35', '22', ''],
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['Date - General Election', '3', '', ''],
            ['Date - Day after General Election', '4', '', ''],
            ['Net Contributions', '5', '14', ''],
            ['Net Expenditures', '6', '15', ''],
            ['Federal Funds', '7', '16', ''],
            ['Individuals', '8', '17', 'a'],
            ['Political Party Committees', '9', '17', 'b'],
            ['Other Political Committees (PACs)', '10', '17', 'c'],
            ['The Candidate', '11', '17', 'd'],
            ['Total contributions (Other than Loans)', '12', '17', 'e'],
            ['Transfers From Aff/Other Party Committees', '13', '18', ''],
            ['Received from or Guaranteed by Candidate', '14', '19', 'a'],
            ['Other Loans', '15', '19', 'b'],
            ['Total Loans', '16', '19', 'c'],
            ['Operating', '17', '20', 'a'],
            ['Fundraising', '18', '20', 'b'],
            ['Legal and Accounting', '19', '20', 'c'],
            ['Total Offsets to Operating Expenditures', '20', '20', 'd'],
            ['Other Receipts', '21', '21', ''],
            ['Total Receipts', '22', '22', ''],
            ['Operating Expenditures', '23', '23', ''],
            ['Transfers to Other Authorized Committees', '24', '24', ''],
            ['Fundraising Disbursements', '25', '25', ''],
            ['Exempt Legal and Accounting Disbursements', '26', '26', ''],
            ['Made or Guaranteed by the Candidate', '27', '27', 'a'],
            ['Other Repayments', '28', '27', 'b'],
            ['Total Loan Repayments Made', '29', '27', 'c'],
            ['Individuals', '30', '28', 'a'],
            ['Political Party Committees', '31', '28', 'b'],
            ['Other Political Committees', '32', '28', 'c'],
            ['Total Contributions Refunds', '33', '28', 'd'],
            ['Other Disbursements', '34', '29', ''],
            ['Total Disbursements', '35', '30', ''],
            ['ALABAMA', '36', '', ''],
            ['ALASKA', '37', '', ''],
            ['ARIZONA', '38', '', ''],
            ['ARKANSAS', '39', '', ''],
            ['CALIFORNIA', '40', '', ''],
            ['COLORADO', '41', '', ''],
            ['CONNECTICUT', '42', '', ''],
            ['DELAWARE', '43', '', ''],
            ['DIST OF COLUMBIA', '44', '', ''],
            ['FLORIDA', '45', '', ''],
            ['GEORGIA', '46', '', ''],
            ['HAWAII', '47', '', ''],
            ['IDAHO', '48', '', ''],
            ['ILLINOIS', '49', '', ''],
            ['INDIANA', '50', '', ''],
            ['IOWA', '51', '', ''],
            ['KANSAS', '52', '', ''],
            ['KENTUCKY', '53', '', ''],
            ['LOUISIANA', '54', '', ''],
            ['MAINE', '55', '', ''],
            ['MARYLAND', '56', '', ''],
            ['MASSACHUSETTS', '57', '', ''],
            ['MICHIGAN', '58', '', ''],
            ['MINNESOTA', '59', '', ''],
            ['MISSISSIPPI', '60', '', ''],
            ['MISSOURI', '61', '', ''],
            ['MONTANA', '62', '', ''],
            ['NEBRASKA', '63', '', ''],
            ['NEVADA', '64', '', ''],
            ['NEW HAMPSHIRE', '65', '', ''],
            ['NEW JERSEY', '66', '', ''],
            ['NEW MEXICO', '67', '', ''],
            ['NEW YORK', '68', '', ''],
            ['NORTH CAROLINA', '69', '', ''],
            ['NORTH DAKOTA', '70', '', ''],
            ['OHIO', '71', '', ''],
            ['OKLAHOMA', '72', '', ''],
            ['OREGON', '73', '', ''],
            ['PENNSYLVANIA', '74', '', ''],
            ['RHODE ISLAND', '75', '', ''],
            ['SOUTH CAROLINA', '76', '', ''],
            ['SOUTH DAKOTA', '77', '', ''],
            ['TENNESSEE', '78', '', ''],
            ['TEXAS', '79', '', ''],
            ['UTAH', '80', '', ''],
            ['VERMONT', '81', '', ''],
            ['VIRGINIA', '82', '', ''],
            ['WASHINGTON', '83', '', ''],
            ['WEST VIRGINIA', '84', '', ''],
            ['WISCONSIN', '85', '', ''],
            ['WYOMING', '86', '', ''],
            ['PUERTO RICO', '87', '', ''],
            ['GUAM', '88', '', ''],
            ['VIRGIN ISLANDS', '89', '', ''],
            ['TOTALS', '90', '', ''],
    ]
