class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['RECORD ID NUMBER (for account name)', '4', '', ''],
            ['ACCOUNT NAME', '5', '', ''],
            ['Bank Account ID Number', '6', '', ''],
            ['COVERAGE FROM DATE', '7', '', ''],
            ['COVERAGE THROUGH DATE', '8', '', ''],
            ['Total Receipts', '9', '1', ''],
            ['Transfers to FED or allocation', '10', '2', ''],
            ['Transfers to state/local Party organizations', '11', '3', ''],
            ['Direct state/local candidate support', '12', '4', ''],
            ['Other Disbursements', '13', '5', ''],
            ['Total Disbursements', '14', '6', ''],
            ['Beginning COH', '15', '7', ''],
            ['Receipts', '16', '8', ''],
            ['Subtotal', '17', '9', ''],
            ['Disbursements', '18', '10', ''],
            ['Ending COH', '19', '11', ''],
            ['Total receipts', '20', '1', ''],
            ['Transfers to FED or allocation', '21', '2', ''],
            ['Transfers to state/local Party organizations', '22', '3', ''],
            ['Direct state/local candidate support', '23', '4', ''],
            ['Other Disbursements', '24', '5', ''],
            ['Total Disbursements', '25', '6', ''],
            ['Beginning COH (as of Jan 1)', '26', '7', ''],
            ['Receipts', '27', '8', ''],
            ['Subtotal', '28', '9', ''],
            ['Disbursements', '29', '10', ''],
            ['Ending COH', '30', '11', ''],
    ]
