class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC COMMITTEE ID', '2', '', ''],
            ['CANDIDATE NAME', '3', '1', ''],
            ['CANDIDATE ID', '4', '2', ''],
            ['CAN/OFFICE', '5', '3', ''],
            ['CANDIDATE STATE', '6', '4', ''],
            ['CANDIDATE DISTRICT', '7', '5', ''],
            ['COMMITTEE NAME', '8', '6', ''],
            ['STREET 1', '9', '8', ''],
            ['STREET 2', '10', '8', ''],
            ['CITY', '11', '9', ''],
            ['STATE', '12', '9', ''],
            ['ZIP', '13', '9', ''],
            ['NAME OF CANDIDATE', '14', '10', ''],
            ['NAME OF COMMITTEE', '15', '11', ''],
            ['COMMITTEE ID', '16', '12', ''],
            ['COMMITTEE STREET 1', '17', '13', ''],
            ['COMMITTEE STREET 2', '18', '13', ''],
            ['COMMITTEE CITY', '19', '14', ''],
            ['COMMITTEE STATE', '20', '14', ''],
            ['COMMITTEE ZIP', '21', '14', ''],
            ['DATE OF FORM 10 RECEIPT', '22', '15', ''],
            ['OPPOSITION PERS FUNDS AMT', '23', '16', ''],
            ['ITEM ELECT CD', '24', '', ''],
            ['ITEM ELECT OTHER', '25', '', ''],
            ['TYPE', '26', '', ''],
            ['NAME/CANDIDATE/TREAS (as signed)', '27', '', ''],
            ['Signed', '28-', '', ''],
    ]
