class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['CONTRIBUTOR NAME', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['ITEM ELECT CD', '10', '', ''],
            ['ITEM ELECT OTHER', '11', '', ''],
            ['INDEMP', '12', '', ''],
            ['INDOCC', '13', '', ''],
            ['AGGREGATE AMT Y-T-D', '14', '', ''],
            ['DATE RECEIVED', '15', '', ''],
            ['AMOUNT RECEIVED', '16', '', ''],
            ['TRANS CODE', '17', '', ''],
            ['TRANS DESCRIP', '18', '', ''],
            ['FEC COMMITTEE ID NUMBER', '19', '', ''],
            ['FEC CANDIDATE ID NUMBER', '20', '', ''],
            ['CANDIDATE NAME', '21', '', ''],
            ['CAN/OFFICE', '22', '', ''],
            ['CAN/STATE', '23', '', ''],
            ['CAN/DIST', '24', '', ''],
            ['CONDUIT NAME', '25', '', ''],
            ['CONDUIT STREET1', '26', '', ''],
            ['CONDUIT STREET2', '27', '', ''],
            ['CONDUIT CITY', '28', '', ''],
            ['CONDUIT STATE', '29', '', ''],
            ['CONDUIT ZIP', '30', '', ''],
            ['MEMO CODE', '31', '', ''],
            ['MEMO TEXT', '32', '', ''],
            ['AMENDED CD', '33', '', ''],
            ['TRAN ID', '34', '', ''],
            ['BACK REF TRAN ID', '35', '', ''],
            ['BACK REF SCHED NAME', '36', '', ''],
            ['Reference to SI or SL system code that identifies the Account', '37', '', ''],
            ['INCREASED LIMIT', '38', '', ''],
            ['CONTRIB ORGANIZATION NAME', '39', '', ''],
            ['CONTRIBUTOR LAST NAME', '40', '', ''],
            ['CONTRIBUTOR FIRST NAME', '41', '', ''],
            ['CONTRIBUTOR MIDDLE NAME', '42', '', ''],
            ['CONTRIBUTOR PREFIX', '43', '', ''],
            ['CONTRIBUTOR SUFFIX', '44', '', ''],
    ]
