class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['BACK REFERENCE TRAN ID', '3', '', ''],
            ['ENTITY TYPE', '4', '', ''],
            ['NAME (Loan Source)', '5', '', ''],
            ['STREET 1', '6', '', ''],
            ['STREET 2', '7', '', ''],
            ['CITY', '8', '', ''],
            ['STATE', '9', '', ''],
            ['ZIP', '10', '', ''],
            ['AMT OF LOAN', '11', '', ''],
            ['LOAN INTEREST RATE PERCENT', '12', '', ''],
            ['Incurred', '13-', '', ''],
            ['Due', '14-', '', ''],
            ['Loan Restructured', '15-A1.', '', ''],
            ['Of Original Loan', '16-A2. ', '', ''],
            ['CREDIT AMOUNT THIS DRAW', '17-B.1.', '', ''],
            ['TOTAL BALANCE', '18-B.2.', '', ''],
            ['Others liable?', '19-C. ', '', ''],
            ['Collateral?', '20-D. ', '', ''],
            ['Collateral', '21-D.1 ', '', ''],
            ['COLLATERAL VALUE/AMOUNT', '22', 'D.2', ''],
            ['Perfected Interest?)', '23-D.3 ', '', ''],
            ['Future Income', '24-E.1 ', '', ''],
            ['Specification of the above', '25-E.2 ', '', ''],
            ['ESTIMATED VALUE', '26', 'E.3', ''],
            ['Depository account established', '27-E.4 ', '', ''],
            ['Account Location', '28-E.5 ', '', ''],
            ['STREET 1', '29', 'E.6', ''],
            ['STREET 2', '30', 'E.7', ''],
            ['CITY', '31', 'E.8', ''],
            ['STATE', '32', 'E.9', ''],
            ['ZIP', '33', 'E.10', ''],
            ['Presidential', '34-E.11 DEP ACCT AUTH ', '', ''],
            ['State basis of loan', '35-F. ', '', ''],
            ['NAME/TREASURER (as signed)', '36', 'G', ''],
            ['SIG/DATE', '37', 'G', ''],
            ['NAME/AUTH (as signed)', '38', 'H', ''],
            ['AUTH/TITLE', '39', 'H', ''],
            ['AUTH/SIG DATE', '40', 'H', ''],
            ['AMENDED CD', '41', '', ''],
    ]
