class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['Has filer been designated to make Coodinated Expenditures?', '3-DESIG ', '', ''],
            ['FEC COMMITTEE ID NUMBER (Designating)', '4', '', ''],
            ['COMMITTEE NAME', '5', '', ''],
            ['FEC COMMITTEE ID NUMBER (Subordinating)', '6', '', ''],
            ['COMMITTEE NAME', '7', '', ''],
            ['STREET 1', '8', '', ''],
            ['STREET 2', '9', '', ''],
            ['CITY', '10', '', ''],
            ['STATE', '11', '', ''],
            ['ZIP', '12', '', ''],
            ['ENTITY TYPE', '13', '', ''],
            ['NAME (Payee)', '14', '', ''],
            ['STREET 1', '15', '', ''],
            ['STREET 2', '16', '', ''],
            ['CITY', '17', '', ''],
            ['STATE', '18', '', ''],
            ['ZIP', '19', '', ''],
            ['AGG. GENERAL ELECT AMOUNT EXPENDED', '20', '', ''],
            ['TRANS Purpose DESCRIP', '21', '', ''],
            ['DATE', '22', '', ''],
            ['AMOUNT', '23', '', ''],
            ['FEC COMMITTEE ID NUMBER', '24', '', ''],
            ['FEC CANDIDATE ID NUMBER', '25', '', ''],
            ['CANDIDATE NAME', '26', '', ''],
            ['CAN/OFFICE', '27', '', ''],
            ['CAN/STATE', '28', '', ''],
            ['CAN/DIST', '29', '', ''],
            ['CONDUIT NAME', '30', '', ''],
            ['CONDUIT STREET 1', '31', '', ''],
            ['CONDUIT STREET 2', '32', '', ''],
            ['CONDUIT CITY', '33', '', ''],
            ['CONDUIT STATE', '34', '', ''],
            ['CONDUIT ZIP', '35', '', ''],
            ['AMENDED CD', '36', '', ''],
            ['TRAN ID', '37', '', ''],
            ['MEMO CODE', '38', '', ''],
            ['MEMO TEXT', '39', '', ''],
            ['BACK REF TRAN ID', '40', '', ''],
            ['BACK REF SCHED NAME', '41', '', ''],
            ['UNLIMITED SPENDING', '42', '', ''],
            ['CATEGORY CODE', '43', '', ''],
            ['TRANS CODE', '44', '', ''],
    ]
