import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER FEC CMTE ID', 'number': '2'},
            {'name': 'Has filer been designated to make Coodinated Expenditures?', 'number': '3-DESIG '},
            {'name': 'FEC COMMITTEE ID NUMBER (Designating)', 'number': '4'},
            {'name': 'COMMITTEE NAME', 'number': '5'},
            {'name': 'FEC COMMITTEE ID NUMBER (Subordinating)', 'number': '6'},
            {'name': 'COMMITTEE NAME', 'number': '7'},
            {'name': 'STREET 1', 'number': '8'},
            {'name': 'STREET 2', 'number': '9'},
            {'name': 'CITY', 'number': '10'},
            {'name': 'STATE', 'number': '11'},
            {'name': 'ZIP', 'number': '12'},
            {'name': 'ENTITY TYPE', 'number': '13'},
            {'name': 'NAME (Payee)', 'number': '14'},
            {'name': 'STREET 1', 'number': '15'},
            {'name': 'STREET 2', 'number': '16'},
            {'name': 'CITY', 'number': '17'},
            {'name': 'STATE', 'number': '18'},
            {'name': 'ZIP', 'number': '19'},
            {'name': 'AGG. GENERAL ELECT AMOUNT EXPENDED', 'number': '20'},
            {'name': 'TRANS Purpose DESCRIP', 'number': '21'},
            {'name': 'DATE', 'number': '22'},
            {'name': 'AMOUNT', 'number': '23'},
            {'name': 'FEC COMMITTEE ID NUMBER', 'number': '24'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '25'},
            {'name': 'CANDIDATE NAME', 'number': '26'},
            {'name': 'CAN/OFFICE', 'number': '27'},
            {'name': 'CAN/STATE', 'number': '28'},
            {'name': 'CAN/DIST', 'number': '29'},
            {'name': 'CONDUIT NAME', 'number': '30'},
            {'name': 'CONDUIT STREET 1', 'number': '31'},
            {'name': 'CONDUIT STREET 2', 'number': '32'},
            {'name': 'CONDUIT CITY', 'number': '33'},
            {'name': 'CONDUIT STATE', 'number': '34'},
            {'name': 'CONDUIT ZIP', 'number': '35'},
            {'name': 'AMENDED CD', 'number': '36'},
            {'name': 'TRAN ID', 'number': '37'},
            {'name': 'MEMO CODE', 'number': '38'},
            {'name': 'MEMO TEXT', 'number': '39'},
            {'name': 'BACK REF TRAN ID', 'number': '40'},
            {'name': 'BACK REF SCHED NAME', 'number': '41'},
            {'name': 'UNLIMITED SPENDING', 'number': '42'},
            {'name': 'CATEGORY CODE', 'number': '43'},
            {'name': 'TRANS CODE', 'number': '44'},
    ]
        self.fields_names = self.hash_names(self.fields)
