class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['NAT PARTY COMMITTEES %', '3', '', ''],
            ['HSE/SEN PTY COMMITTEES MINIMUM FED %', '4', '', ''],
            ['HSE/SEN PTY COMMITTEES PERCENTAGE ESTIMATED FEDERAL CAN SUPPORT', '5', '', ''],
            ['HSE/SEN PTY COMMITTEES PERCENTAGE ESTIMATED NON FEDERAL CAN SUPPORT', '6', '', ''],
            ['HSE/SEN PTY COMMITTEES ACTUAL FEDERAL CAN SUPPORT', '7', '', ''],
            ['HSE/SEN PTY COMMITTEES ACTUAL NON FEDERAL CAN SUPPORT', '8', '', ''],
            ['HSE/SEN PTY COMMITTEES PERCENTAGE ACTUAL FEDERAL', '9', '', ''],
            ['Estimated Direct Cand Support - Federal Percent', '10', '', ''],
            ['Estimated Direct Cand Support - Non-Federal Pct', '11', '', ''],
            ['Actual Direct Candidate Support - Federal Amount', '12', '', ''],
            ['Actual Direct Candidate Support - Non-Fed Amount', '13', '', ''],
            ['Actual Direct Candidate Support - Federal Percent', '14', '', ''],
            ['BALLOT COMP PRES BLANK OR 1', '15', '1', ''],
            ['BALLOT COMP SEN BLANK OR 1', '16', '2', ''],
            ['BALLOT COMP HSE BLANK OR 1', '17', '3', ''],
            ['SUBTOTAL FED', '18', '4', ''],
            ['BALLOT COMP GOV BLANK OR 1', '19', '5', ''],
            ['OTHER STATEWIDE', '20', '6', ''],
            ['STATE SENATE', '21', '7', ''],
            ['STATE REP.', '22', '8', ''],
            ['LOCAL CANDIDATES BLANK, 1 OR 2', '23', '9', ''],
            ['EXTRA NON-FED POINT BLANK OR 1', '24', '10', ''],
            ['SUBTOTAL', '25', '11', ''],
            ['TOTAL POINTS', '26', '12', ''],
            ['FEDERAL ALLOCATION PERCENTAGE', '27', '', ''],
            ['AMENDED CD', '28', '', ''],
            ['TRAN ID', '29', '', ''],
            ['State and Local Party Committee Presidential-Only Election Year (28% Federal)', '30', '', ''],
            ['State and Local Party Committee Presidential and Senate Election Year (36% Federal)', '31', '', ''],
            ['State and Local Party Committee Senate-Only Election Year (21% Federal)', '32', '', ''],
            ['State and Local Party Committee Non-Presidential and Non-Senate Election Year (15% Federal)', '33', '', ''],
    ]
