class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['NAME (Payee)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['CATEGORY CODE', '10', '', ''],
            ['TRANS CODE', '11', '', ''],
            ['TRANS Purpose DESCRIP', '12', '', ''],
            ['DATE', '13', '', ''],
            ['TOTAL AMOUNT', '14', '', ''],
            ['FEDERAL SHARE', '15', '', ''],
            ['LEVIN SHARE', '16', '', ''],
            ['Activity Is Voter Registration', '17-', '', ''],
            ['Activity Is Voter ID', '18-', '', ''],
            ['Activity GOTV', '19-', '', ''],
            ['Activity is Generic Campaign', '20-', '', ''],
            ['ACTIVITY/EVENT YEAR-TO-DATE', '21', '', ''],
            ['ADDITIONAL DESCRIPTION', '22', '', ''],
            ['FEC COMMITTEE ID NUMBER', '23', '', ''],
            ['FEC CANDIDATE ID NUMBER', '24', '', ''],
            ['CANDIDATE NAME', '25', '', ''],
            ['CAN/OFFICE', '26', '', ''],
            ['CAN/STATE', '27', '', ''],
            ['CAN/DIST', '28', '', ''],
            ['CONDUIT COMMITTEE ID', '29', '', ''],
            ['CONDUIT NAME', '30', '', ''],
            ['CONDUIT STREET 1', '31', '', ''],
            ['CONDUIT STREET 2', '32', '', ''],
            ['CONDUIT CITY', '33', '', ''],
            ['CONDUIT STATE', '34', '', ''],
            ['CONDUIT ZIP', '35', '', ''],
            ['MEMO CODE', '36', '', ''],
            ['MEMO TEXT', '37', '', ''],
            ['AMENDED CD', '38', '', ''],
            ['TRAN ID', '39', '', ''],
            ['BACK REF TRAN ID', '40', '', ''],
            ['BACK REF SCHED NAME', '41', '', ''],
    ]
