lint:

	~/.local/bin/pylint --output-format=parseable ./e_filing_headers_all_versions.py \
./versions.py											\
./fec/version/versions_base.py									\
./fec/version/v7_0/F2.py									\
./fec/version/v7_0/SD.py									\
./fec/version/v7_0/SB.py									\
./fec/version/v7_0/F13.py									\
./fec/version/v7_0/F9.py									\
./fec/version/v7_0/F133.py									\
./fec/version/v7_0/SH1.py									\
./fec/version/v7_0/F1.py									\
./fec/version/v7_0/F4.py									\
./fec/version/v7_0/F7.py									\
./fec/version/v7_0/SF.py									\
./fec/version/v7_0/F6.py									\
./fec/version/v7_0/F56.py									\
./fec/version/v7_0/SH4.py									\
./fec/version/v7_0/F3P31.py									\
./fec/version/v7_0/HRD.py									\
./fec/version/v7_0/F57.py									\
./fec/version/v7_0/SH3.py									\
./fec/version/v7_0/F3PS.py									\
./fec/version/v7_0/SH2.py									\
./fec/version/v7_0/TEXT.py									\
./fec/version/v7_0/SI.py									\
./fec/version/v7_0/SC2.py									\
./fec/version/v7_0/__init__.py									\
./fec/version/v7_0/F93.py									\
./fec/version/v7_0/F24.py									\
./fec/version/v7_0/F1M.py									\
./fec/version/v7_0/F3L.py									\
./fec/version/v7_0/SC1.py									\
./fec/version/v7_0/F65.py									\
./fec/version/v7_0/SH5.py									\
./fec/version/v7_0/F94.py									\
./fec/version/v7_0/F99.py									\
./fec/version/v7_0/SL.py									\
./fec/version/v7_0/F3Z.py									\
./fec/version/v7_0/F132.py									\
./fec/version/v7_0/F3X.py									\
./fec/version/v7_0/F2S.py									\
./fec/version/v7_0/F76.py									\
./fec/version/v7_0/SH6.py									\
./fec/version/v7_0/SE.py									\
./fec/version/v7_0/F3S.py									\
./fec/version/v7_0/F1S.py									\
./fec/version/v7_0/F91.py									\
./fec/version/v7_0/SA.py									\
./fec/version/v7_0/F92.py									\
./fec/version/v7_0/F3P.py									\
./fec/version/v7_0/F3.py									\
./fec/version/v7_0/F5.py									\
./fec/version/v7_0/SC.py									\
./fec/version/v6_1.py										\
./fec/version/version_base.py									\
./fec/version/v7_0.py										\
./fec/version/v1.py										\
./fec/version/v5_3.py										\
./fec/version/v6_1/F2.py									\
./fec/version/v6_1/SD.py									\
./fec/version/v6_1/SB.py									\
./fec/version/v6_1/F13.py									\
./fec/version/v6_1/F9.py									\
./fec/version/v6_1/F105.py									\
./fec/version/v6_1/F82.py									\
./fec/version/v6_1/F133.py									\
./fec/version/v6_1/SH1.py									\
./fec/version/v6_1/F1.py									\
./fec/version/v6_1/F4.py									\
./fec/version/v6_1/F7.py									\
./fec/version/v6_1/SF.py									\
./fec/version/v6_1/F6.py									\
./fec/version/v6_1/F56.py									\
./fec/version/v6_1/SH4.py									\
./fec/version/v6_1/F3P31.py									\
./fec/version/v6_1/HRD.py									\
./fec/version/v6_1/F57.py									\
./fec/version/v6_1/SH3.py									\
./fec/version/v6_1/F3PS.py									\
./fec/version/v6_1/SH2.py									\
./fec/version/v6_1/TEXT.py									\
./fec/version/v6_1/SI.py									\
./fec/version/v6_1/SC2.py									\
./fec/version/v6_1/__init__.py									\
./fec/version/v6_1/F93.py									\
./fec/version/v6_1/F24.py									\
./fec/version/v6_1/F1M.py									\
./fec/version/v6_1/SC1.py									\
./fec/version/v6_1/F65.py									\
./fec/version/v6_1/SH5.py									\
./fec/version/v6_1/F94.py									\
./fec/version/v6_1/F99.py									\
./fec/version/v6_1/SL.py									\
./fec/version/v6_1/F10.py									\
./fec/version/v6_1/F3Z.py									\
./fec/version/v6_1/F132.py									\
./fec/version/v6_1/F3X.py									\
./fec/version/v6_1/F2S.py									\
./fec/version/v6_1/F76.py									\
./fec/version/v6_1/SH6.py									\
./fec/version/v6_1/SE.py									\
./fec/version/v6_1/F8.py									\
./fec/version/v6_1/F3S.py									\
./fec/version/v6_1/F1S.py									\
./fec/version/v6_1/F91.py									\
./fec/version/v6_1/F83.py									\
./fec/version/v6_1/SA.py									\
./fec/version/v6_1/F92.py									\
./fec/version/v6_1/F3P.py									\
./fec/version/v6_1/F3.py									\
./fec/version/v6_1/F5.py									\
./fec/version/v6_1/SC.py									\
./fec/version/v8_0/F2.py									\
./fec/version/v8_0/SD.py									\
./fec/version/v8_0/SB.py									\
./fec/version/v8_0/F13.py									\
./fec/version/v8_0/F9.py									\
./fec/version/v8_0/F133.py									\
./fec/version/v8_0/SH1.py									\
./fec/version/v8_0/F1.py									\
./fec/version/v8_0/F4.py									\
./fec/version/v8_0/F7.py									\
./fec/version/v8_0/SF.py									\
./fec/version/v8_0/F6.py									\
./fec/version/v8_0/F56.py									\
./fec/version/v8_0/SH4.py									\
./fec/version/v8_0/F3P31.py									\
./fec/version/v8_0/HRD.py									\
./fec/version/v8_0/F57.py									\
./fec/version/v8_0/SH3.py									\
./fec/version/v8_0/F3PS.py									\
./fec/version/v8_0/SH2.py									\
./fec/version/v8_0/TEXT.py									\
./fec/version/v8_0/SC2.py									\
./fec/version/v8_0/__init__.py									\
./fec/version/v8_0/F93.py									\
./fec/version/v8_0/F24.py									\
./fec/version/v8_0/F1M.py									\
./fec/version/v8_0/F3L.py									\
./fec/version/v8_0/SC1.py									\
./fec/version/v8_0/F65.py									\
./fec/version/v8_0/SH5.py									\
./fec/version/v8_0/F94.py									\
./fec/version/v8_0/F99.py									\
./fec/version/v8_0/SL.py									\
./fec/version/v8_0/F3Z.py									\
./fec/version/v8_0/F132.py									\
./fec/version/v8_0/F3X.py									\
./fec/version/v8_0/F2S.py									\
./fec/version/v8_0/F76.py									\
./fec/version/v8_0/SH6.py									\
./fec/version/v8_0/SE.py									\
./fec/version/v8_0/F3S.py									\
./fec/version/v8_0/F1S.py									\
./fec/version/v8_0/F91.py									\
./fec/version/v8_0/SA.py									\
./fec/version/v8_0/F92.py									\
./fec/version/v8_0/F3P.py									\
./fec/version/v8_0/F3.py									\
./fec/version/v8_0/F5.py									\
./fec/version/v8_0/SC.py									\
./fec/version/v6_2/F2.py									\
./fec/version/v6_2/SD.py									\
./fec/version/v6_2/SB.py									\
./fec/version/v6_2/F13.py									\
./fec/version/v6_2/F9.py									\
./fec/version/v6_2/F105.py									\
./fec/version/v6_2/F82.py									\
./fec/version/v6_2/F133.py									\
./fec/version/v6_2/SH1.py									\
./fec/version/v6_2/F1.py									\
./fec/version/v6_2/F4.py									\
./fec/version/v6_2/F7.py									\
./fec/version/v6_2/SF.py									\
./fec/version/v6_2/F6.py									\
./fec/version/v6_2/F56.py									\
./fec/version/v6_2/SH4.py									\
./fec/version/v6_2/F3P31.py									\
./fec/version/v6_2/HRD.py									\
./fec/version/v6_2/F57.py									\
./fec/version/v6_2/SH3.py									\
./fec/version/v6_2/F3PS.py									\
./fec/version/v6_2/SH2.py									\
./fec/version/v6_2/TEXT.py									\
./fec/version/v6_2/SI.py									\
./fec/version/v6_2/SC2.py									\
./fec/version/v6_2/__init__.py									\
./fec/version/v6_2/F93.py									\
./fec/version/v6_2/F24.py									\
./fec/version/v6_2/F1M.py									\
./fec/version/v6_2/SC1.py									\
./fec/version/v6_2/F65.py									\
./fec/version/v6_2/SH5.py									\
./fec/version/v6_2/F94.py									\
./fec/version/v6_2/F99.py									\
./fec/version/v6_2/SL.py									\
./fec/version/v6_2/F10.py									\
./fec/version/v6_2/F3Z.py									\
./fec/version/v6_2/F132.py									\
./fec/version/v6_2/F3X.py									\
./fec/version/v6_2/F2S.py									\
./fec/version/v6_2/F76.py									\
./fec/version/v6_2/SH6.py									\
./fec/version/v6_2/SE.py									\
./fec/version/v6_2/F8.py									\
./fec/version/v6_2/F3S.py									\
./fec/version/v6_2/F1S.py									\
./fec/version/v6_2/F91.py									\
./fec/version/v6_2/F83.py									\
./fec/version/v6_2/SA.py									\
./fec/version/v6_2/F92.py									\
./fec/version/v6_2/F3P.py									\
./fec/version/v6_2/F3.py									\
./fec/version/v6_2/F5.py									\
./fec/version/v6_2/SC.py									\
./fec/version/v5_3/F2.py									\
./fec/version/v5_3/SD.py									\
./fec/version/v5_3/SB.py									\
./fec/version/v5_3/F13.py									\
./fec/version/v5_3/F9.py									\
./fec/version/v5_3/F105.py									\
./fec/version/v5_3/F82.py									\
./fec/version/v5_3/F133.py									\
./fec/version/v5_3/SH1.py									\
./fec/version/v5_3/F1.py									\
./fec/version/v5_3/F4.py									\
./fec/version/v5_3/F7.py									\
./fec/version/v5_3/SF.py									\
./fec/version/v5_3/F6.py									\
./fec/version/v5_3/F56.py									\
./fec/version/v5_3/SH4.py									\
./fec/version/v5_3/F3P31.py									\
./fec/version/v5_3/HRD.py									\
./fec/version/v5_3/F57.py									\
./fec/version/v5_3/SH3.py									\
./fec/version/v5_3/F3PS.py									\
./fec/version/v5_3/SH2.py									\
./fec/version/v5_3/TEXT.py									\
./fec/version/v5_3/SI.py									\
./fec/version/v5_3/SC2.py									\
./fec/version/v5_3/__init__.py									\
./fec/version/v5_3/F93.py									\
./fec/version/v5_3/F24.py									\
./fec/version/v5_3/F1M.py									\
./fec/version/v5_3/SC1.py									\
./fec/version/v5_3/F65.py									\
./fec/version/v5_3/SH5.py									\
./fec/version/v5_3/F94.py									\
./fec/version/v5_3/F99.py									\
./fec/version/v5_3/SL.py									\
./fec/version/v5_3/F10.py									\
./fec/version/v5_3/F3Z.py									\
./fec/version/v5_3/F132.py									\
./fec/version/v5_3/F3X.py									\
./fec/version/v5_3/F76.py									\
./fec/version/v5_3/SH6.py									\
./fec/version/v5_3/SE.py									\
./fec/version/v5_3/F8.py									\
./fec/version/v5_3/F3S.py									\
./fec/version/v5_3/F1S.py									\
./fec/version/v5_3/F91.py									\
./fec/version/v5_3/F83.py									\
./fec/version/v5_3/SA.py									\
./fec/version/v5_3/F92.py									\
./fec/version/v5_3/F3P.py									\
./fec/version/v5_3/F3.py									\
./fec/version/v5_3/F5.py									\
./fec/version/v5_3/SC.py									\
./fec/version/v2/F2.py										\
./fec/version/v2/SD.py										\
./fec/version/v2/SB.py										\
./fec/version/v2/F82.py										\
./fec/version/v2/SH1.py										\
./fec/version/v2/F1.py										\
./fec/version/v2/F4.py										\
./fec/version/v2/F7.py										\
./fec/version/v2/SF.py										\
./fec/version/v2/F6.py										\
./fec/version/v2/F56.py										\
./fec/version/v2/SH4.py										\
./fec/version/v2/F3P31.py									\
./fec/version/v2/F57.py										\
./fec/version/v2/SH3.py										\
./fec/version/v2/SH2.py										\
./fec/version/v2/SI.py										\
./fec/version/v2/SC2.py										\
./fec/version/v2/__init__.py									\
./fec/version/v2/F1M.py										\
./fec/version/v2/SC1.py										\
./fec/version/v2/F65.py										\
./fec/version/v2/F3Z.py										\
./fec/version/v2/F3X.py										\
./fec/version/v2/F76.py										\
./fec/version/v2/SE.py										\
./fec/version/v2/F8.py										\
./fec/version/v2/F83.py										\
./fec/version/v2/SA.py										\
./fec/version/v2/F3P.py										\
./fec/version/v2/F3.py										\
./fec/version/v2/F5.py										\
./fec/version/v2/SC.py										\
./fec/version/v5_0/F2.py									\
./fec/version/v5_0/SD.py									\
./fec/version/v5_0/SB.py									\
./fec/version/v5_0/F9.py									\
./fec/version/v5_0/F105.py									\
./fec/version/v5_0/F82.py									\
./fec/version/v5_0/SH1.py									\
./fec/version/v5_0/F1.py									\
./fec/version/v5_0/F12.py									\
./fec/version/v5_0/F4.py									\
./fec/version/v5_0/F7.py									\
./fec/version/v5_0/SF.py									\
./fec/version/v5_0/F6.py									\
./fec/version/v5_0/F56.py									\
./fec/version/v5_0/SH4.py									\
./fec/version/v5_0/F3P31.py									\
./fec/version/v5_0/HRD.py									\
./fec/version/v5_0/F57.py									\
./fec/version/v5_0/SH3.py									\
./fec/version/v5_0/F3PS.py									\
./fec/version/v5_0/SH2.py									\
./fec/version/v5_0/TEXT.py									\
./fec/version/v5_0/SI.py									\
./fec/version/v5_0/SC2.py									\
./fec/version/v5_0/__init__.py									\
./fec/version/v5_0/F93.py									\
./fec/version/v5_0/F24.py									\
./fec/version/v5_0/F1M.py									\
./fec/version/v5_0/SC1.py									\
./fec/version/v5_0/F65.py									\
./fec/version/v5_0/SH5.py									\
./fec/version/v5_0/F94.py									\
./fec/version/v5_0/F99.py									\
./fec/version/v5_0/SL.py									\
./fec/version/v5_0/F10.py									\
./fec/version/v5_0/F3Z.py									\
./fec/version/v5_0/F3X.py									\
./fec/version/v5_0/F76.py									\
./fec/version/v5_0/SH6.py									\
./fec/version/v5_0/SE.py									\
./fec/version/v5_0/F8.py									\
./fec/version/v5_0/F3S.py									\
./fec/version/v5_0/F1S.py									\
./fec/version/v5_0/F91.py									\
./fec/version/v5_0/F83.py									\
./fec/version/v5_0/SA.py									\
./fec/version/v5_0/F92.py									\
./fec/version/v5_0/F3P.py									\
./fec/version/v5_0/F3.py									\
./fec/version/v5_0/F11.py									\
./fec/version/v5_0/F5.py									\
./fec/version/v5_0/SC.py									\
./fec/version/v3/F2.py										\
./fec/version/v3/SD.py										\
./fec/version/v3/SB.py										\
./fec/version/v3/F82.py										\
./fec/version/v3/SH1.py										\
./fec/version/v3/F1.py										\
./fec/version/v3/F4.py										\
./fec/version/v3/F7.py										\
./fec/version/v3/SF.py										\
./fec/version/v3/F6.py										\
./fec/version/v3/F56.py										\
./fec/version/v3/SH4.py										\
./fec/version/v3/F3P31.py									\
./fec/version/v3/HRD.py										\
./fec/version/v3/F57.py										\
./fec/version/v3/SH3.py										\
./fec/version/v3/F3PS.py									\
./fec/version/v3/SH2.py										\
./fec/version/v3/TEXT.py									\
./fec/version/v3/SI.py										\
./fec/version/v3/SC2.py										\
./fec/version/v3/__init__.py									\
./fec/version/v3/F24.py										\
./fec/version/v3/F1M.py										\
./fec/version/v3/SC1.py										\
./fec/version/v3/F65.py										\
./fec/version/v3/F99.py										\
./fec/version/v3/F3Z.py										\
./fec/version/v3/F3X.py										\
./fec/version/v3/F76.py										\
./fec/version/v3/SE.py										\
./fec/version/v3/F8.py										\
./fec/version/v3/F3S.py										\
./fec/version/v3/F1S.py										\
./fec/version/v3/F83.py										\
./fec/version/v3/SA.py										\
./fec/version/v3/F3P.py										\
./fec/version/v3/F3.py										\
./fec/version/v3/F5.py										\
./fec/version/v3/SC.py										\
./fec/version/__init__.py									\
./fec/version/v6_2.py										\
./fec/version/v3.py										\
./fec/version/v8_0.py										\
./fec/version/v5_1.py										\
./fec/version/v5_2/F2.py									\
./fec/version/v5_2/SD.py									\
./fec/version/v5_2/SB.py									\
./fec/version/v5_2/F13.py									\
./fec/version/v5_2/F9.py									\
./fec/version/v5_2/F105.py									\
./fec/version/v5_2/F82.py									\
./fec/version/v5_2/F133.py									\
./fec/version/v5_2/SH1.py									\
./fec/version/v5_2/F1.py									\
./fec/version/v5_2/F4.py									\
./fec/version/v5_2/F7.py									\
./fec/version/v5_2/SF.py									\
./fec/version/v5_2/F6.py									\
./fec/version/v5_2/F56.py									\
./fec/version/v5_2/SH4.py									\
./fec/version/v5_2/F3P31.py									\
./fec/version/v5_2/HRD.py									\
./fec/version/v5_2/F57.py									\
./fec/version/v5_2/SH3.py									\
./fec/version/v5_2/F3PS.py									\
./fec/version/v5_2/SH2.py									\
./fec/version/v5_2/TEXT.py									\
./fec/version/v5_2/SI.py									\
./fec/version/v5_2/SC2.py									\
./fec/version/v5_2/__init__.py									\
./fec/version/v5_2/F93.py									\
./fec/version/v5_2/F24.py									\
./fec/version/v5_2/F1M.py									\
./fec/version/v5_2/SC1.py									\
./fec/version/v5_2/F65.py									\
./fec/version/v5_2/SH5.py									\
./fec/version/v5_2/F94.py									\
./fec/version/v5_2/F99.py									\
./fec/version/v5_2/SL.py									\
./fec/version/v5_2/F10.py									\
./fec/version/v5_2/F3Z.py									\
./fec/version/v5_2/F132.py									\
./fec/version/v5_2/F3X.py									\
./fec/version/v5_2/F76.py									\
./fec/version/v5_2/SH6.py									\
./fec/version/v5_2/SE.py									\
./fec/version/v5_2/F8.py									\
./fec/version/v5_2/F3S.py									\
./fec/version/v5_2/F1S.py									\
./fec/version/v5_2/F91.py									\
./fec/version/v5_2/F83.py									\
./fec/version/v5_2/SA.py									\
./fec/version/v5_2/F92.py									\
./fec/version/v5_2/F3P.py									\
./fec/version/v5_2/F3.py									\
./fec/version/v5_2/F5.py									\
./fec/version/v5_2/SC.py									\
./fec/version/v2.py										\
./fec/version/v6_4.py										\
./fec/version/v6_3/F2.py									\
./fec/version/v6_3/SD.py									\
./fec/version/v6_3/SB.py									\
./fec/version/v6_3/F13.py									\
./fec/version/v6_3/F9.py									\
./fec/version/v6_3/F105.py									\
./fec/version/v6_3/F82.py									\
./fec/version/v6_3/F133.py									\
./fec/version/v6_3/SH1.py									\
./fec/version/v6_3/F1.py									\
./fec/version/v6_3/F4.py									\
./fec/version/v6_3/F7.py									\
./fec/version/v6_3/SF.py									\
./fec/version/v6_3/F6.py									\
./fec/version/v6_3/F56.py									\
./fec/version/v6_3/SH4.py									\
./fec/version/v6_3/F3P31.py									\
./fec/version/v6_3/HRD.py									\
./fec/version/v6_3/F57.py									\
./fec/version/v6_3/SH3.py									\
./fec/version/v6_3/F3PS.py									\
./fec/version/v6_3/SH2.py									\
./fec/version/v6_3/TEXT.py									\
./fec/version/v6_3/SI.py									\
./fec/version/v6_3/SC2.py									\
./fec/version/v6_3/__init__.py									\
./fec/version/v6_3/F93.py									\
./fec/version/v6_3/F24.py									\
./fec/version/v6_3/F1M.py									\
./fec/version/v6_3/SC1.py									\
./fec/version/v6_3/F65.py									\
./fec/version/v6_3/SH5.py									\
./fec/version/v6_3/F94.py									\
./fec/version/v6_3/F99.py									\
./fec/version/v6_3/SL.py									\
./fec/version/v6_3/F10.py									\
./fec/version/v6_3/F3Z.py									\
./fec/version/v6_3/F132.py									\
./fec/version/v6_3/F3X.py									\
./fec/version/v6_3/F2S.py									\
./fec/version/v6_3/F76.py									\
./fec/version/v6_3/SH6.py									\
./fec/version/v6_3/SE.py									\
./fec/version/v6_3/F8.py									\
./fec/version/v6_3/F3S.py									\
./fec/version/v6_3/F1S.py									\
./fec/version/v6_3/F91.py									\
./fec/version/v6_3/F83.py									\
./fec/version/v6_3/SA.py									\
./fec/version/v6_3/F92.py									\
./fec/version/v6_3/F3P.py									\
./fec/version/v6_3/F3.py									\
./fec/version/v6_3/F5.py									\
./fec/version/v6_3/SC.py									\
./fec/version/records_base.py									\
./fec/version/v5_2.py										\
./fec/version/v5_0.py										\
./fec/version/v6_3.py										\
./fec/version/v1/F2.py										\
./fec/version/v1/SD.py										\
./fec/version/v1/SB.py										\
./fec/version/v1/F82.py										\
./fec/version/v1/SH1.py										\
./fec/version/v1/F1.py										\
./fec/version/v1/F4.py										\
./fec/version/v1/F7.py										\
./fec/version/v1/SF.py										\
./fec/version/v1/F6.py										\
./fec/version/v1/F56.py										\
./fec/version/v1/SH4.py										\
./fec/version/v1/F3P31.py									\
./fec/version/v1/F57.py										\
./fec/version/v1/SH3.py										\
./fec/version/v1/SH2.py										\
./fec/version/v1/SI.py										\
./fec/version/v1/__init__.py									\
./fec/version/v1/F1M.py										\
./fec/version/v1/SC1.py										\
./fec/version/v1/F65.py										\
./fec/version/v1/F3Z.py										\
./fec/version/v1/F3X.py										\
./fec/version/v1/F76.py										\
./fec/version/v1/SE.py										\
./fec/version/v1/F8.py										\
./fec/version/v1/F83.py										\
./fec/version/v1/SA.py										\
./fec/version/v1/F3P.py										\
./fec/version/v1/F3.py										\
./fec/version/v1/F5.py										\
./fec/version/v1/SC.py										\
./fec/version/v5_1/F2.py									\
./fec/version/v5_1/SD.py									\
./fec/version/v5_1/SB.py									\
./fec/version/v5_1/F9.py									\
./fec/version/v5_1/F105.py									\
./fec/version/v5_1/F82.py									\
./fec/version/v5_1/SH1.py									\
./fec/version/v5_1/F1.py									\
./fec/version/v5_1/F12.py									\
./fec/version/v5_1/F4.py									\
./fec/version/v5_1/F7.py									\
./fec/version/v5_1/SF.py									\
./fec/version/v5_1/F6.py									\
./fec/version/v5_1/F56.py									\
./fec/version/v5_1/SH4.py									\
./fec/version/v5_1/F3P31.py									\
./fec/version/v5_1/HRD.py									\
./fec/version/v5_1/F57.py									\
./fec/version/v5_1/SH3.py									\
./fec/version/v5_1/F3PS.py									\
./fec/version/v5_1/SH2.py									\
./fec/version/v5_1/TEXT.py									\
./fec/version/v5_1/SI.py									\
./fec/version/v5_1/SC2.py									\
./fec/version/v5_1/__init__.py									\
./fec/version/v5_1/F93.py									\
./fec/version/v5_1/F24.py									\
./fec/version/v5_1/F1M.py									\
./fec/version/v5_1/SC1.py									\
./fec/version/v5_1/F65.py									\
./fec/version/v5_1/SH5.py									\
./fec/version/v5_1/F94.py									\
./fec/version/v5_1/F99.py									\
./fec/version/v5_1/SL.py									\
./fec/version/v5_1/F10.py									\
./fec/version/v5_1/F3Z.py									\
./fec/version/v5_1/F3X.py									\
./fec/version/v5_1/F76.py									\
./fec/version/v5_1/SH6.py									\
./fec/version/v5_1/SE.py									\
./fec/version/v5_1/F8.py									\
./fec/version/v5_1/F3S.py									\
./fec/version/v5_1/F1S.py									\
./fec/version/v5_1/F91.py									\
./fec/version/v5_1/F83.py									\
./fec/version/v5_1/SA.py									\
./fec/version/v5_1/F92.py									\
./fec/version/v5_1/F3P.py									\
./fec/version/v5_1/F3.py									\
./fec/version/v5_1/F11.py									\
./fec/version/v5_1/F5.py									\
./fec/version/v5_1/SC.py									\
./fec/version/v6_4/F2.py									\
./fec/version/v6_4/SD.py									\
./fec/version/v6_4/SB.py									\
./fec/version/v6_4/F13.py									\
./fec/version/v6_4/F9.py									\
./fec/version/v6_4/F82.py									\
./fec/version/v6_4/F133.py									\
./fec/version/v6_4/SH1.py									\
./fec/version/v6_4/F1.py									\
./fec/version/v6_4/F4.py									\
./fec/version/v6_4/F7.py									\
./fec/version/v6_4/SF.py									\
./fec/version/v6_4/F6.py									\
./fec/version/v6_4/F56.py									\
./fec/version/v6_4/SH4.py									\
./fec/version/v6_4/F3P31.py									\
./fec/version/v6_4/HRD.py									\
./fec/version/v6_4/F57.py									\
./fec/version/v6_4/SH3.py									\
./fec/version/v6_4/SH2.py									\
./fec/version/v6_4/TEXT.py									\
./fec/version/v6_4/SI.py									\
./fec/version/v6_4/SC2.py									\
./fec/version/v6_4/__init__.py									\
./fec/version/v6_4/F93.py									\
./fec/version/v6_4/F24.py									\
./fec/version/v6_4/F1M.py									\
./fec/version/v6_4/F3L.py									\
./fec/version/v6_4/SC1.py									\
./fec/version/v6_4/F65.py									\
./fec/version/v6_4/SH5.py									\
./fec/version/v6_4/F94.py									\
./fec/version/v6_4/F99.py									\
./fec/version/v6_4/SL.py									\
./fec/version/v6_4/F3Z.py									\
./fec/version/v6_4/F132.py									\
./fec/version/v6_4/F3X.py									\
./fec/version/v6_4/F2S.py									\
./fec/version/v6_4/F76.py									\
./fec/version/v6_4/SH6.py									\
./fec/version/v6_4/SE.py									\
./fec/version/v6_4/F8.py									\
./fec/version/v6_4/F3S.py									\
./fec/version/v6_4/F1S.py									\
./fec/version/v6_4/F91.py									\
./fec/version/v6_4/F83.py									\
./fec/version/v6_4/SA.py									\
./fec/version/v6_4/F92.py									\
./fec/version/v6_4/F3P.py									\
./fec/version/v6_4/F3.py									\
./fec/version/v6_4/F5.py									\
./fec/version/v6_4/SC.py									\
./fec/__init__.py


all:
	python e_filing_headers_all_versions.py
