class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['Net Contributions', '3', '14', ''],
            ['Net Expenditures', '4', '15', ''],
            ['Federal Funds', '5', '16', ''],
            ['Individuals', '6', '17', 'a'],
            ['Political Party Committees', '7', '17', 'b'],
            ['Other Political Committees (PACs)', '8', '17', 'c'],
            ['The Candidate', '9', '17', 'd'],
            ['Total contributions (Other than Loans)', '10', '17', 'e'],
            ['Transfers From Aff/Other Party Committees', '11', '18', ''],
            ['Received from or Guaranteed by Candidate', '12', '19', 'a'],
            ['Other Loans', '13', '19', 'b'],
            ['Total Loans', '14', '19', 'c'],
            ['Operating', '15', '20', 'a'],
            ['Fundraising', '16', '20', 'b'],
            ['Legal and Accounting', '17', '20', 'c'],
            ['Total Offsets to Operating Expenditures', '18', '20', 'd'],
            ['Other Receipts', '19', '21', ''],
            ['Total Receipts', '20', '22', ''],
            ['Operating Expenditures', '21', '23', ''],
            ['Transfers to Other Authorized Committees', '22', '24', ''],
            ['Fundraising Disbursements', '23', '25', ''],
            ['Exempt Legal and Accounting Disbursements', '24', '26', ''],
            ['Made or Guaranteed by the Candidate', '25', '27', 'a'],
            ['Other Repayments', '26', '27', 'b'],
            ['Total Loan Repayments Made', '27', '27', 'c'],
            ['Individuals', '28', '28', 'a'],
            ['Political Party Committees', '29', '28', 'b'],
            ['Other Political Committees', '30', '28', 'c'],
            ['Total Contributions Refunds', '31', '28', 'd'],
            ['Other Disbursements', '32', '29', ''],
            ['Total Disbursements', '33', '30', ''],
            ['ALABAMA', '34', '', ''],
            ['ALASKA', '35', '', ''],
            ['ARIZONA', '36', '', ''],
            ['ARKANSAS', '37', '', ''],
            ['CALIFORNIA', '38', '', ''],
            ['COLORADO', '39', '', ''],
            ['CONNECTICUT', '40', '', ''],
            ['DELAWARE', '41', '', ''],
            ['DIST OF COLUMBIA', '42', '', ''],
            ['FLORIDA', '43', '', ''],
            ['GEORGIA', '44', '', ''],
            ['HAWAII', '45', '', ''],
            ['IDAHO', '46', '', ''],
            ['ILLINOIS', '47', '', ''],
            ['INDIANA', '48', '', ''],
            ['IOWA', '49', '', ''],
            ['KANSAS', '50', '', ''],
            ['KENTUCKY', '51', '', ''],
            ['LOUISIANA', '52', '', ''],
            ['MAINE', '53', '', ''],
            ['MARYLAND', '54', '', ''],
            ['MASSACHUSETTS', '55', '', ''],
            ['MICHIGAN', '56', '', ''],
            ['MINNESOTA', '57', '', ''],
            ['MISSISSIPPI', '58', '', ''],
            ['MISSOURI', '59', '', ''],
            ['MONTANA', '60', '', ''],
            ['NEBRASKA', '61', '', ''],
            ['NEVADA', '62', '', ''],
            ['NEW HAMPSHIRE', '63', '', ''],
            ['NEW JERSEY', '64', '', ''],
            ['NEW MEXICO', '65', '', ''],
            ['NEW YORK', '66', '', ''],
            ['NORTH CAROLINA', '67', '', ''],
            ['NORTH DAKOTA', '68', '', ''],
            ['OHIO', '69', '', ''],
            ['OKLAHOMA', '70', '', ''],
            ['OREGON', '71', '', ''],
            ['PENNSYLVANIA', '72', '', ''],
            ['RHODE ISLAND', '73', '', ''],
            ['SOUTH CAROLINA', '74', '', ''],
            ['SOUTH DAKOTA', '75', '', ''],
            ['TENNESSEE', '76', '', ''],
            ['TEXAS', '77', '', ''],
            ['UTAH', '78', '', ''],
            ['VERMONT', '79', '', ''],
            ['VIRGINIA', '80', '', ''],
            ['WASHINGTON', '81', '', ''],
            ['WEST VIRGINIA', '82', '', ''],
            ['WISCONSIN', '83', '', ''],
            ['WYOMING', '84', '', ''],
            ['PUERTO RICO', '85', '', ''],
            ['GUAM', '86', '', ''],
            ['VIRGIN ISLANDS', '87', '', ''],
            ['TOTALS', '88', '', ''],
            ['Date - General Election', '89', '', ''],
            ['Date - Day after General Election', '90', '', ''],
    ]
