class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['NAME (Payee)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['TRANS Purpose DESCRIP', '10', '', ''],
            ['Of Expenditure', '11-', '', ''],
            ['AMOUNT', '12', '', ''],
            ['SUPPORT/OPPOSE', '13', '', ''],
            ['S/O FEC CAN ID NUMBER', '14', '', ''],
            ['S/O CAN/NAME', '15', '', ''],
            ['S/O CAN/OFFICE', '16', '', ''],
            ['S/O CAN/STATE', '17', '', ''],
            ['S/O CAN/DIST', '18', '', ''],
            ['FEC COMMITTEE ID NUMBER', '19', '', ''],
            ['Unused field', '20', '', ''],
            ['Unused field', '21', '', ''],
            ['Unused field', '22', '', ''],
            ['Unused field', '23', '', ''],
            ['Unused field', '24', '', ''],
            ['CONDUIT NAME', '25', '', ''],
            ['CONDUIT STREET 1', '26', '', ''],
            ['CONDUIT STREET 2', '27', '', ''],
            ['CONDUIT CITY', '28', '', ''],
            ['CONDUIT STATE', '29', '', ''],
            ['CONDUIT ZIP', '30', '', ''],
            ['AMENDED CD', '31', '', ''],
            ['TRAN ID', '32', '', ''],
            ['CATEGORY CODE', '33', '', ''],
            ['TRANS Purpose CODE', '34', '', ''],
            ['Calendar YTD for election/office sought', '35', '', ''],
    ]
