class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['CASH ON HAND', '9', '1', ''],
            ['as of', '10', '1', 'a'],
            ['Total assets to be liquidated', '11', '2', ''],
            ['Total (assets)', '12', '3', ''],
            ['Year to date receipts', '13', '4', ''],
            ['Year to date disbursements', '14', '5', ''],
            ['Total amount of debts owed by cmte', '15', '6', ''],
            ['Total number of creditors owed', '16', '7', ''],
            ['Number of creditors in part II of this plan', '17', '8', ''],
            ['Total amount of debts owed to creditors in part II of plan', '18', '9', ''],
            ['Total amount to be paid to creditors', '19', '10', ''],
            ['Is the cmte terminating activities', '20-11. ', '', ''],
            ['PLANNED FOR TERMINATION RPT', '21-11. Y ', '', ''],
            ['If this is an auth cmtte are there other auth cmtte.', '22-12. ', '', ''],
            ['Y IF YES list AUTH CMTE ID/NAMES', '23-12. Y ', '', ''],
            ['sufficient funds to pay total amount indicated in this plan', '24-13. ', '', ''],
            ['N If NO what steps will be taken to obtain the funds', '25-13. N ', '', ''],
            ['Has the committee filed previous debt settlement plans', '26-14. ', '', ''],
            ['After disposing ... will there be any residual funds?', '27-15. ', '', ''],
            ['IF YES how will the funds be disbursed', '28-15. Y ', '', ''],
            ['PART III YESNO (Does cmtte have sufficient funds to pay the remaining', '29', '', ''],
            ['N If no, what steps will be taken to obtain the funds.', '30-PART III ', '', ''],
            ['NAME/TREASURER (as signed)', '31', '', ''],
            ['Signed', '32-', '', ''],
    ]
