class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['IND/ORG/CORP NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['CHG OF ADDRESS', '9', '', ''],
            ['EMPLOYER', '10', '', ''],
            ['OCCUPATION', '11', '', ''],
            ['BEGINNING COVERAGE DATE', '12', '', ''],
            ['ENDING COVERAGE DATE', '13', '', ''],
            ['DATE OF PUBLIC DISTRIBUTION', '14', '', ''],
            ['COMMUNICATION TITLE', '15', '', ''],
            ['QUALIFIED NON-PROFIT', '16', '', ''],
            ['SEGREGATED BANK ACCOUNT', '17', '', ''],
            ['Custodian', '18-', '', ''],
            ['STREET 1', '19', '', ''],
            ['STREET 2', '20', '', ''],
            ['CITY', '21', '', ''],
            ['STATE', '22', '', ''],
            ['ZIP', '23', '', ''],
            ['EMPLOYER', '24', '', ''],
            ['OCCUPATION', '25', '', ''],
            ['TOTAL DONATIONS THIS STATEMENT', '26', '9', ''],
            ['TOTAL DISB./OBLIG. THIS STATEMENT', '27', '10', ''],
            ['NAME PERSON COMPLETING REPORT', '28', '', ''],
            ['Signed', '29-', '', ''],
    ]
