from fec.version.records_base import RecordsBase
class Records(RecordsBase):
    def __init__(self):
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER FEC CMTE ID', 'number': '2'},
            {'name': 'ENTITY TYPE', 'number': '3'},
            {'name': 'CONTRIBUTOR NAME', 'number': '4'},
            {'name': 'STREET 1', 'number': '5'},
            {'name': 'STREET 2', 'number': '6'},
            {'name': 'CITY', 'number': '7'},
            {'name': 'STATE', 'number': '8'},
            {'name': 'ZIP', 'number': '9'},
            {'name': 'ITEM ELECT CD', 'number': '10'},
            {'name': 'ITEM ELECT OTHER', 'number': '11'},
            {'name': 'INDEMP', 'number': '12'},
            {'name': 'INDOCC', 'number': '13'},
            {'name': 'AGGREGATE AMT Y-T-D', 'number': '14'},
            {'name': 'DATE RECEIVED', 'number': '15'},
            {'name': 'AMOUNT RECEIVED', 'number': '16'},
            {'name': 'TRANS CODE', 'number': '17'},
            {'name': 'TRANS DESCRIP', 'number': '18'},
            {'name': 'FEC COMMITTEE ID NUMBER', 'number': '19'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '20'},
            {'name': 'CANDIDATE NAME', 'number': '21'},
            {'name': 'CAN/OFFICE', 'number': '22'},
            {'name': 'CAN/STATE', 'number': '23'},
            {'name': 'CAN/DIST', 'number': '24'},
            {'name': 'CONDUIT NAME', 'number': '25'},
            {'name': 'CONDUIT STREET1', 'number': '26'},
            {'name': 'CONDUIT STREET2', 'number': '27'},
            {'name': 'CONDUIT CITY', 'number': '28'},
            {'name': 'CONDUIT STATE', 'number': '29'},
            {'name': 'CONDUIT ZIP', 'number': '30'},
            {'name': 'MEMO CODE', 'number': '31'},
            {'name': 'MEMO TEXT', 'number': '32'},
            {'name': 'AMENDED CD', 'number': '33'},
            {'name': 'TRAN ID', 'number': '34'},
            {'name': 'BACK REF TRAN ID', 'number': '35'},
            {'name': 'BACK REF SCHED NAME', 'number': '36'},
            {'name': 'Reference to SI or SL system code that identifies the Account', 'number': '37'},
            {'name': 'INCREASED LIMIT', 'number': '38'},
    ]
