class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['NAME (Payee)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['TRANS Purpose DESCRIP', '10', '', ''],
            ['DATE', '11', '', ''],
            ['AMOUNT EXPENDED', '12', '', ''],
            ['SUPPORT/OPPOSE', '13', '', ''],
            ['S/O FEC CAN ID NUMBER', '14', '', ''],
            ['S/O CAN/NAME', '15', '', ''],
            ['S/O CAN/OFFICE', '16', '', ''],
            ['S/O STATE', '17', '', ''],
            ['S/O CAN/DIST', '18', '', ''],
            ['FEC COMMITTEE ID NUMBER', '19', '', ''],
            ['Unused field', '20', '', ''],
            ['Unused field', '21', '', ''],
            ['Unused field', '22', '', ''],
            ['Unused field', '23', '', ''],
            ['Unused field', '24', '', ''],
            ['CONDUIT NAME', '25', '', ''],
            ['CONDUIT STREET 1', '26', '', ''],
            ['CONDUIT STREET 2', '27', '', ''],
            ['CONDUIT CITY', '28', '', ''],
            ['CONDUIT STATE', '29', '', ''],
            ['CONDUIT ZIP', '30', '', ''],
            ['as signed', '31-', '', ''],
            ['Signed', '32-', '', ''],
            ['Notarized', '33-', '', ''],
            ['Notary Commission Expires', '34-', '', ''],
            ['Notary', '35-', '', ''],
            ['AMENDED CD', '36', '', ''],
            ['TRAN ID', '37', '', ''],
            ['MEMO CODE', '38', '', ''],
            ['MEMO TEXT', '39', '', ''],
            ['BACK REF TRAN ID', '40', '', ''],
            ['BACK REF SCHED NAME', '41', '', ''],
            ['ITEM ELECT CD', '42', '', ''],
            ['ITEM ELECT OTHER', '43', '', ''],
            ['CATEGORY CODE', '44', '', ''],
            ['TRANS CODE', '45', '', ''],
            ['CALENDAR YTD - OFFICE SOUGHT', '46', '', ''],
    ]
