class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['NAME OF ACCOUNT', '3', '', ''],
            ['System code for account named in Field #3', '4', '', ''],
            ['Coverage From', '5-', '', ''],
            ['Coverage To', '6-', '', ''],
            ['Itemized Receipts From Persons', '7', '1', ''],
            ['Unitemized Receipts From Persons', '8', '1', ''],
            ['Total Receipts From Persons', '9', '1', ''],
            ['Other Receipts', '10', '2', ''],
            ['Total Receipts', '11', '3', ''],
            ['Voter Registration DISBURSEMENTS', '12', '4', 'a'],
            ['Voter ID DISBURSEMENTS', '13', '4', 'b'],
            ['GOTV DISBURSEMENTS', '14', '4', 'c'],
            ['Generic Campaign DISBURSEMENTS', '15', '4', 'd'],
            ['Line 4 Total', '16', '4', 'e'],
            ['Other Disbursements', '17', '5', ''],
            ['Total Disbursements', '18', '6', ''],
            ['Cash on Hand beginning', '19', '7', ''],
            ['Receipts', '20', '8', ''],
            ['Subtotal', '21', '9', ''],
            ['Disbursements', '22', '10', ''],
            ['Itemized Receipts From Persons', '23', '1', ''],
            ['Unitemized Receipts From Persons', '24', '1', ''],
            ['Total Receipts From Persons', '25', '1', ''],
            ['Other Receipts', '26', '2', ''],
            ['Total Receipts', '27', '3', ''],
            ['Voter Registration DISBURSEMENTS', '28', '4', 'a'],
            ['Voter ID DISBURSEMENTS', '29', '4', 'b'],
            ['GOTV DISBURSEMENTS', '30', '4', 'c'],
            ['Generic Campaign DISBURSEMENTS', '31', '4', 'd'],
            ['Line 4 Total', '32', '4', 'e'],
            ['Other Disbursements', '33', '5', ''],
            ['Total Disbursements', '34', '6', ''],
            ['Cash on Hand Jan 1, 19', '35', '7', ''],
            ['Receipts', '36', '8', ''],
            ['Subtotal', '37', '9', ''],
            ['Disbursements', '38', '10', ''],
            ['ENDING CASH ON HAND', '39', '11', ''],
            ['AMENDED CODE', '40', '', ''],
            ['TRAN ID', '41', '', ''],
    ]
