import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER FEC CMTE ID', 'number': '2'},
            {'name': 'COMMITTEE NAME', 'number': '3'},
            {'name': 'STREET 1', 'number': '4'},
            {'name': 'STREET 2', 'number': '5'},
            {'name': 'CITY', 'number': '6'},
            {'name': 'STATE', 'number': '7'},
            {'name': 'ZIP', 'number': '8'},
            {'name': 'Submitted', 'number': '9-'},
            {'name': 'CHG OF COMMITTEE NAME', 'number': '10'},
            {'name': 'CHG OF ADDRESS', 'number': '11'},
            {'name': 'COMMITTEE TYPE', 'number': '12-5.'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '13-5.'},
            {'name': 'CANDIDATE NAME', 'number': '14-5.'},
            {'name': 'CAN/OFFICE', 'number': '15-5.'},
            {'name': 'CAN/STATE', 'number': '16-5.'},
            {'name': 'CAN/DIST', 'number': '17-5.'},
            {'name': 'PARTY CODE', 'number': '18-5.'},
            {'name': 'PARTY TYPE', 'number': '19-5.'},
            {'name': 'FEC COMMITTEE ID NUMBER', 'number': '20-6.'},
            {'name': 'COMMITTEE NAME (Affiliated)', 'number': '21-6.'},
            {'name': 'STREET 1', 'number': '22-6.'},
            {'name': 'STREET 2', 'number': '23-6.'},
            {'name': 'CITY', 'number': '24-6.'},
            {'name': 'STATE', 'number': '25-6.'},
            {'name': 'ZIP', 'number': '26-6.'},
            {'name': 'RELATIONSHIP (w/ Above Cmte)', 'number': '27-6.'},
            {'name': 'ORGANIZATION TYPE', 'number': '28-6.'},
            {'name': 'Custodian Name', 'number': '29-7. '},
            {'name': 'STREET 1', 'number': '30-7.'},
            {'name': 'STREET 2', 'number': '31-7.'},
            {'name': 'CITY', 'number': '32-7.'},
            {'name': 'STATE', 'number': '33-7.'},
            {'name': 'ZIP', 'number': '34-7.'},
            {'name': 'TITLE', 'number': '35-7.'},
            {'name': 'TELEPHONE', 'number': '36-7.'},
            {'name': 'Treasurer', 'number': '37-8. '},
            {'name': 'STREET 1', 'number': '38-8.'},
            {'name': 'STREET 2', 'number': '39-8.'},
            {'name': 'CITY', 'number': '40-8.'},
            {'name': 'STATE', 'number': '41-8.'},
            {'name': 'ZIP', 'number': '42-8.'},
            {'name': 'TITLE', 'number': '43-8.'},
            {'name': 'TELEPHONE', 'number': '44-8.'},
            {'name': 'Designated Agent', 'number': '45-8. '},
            {'name': 'STREET 1', 'number': '46-8.'},
            {'name': 'STREET 2', 'number': '47-8.'},
            {'name': 'CITY', 'number': '48-8.'},
            {'name': 'STATE', 'number': '49-8.'},
            {'name': 'ZIP', 'number': '50-8.'},
            {'name': 'TITLE', 'number': '51-8.'},
            {'name': 'TELEPHONE', 'number': '52-8.'},
            {'name': 'Bank/Depository', 'number': '53-9. '},
            {'name': 'STREET 1', 'number': '54-9.'},
            {'name': 'STREET 2', 'number': '55-9.'},
            {'name': 'CITY', 'number': '56-9.'},
            {'name': 'STATE', 'number': '57-9.'},
            {'name': 'ZIP', 'number': '58-9.'},
            {'name': 'NAME/TREASURER (as signed)', 'number': '59'},
            {'name': 'Signed', 'number': '60-'},
            {'name': 'COMMITTEE EMAIL', 'number': '61'},
            {'name': 'COMMITTEE WEB URL', 'number': '62'},
    ]
        self.fields_names = self.hash_names(self.fields)
