class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['NAME (Contributor/Lender)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['RPTPGI', '10', '', ''],
            ['INDEMP', '11', '', ''],
            ['INDOCC', '12', '', ''],
            ['Of Contribution', '13-', '', ''],
            ['FAIR MARKET VALUE OF ITEM', '14', '', ''],
            ['TRANSACTION CODE', '15', '', ''],
            ['TRANSDESC', '16', '', ''],
            ['FEC COMMITTEE ID NUMBER', '17', '', ''],
            ['FEC CANDIDATE ID NUMBER', '18', '', ''],
            ['CANDIDATE NAME', '19', '', ''],
            ['CAN/OFFICE', '20', '', ''],
            ['CAN/STATE', '21', '', ''],
            ['CAN/DIST', '22', '', ''],
            ['CONDUIT NAME', '23', '', ''],
            ['CONDUIT STREET 1', '24', '', ''],
            ['CONDUIT STREET 2', '25', '', ''],
            ['CONDUIT CITY', '26', '', ''],
            ['CONDUIT STATE', '27', '', ''],
            ['CONDUIT ZIP', '28', '', ''],
            ['MEMO CODE', '29', '', ''],
            ['MEMO TEXT', '30', '', ''],
            ['AMENDED CD', '31', '', ''],
            ['TRAN ID', '32', '', ''],
    ]
