from fec.version.records_base import RecordsBase
class Records(RecordsBase):
    def __init__(self):
        RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER FEC CMTE ID', 'number': '2'},
            {'name': 'COMMITTEE NAME', 'number': '3'},
            {'name': 'STREET 1', 'number': '4'},
            {'name': 'STREET 2', 'number': '5'},
            {'name': 'CITY', 'number': '6'},
            {'name': 'STATE', 'number': '7'},
            {'name': 'ZIP', 'number': '8'},
            {'name': 'CHG OF ADDRESS', 'number': '9'},
            {'name': 'QUALIFIED CMTE', 'number': '10'},
            {'name': 'RPTCODE', 'number': '11'},
            {'name': 'RPTPGI', 'number': '12'},
            {'name': 'Of Election', 'number': '13-'},
            {'name': 'STATE (Of Election)', 'number': '14'},
            {'name': 'Coverage From', 'number': '15-'},
            {'name': 'Coverage To', 'number': '16-'},
            {'name': 'Cash on Hand beginning', 'number': '17-6(b)'},
            {'name': 'Total Receipts', 'number': '18-6(c)'},
            {'name': 'Subtotal', 'number': '19-6(d)'},
            {'name': 'Total Disbursements', 'number': '20-7.'},
            {'name': 'Cash on Hand at Close', 'number': '21-8.'},
            {'name': 'Debts to', 'number': '22-9.'},
            {'name': 'Debts by', 'number': '23-10.'},
            {'name': 'Itemized', 'number': '24-11(a)i'},
            {'name': 'Unitemized', 'number': '25-11(a)ii'},
            {'name': 'Total', 'number': '26-11(a)iii'},
            {'name': 'Political Party Committees', 'number': '27-11(b)'},
            {'name': 'Other Political Committees (PACs)', 'number': '28-11(c)'},
            {'name': 'Total Contributions', 'number': '29-11(d)'},
            {'name': 'Transfers from Affiliated/Other Party Committees', 'number': '30-12.'},
            {'name': 'All Loans Received', 'number': '31-13.'},
            {'name': 'Loan Repayments Received', 'number': '32-14.'},
            {'name': 'Offsets to Operating Expenditures (refunds ...)', 'number': '33-15.'},
            {'name': 'Refunds of Federal Contributions', 'number': '34-16.'},
            {'name': 'Other Federal Receipts (dividends)', 'number': '35-17.'},
            {'name': 'Transfers from Nonfederal Account', 'number': '36-18.'},
            {'name': 'Total Receipts', 'number': '37-19.'},
            {'name': 'Total Federal Receipts', 'number': '38-20.'},
            {'name': 'Federal Share', 'number': '39-21(a)i'},
            {'name': 'Non-Federal Share', 'number': '40-21(a)ii'},
            {'name': 'Other Federal Operating Expenditures', 'number': '41-21(b)'},
            {'name': 'Total Operating Expenditures', 'number': '42-21(c)'},
            {'name': 'Transfers to Affiliated/Other Party Committees', 'number': '43-22.'},
            {'name': 'Contributions to Federal Candidates/Committees', 'number': '44-23.'},
            {'name': 'Independent Expenditures', 'number': '45-24.'},
            {'name': 'Coordinated Expenditures made by Party Committees', 'number': '46-25.'},
            {'name': 'Loan Repayments', 'number': '47-26.'},
            {'name': 'Loans Made', 'number': '48-27.'},
            {'name': 'Individuals/Persons', 'number': '49-28(a)'},
            {'name': 'Political Party Committees', 'number': '50-28(b)'},
            {'name': 'Other Political Committees', 'number': '51-28(c)'},
            {'name': 'Total Contributions Refunds', 'number': '52-28(d)'},
            {'name': 'Other Disbursements', 'number': '53-29.'},
            {'name': 'Total Disbursements', 'number': '54-30.'},
            {'name': 'Total Federal Disbursements', 'number': '55-31.'},
            {'name': 'Total Contributions', 'number': '56-32.'},
            {'name': 'Total Contribution Refunds', 'number': '57-33.'},
            {'name': 'Net Contributions', 'number': '58-34.'},
            {'name': 'Total Federal Operating Expenditures', 'number': '59-35.'},
            {'name': 'Offsets to Operating Expenditures', 'number': '60-36.'},
            {'name': 'Net Operating Expenditures', 'number': '61-37.'},
            {'name': 'Cash on Hand Jan 1, 19', 'number': '62-6(a)'},
            {'name': 'Year for Above', 'number': '63'},
            {'name': 'Total Receipts', 'number': '64-6(c)'},
            {'name': 'Subtotal', 'number': '65-6(d)'},
            {'name': 'Total disbursements', 'number': '66-7.'},
            {'name': 'Cash on Hand Close', 'number': '67-8.'},
            {'name': 'Itemized', 'number': '68-11(a)i'},
            {'name': 'Unitemized', 'number': '69-11(a)ii'},
            {'name': 'Total', 'number': '70-11(a)iii'},
            {'name': 'Political Party committees', 'number': '71-11(b)'},
            {'name': 'Other Political Committees (PACs)', 'number': '72-11(c)'},
            {'name': 'Total Contributions', 'number': '73-11(d)'},
            {'name': 'Transfers from Affiliated/Other Party Committees', 'number': '74-12.'},
            {'name': 'All Loans Received', 'number': '75-13.'},
            {'name': 'Loan Repayments Received', 'number': '76-14.'},
            {'name': 'Offsets to Operating Expenditures (refunds)', 'number': '77-15.'},
            {'name': 'Refunds of Federal Contributions', 'number': '78-16.'},
            {'name': 'Other Federal Receipts (dividends)', 'number': '79-17.'},
            {'name': 'Transfers from Nonfederal Account', 'number': '80-18.'},
            {'name': 'Total Receipts', 'number': '81-19.'},
            {'name': 'Total Federal Receipts', 'number': '82-20.'},
            {'name': 'Federal Share', 'number': '83-21(a)i'},
            {'name': 'Non-Federal Share', 'number': '84-21(a)ii'},
            {'name': 'Other Federal Operating Expenditures', 'number': '85-21(b)'},
            {'name': 'Total operating Expenditures', 'number': '86-21(c)'},
            {'name': 'Transfers to Affiliated/Other Party Committees', 'number': '87-22.'},
            {'name': 'Contributions to Federal Candidates/Committees', 'number': '88-23.'},
            {'name': 'Independent Expenditures', 'number': '89-24.'},
            {'name': 'Coordinated Expenditures made by Party Committees', 'number': '90-25.'},
            {'name': 'Loan Repayments Made', 'number': '91-26.'},
            {'name': 'Loans Made', 'number': '92-27.'},
            {'name': 'Individuals/Persons', 'number': '93-28(a)'},
            {'name': 'Political Party Committees', 'number': '94-28(b)'},
            {'name': 'Other Political Committees', 'number': '95-28(c)'},
            {'name': 'Total contributions Refunds', 'number': '96-28(d)'},
            {'name': 'Other Disbursements', 'number': '97-29.'},
            {'name': 'Total Disbursements', 'number': '98-30.'},
            {'name': 'Total Federal Disbursements', 'number': '99-31.'},
            {'name': 'Total Contributions', 'number': '100-32.'},
            {'name': 'Total Contribution Refunds', 'number': '101-33.'},
            {'name': 'Net contributions', 'number': '102-34.'},
            {'name': 'Total Federal Operating Expenditures', 'number': '103-35.'},
            {'name': 'Offsets to Operating Expenditures', 'number': '104-36.'},
            {'name': 'Net Operating Expenditures', 'number': '105-37.'},
            {'name': 'NAME/TREASURER (as signed)', 'number': '106'},
            {'name': 'Signed', 'number': '107-'},
    ]
        self.fields_names = self.hash_names(self.fields)
