class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['CHG OF ADDRESS', '9', '', ''],
            ['QUALIFIED CMTE', '10', '', ''],
            ['RPTCODE', '11', '', ''],
            ['RPTPGI', '12', '', ''],
            ['Of Election', '13-', '', ''],
            ['STATE (Of Election)', '14', '', ''],
            ['Coverage From', '15-', '', ''],
            ['Coverage To', '16-', '', ''],
            ['Cash on Hand beginning', '17', '6', 'b'],
            ['Total Receipts', '18', '6', 'c'],
            ['Subtotal', '19', '6', 'd'],
            ['Total Disbursements', '20', '7', ''],
            ['Cash on Hand at Close', '21', '8', ''],
            ['Debts to', '22', '9', ''],
            ['Debts by', '23', '10', ''],
            ['Itemized', '24', '11', '(a)i'],
            ['Unitemized', '25', '11', '(a)ii'],
            ['Total', '26', '11', '(a)iii'],
            ['Political Party Committees', '27', '11', 'b'],
            ['Other Political Committees (PACs)', '28', '11', 'c'],
            ['Total Contributions', '29', '11', 'd'],
            ['Transfers from Affiliated/Other Party Committees', '30', '12', ''],
            ['All Loans Received', '31', '13', ''],
            ['Loan Repayments Received', '32', '14', ''],
            ['Offsets to Operating Expenditures (refunds ...)', '33', '15', ''],
            ['Refunds of Federal Contributions', '34', '16', ''],
            ['Other Federal Receipts (dividends)', '35', '17', ''],
            ['Transfers from Nonfederal Account', '36', '18', ''],
            ['Total Receipts', '37', '19', ''],
            ['Total Federal Receipts', '38', '20', ''],
            ['Federal Share', '39', '21', '(a)i'],
            ['Non-Federal Share', '40', '21', '(a)ii'],
            ['Other Federal Operating Expenditures', '41', '21', 'b'],
            ['Total Operating Expenditures', '42', '21', 'c'],
            ['Transfers to Affiliated/Other Party Committees', '43', '22', ''],
            ['Contributions to Federal Candidates/Committees', '44', '23', ''],
            ['Independent Expenditures', '45', '24', ''],
            ['Coordinated Expenditures made by Party Committees', '46', '25', ''],
            ['Loan Repayments', '47', '26', ''],
            ['Loans Made', '48', '27', ''],
            ['Individuals/Persons', '49', '28', 'a'],
            ['Political Party Committees', '50', '28', 'b'],
            ['Other Political Committees', '51', '28', 'c'],
            ['Total Contributions Refunds', '52', '28', 'd'],
            ['Other Disbursements', '53', '29', ''],
            ['Total Disbursements', '54', '30', ''],
            ['Total Federal Disbursements', '55', '31', ''],
            ['Total Contributions', '56', '32', ''],
            ['Total Contribution Refunds', '57', '33', ''],
            ['Net Contributions', '58', '34', ''],
            ['Total Federal Operating Expenditures', '59', '35', ''],
            ['Offsets to Operating Expenditures', '60', '36', ''],
            ['Net Operating Expenditures', '61', '37', ''],
            ['Cash on Hand Jan 1, 19', '62', '6', 'a'],
            ['Year for Above', '63', '', ''],
            ['Total Receipts', '64', '6', 'c'],
            ['Subtotal', '65', '6', 'd'],
            ['Total disbursements', '66', '7', ''],
            ['Cash on Hand Close', '67', '8', ''],
            ['Itemized', '68', '11', '(a)i'],
            ['Unitemized', '69', '11', '(a)ii'],
            ['Total', '70', '11', '(a)iii'],
            ['Political Party committees', '71', '11', 'b'],
            ['Other Political Committees (PACs)', '72', '11', 'c'],
            ['Total Contributions', '73', '11', 'd'],
            ['Transfers from Affiliated/Other Party Committees', '74', '12', ''],
            ['All Loans Received', '75', '13', ''],
            ['Loan Repayments Received', '76', '14', ''],
            ['Offsets to Operating Expenditures (refunds)', '77', '15', ''],
            ['Refunds of Federal Contributions', '78', '16', ''],
            ['Other Federal Receipts (dividends)', '79', '17', ''],
            ['Transfers from Nonfederal Account', '80', '18', ''],
            ['Total Receipts', '81', '19', ''],
            ['Total Federal Receipts', '82', '20', ''],
            ['Federal Share', '83', '21', '(a)i'],
            ['Non-Federal Share', '84', '21', '(a)ii'],
            ['Other Federal Operating Expenditures', '85', '21', 'b'],
            ['Total operating Expenditures', '86', '21', 'c'],
            ['Transfers to Affiliated/Other Party Committees', '87', '22', ''],
            ['Contributions to Federal Candidates/Committees', '88', '23', ''],
            ['Independent Expenditures', '89', '24', ''],
            ['Coordinated Expenditures made by Party Committees', '90', '25', ''],
            ['Loan Repayments Made', '91', '26', ''],
            ['Loans Made', '92', '27', ''],
            ['Individuals/Persons', '93', '28', 'a'],
            ['Political Party Committees', '94', '28', 'b'],
            ['Other Political Committees', '95', '28', 'c'],
            ['Total contributions Refunds', '96', '28', 'd'],
            ['Other Disbursements', '97', '29', ''],
            ['Total Disbursements', '98', '30', ''],
            ['Total Federal Disbursements', '99', '31', ''],
            ['Total Contributions', '100', '32', ''],
            ['Total Contribution Refunds', '101', '33', ''],
            ['Net contributions', '102', '34', ''],
            ['Total Federal Operating Expenditures', '103', '35', ''],
            ['Offsets to Operating Expenditures', '104', '36', ''],
            ['Net Operating Expenditures', '105', '37', ''],
            ['NAME/TREASURER (as signed)', '106', '', ''],
            ['Signed', '107-', '', ''],
    ]
