from fec.version.records_base import RecordsBase
class Records(RecordsBase):
    def __init__(self):
        RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER FEC CMTE ID', 'number': '2'},
            {'name': 'COMMITTEE NAME', 'number': '3'},
            {'name': 'STREET 1', 'number': '4'},
            {'name': 'STREET 2', 'number': '5'},
            {'name': 'CITY', 'number': '6'},
            {'name': 'STATE', 'number': '7'},
            {'name': 'ZIP', 'number': '8'},
            {'name': 'COMMITTEE/ORG TYPE', 'number': '9'},
            {'name': 'DESC', 'number': '10'},
            {'name': 'RPTCODE', 'number': '11'},
            {'name': 'Coverage From', 'number': '12-'},
            {'name': 'Coverage To', 'number': '13-'},
            {'name': 'cash on hand beg. report per.', 'number': '14-6.(b)'},
            {'name': 'Total receipts', 'number': '15-6.(c)'},
            {'name': 'Subtotal', 'number': '16-6.(d)'},
            {'name': 'Total disbursements', 'number': '17-7.'},
            {'name': 'COH CLOSE', 'number': '18-8.'},
            {'name': 'Debts to', 'number': '19-9.'},
            {'name': 'Debts by', 'number': '20-10.'},
            {'name': 'Convention expenditures', 'number': '21-11.'},
            {'name': 'refunds/rebates/returns relating to conv exp.', 'number': '22-12.'},
            {'name': 'Expenditures subject to limits', 'number': '23-12(a)'},
            {'name': 'expend. from prior years subject to limits', 'number': '24-12(b)'},
            {'name': 'total expenditures subject to limits', 'number': '25-12(c)'},
            {'name': 'Federal Funds SCH A', 'number': '26-13.'},
            {'name': 'Itemized', 'number': '27-14(a)'},
            {'name': 'unitemized', 'number': '28-14(b)'},
            {'name': 'subtotal', 'number': '29-14(c)'},
            {'name': 'Transfers from affiliated Committees.', 'number': '30-15.'},
            {'name': 'loans received', 'number': '31-16(a)'},
            {'name': 'loan repayments received', 'number': '32-16(b)'},
            {'name': 'subtotal loans/repayments', 'number': '33-16(c)'},
            {'name': 'Itemized', 'number': '34-17(a)'},
            {'name': 'unitemized', 'number': '35-17(b)'},
            {'name': 'subtotal', 'number': '36-17(c)'},
            {'name': 'Itemized', 'number': '37-18(a)'},
            {'name': 'unitemized', 'number': '38-18(b)'},
            {'name': 'subtotal', 'number': '39-18(c)'},
            {'name': 'Itemized', 'number': '40-19(a)'},
            {'name': 'unitemized', 'number': '41-19(b)'},
            {'name': 'subtotal', 'number': '42-19(c)'},
            {'name': 'total receipts', 'number': '43-20.'},
            {'name': 'Itemized', 'number': '44-21(a)'},
            {'name': 'unitemized', 'number': '45-21(b)'},
            {'name': 'subtotal', 'number': '46-21(c)'},
            {'name': 'Transfers to Affiliated Committees', 'number': '47-22.'},
            {'name': 'loans made', 'number': '48-23(a)'},
            {'name': 'loan repayments made', 'number': '49-23(b)'},
            {'name': 'subtotal', 'number': '50-23(c)'},
            {'name': 'Itemized', 'number': '51-24(a)'},
            {'name': 'unitemized', 'number': '52-24(b)'},
            {'name': 'subtotal', 'number': '53-24(c)'},
            {'name': 'Total disbursements', 'number': '54-25.'},
            {'name': 'Cash on Hand', 'number': '55-6.(a)'},
            {'name': 'YEAR', 'number': '56-6.(a) 19'},
            {'name': 'Total receipts', 'number': '57-6.(c)'},
            {'name': 'Subtotal', 'number': '58-6.(d)'},
            {'name': 'Total disbursements', 'number': '59-7.'},
            {'name': 'COH CLOSE', 'number': '60-8.'},
            {'name': 'Convention expenditures', 'number': '61-11.'},
            {'name': 'refunds/rebates/returns relating to conv exp.', 'number': '62-12.'},
            {'name': 'Expenditures subject to limits', 'number': '63-12(a)'},
            {'name': 'expend. from prior years subject to limits', 'number': '64-12(b)'},
            {'name': 'total expenditures subject to limits', 'number': '65-12(c)'},
            {'name': 'Federal Funds', 'number': '66-13.'},
            {'name': 'subtotal', 'number': '67-14(c)'},
            {'name': 'Transfers from affiliated Committees.', 'number': '68-15.'},
            {'name': 'subtotal loans/repayments', 'number': '69-16(c)'},
            {'name': 'subtotal', 'number': '70-17(c)'},
            {'name': 'subtotal', 'number': '71-18(c)'},
            {'name': 'subtotal', 'number': '72-19(c)'},
            {'name': 'total receipts', 'number': '73-20.'},
            {'name': 'subtotal', 'number': '74-21(c)'},
            {'name': 'Transfers to Affiliated Committees', 'number': '75-22.'},
            {'name': 'subtotal', 'number': '76-23(c)'},
            {'name': 'subtotal', 'number': '77-24(c)'},
            {'name': 'Total disbursements', 'number': '78-25.'},
            {'name': 'NAME/TREASURER (as signed)', 'number': '79'},
            {'name': 'Signed', 'number': '80-'},
    ]
        self.fields_names = self.hash_names(self.fields)
