class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['CHG OF ADDRESS', '9', '', ''],
            ['Qual/Non Q', '10-', '', ''],
            ['INDEMP', '11', '', ''],
            ['INDOCC', '12', '', ''],
            ['RPTCODE', '13', '', ''],
            ['RPTPGI', '14', '', ''],
            ['Of Election', '15-', '', ''],
            ['STATE (Of Election)', '16', '', ''],
            ['Coverage From', '17-', '', ''],
            ['Coverage To', '18-', '', ''],
            ['TOTAL CONTRIBUTION', '19', '', ''],
            ['TOTAL INDEP. EXPEND', '20', '', ''],
            ['Person Completing Form', '21-', '', ''],
            ['Signed', '22-', '', ''],
            ['Notarized', '23-', '', ''],
            ['Notary Commission Expires', '24-', '', ''],
            ['Notary', '25-', '', ''],
    ]
