class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['CREDITOR CODE', '3', '', ''],
            ['NAME (Contributor/Lender)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['Incurred', '10-', '', ''],
            ['AMOUNT OWED TO', '11', '', ''],
            ['AMOUNT OFFERED IN', '12', '', ''],
            ['Initial Terms And Nature Of Debt', '13-A. ', '', ''],
            ['Efforts Made By Cmte To Pay Debt', '14-B. ', '', ''],
            ['Steps Taken By Creditor To Collect', '15-C. ', '', ''],
            ['effort made by creditor to collect...', '16-D. ', '', ''],
            ['N If No Explain', '17-D. ', '', ''],
            ['terms of debt settlement comparable...', '18-E. ', '', ''],
            ['N If No Explain', '19-E. ', '', ''],
            ['FEC COMMITTEE ID NUMBER', '20', '', ''],
            ['FEC CANDIDATE ID NUMBER', '21', '', ''],
            ['CANDIDATE NAME', '22', '', ''],
            ['CAN/OFFICE', '23', '', ''],
            ['CAN/STATE', '24', '', ''],
            ['CAN/DIST', '25', '', ''],
            ['NAME of creditor or representative', '26', '', ''],
            ['Signed', '27-', '', ''],
            ['AMENDED CD', '28', '', ''],
            ['TRAN ID', '29', '', ''],
    ]
