class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['RECIPIENT NAME', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['TRANS CODE', '10', '', ''],
            ['TRANS DESCRIP', '11', '', ''],
            ['ITEM ELECT CD', '12', '', ''],
            ['ITEM ELECT OTHER', '13', '', ''],
            ['DATE OF EXPENDITURE', '14', '', ''],
            ['AMOUNT OF EXPENDITURE', '15', '', ''],
            ['FEC COMMITTEE ID NUMBER', '16', '', ''],
            ['FEC CANDIDATE ID NUMBER', '17', '', ''],
            ['CANDIDATE NAME', '18', '', ''],
            ['CAN/OFFICE', '19', '', ''],
            ['CAN/STATE', '20', '', ''],
            ['CAN/DIST', '21', '', ''],
            ['CONDUIT NAME', '22', '', ''],
            ['CONDUIT STREET 1', '23', '', ''],
            ['CONDUIT STREET 2', '24', '', ''],
            ['CONDUIT CITY', '25', '', ''],
            ['CONDUIT STATE', '26', '', ''],
            ['CONDUIT ZIP', '27', '', ''],
            ['MEMO CODE', '28', '', ''],
            ['MEMO TEXT', '29', '', ''],
            ['AMENDED CD', '30', '', ''],
            ['TRAN ID', '31', '', ''],
            ['BACK REF TRAN ID', '32', '', ''],
            ['BACK REF SCHED NAME', '33', '', ''],
            ['NAT Committee NON-FED ACCT', '34', '', ''],
    ]
