class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['NAME (Loan Source)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['ELECTION', '10', '', ''],
            ['ELECTION DESCRIPTION', '11', '', ''],
            ['ORIG. AMT OF LOAN', '12', '', ''],
            ['PAYMENT TO DATE', '13', '', ''],
            ['LOAN BALANCE', '14', '', ''],
            ['Incurred', '15-', '', ''],
            ['DUE DATE TERMS', '16', '', ''],
            ['PCT RATE TERMS', '17', '', ''],
            ['SECURED YESNO', '18', '', ''],
            ['FEC COMMITTEE ID NUMBER', '19', '', ''],
            ['FEC CANDIDATE ID NUMBER', '20', '', ''],
            ['CANDIDATE NAME', '21', '', ''],
            ['CAN/OFFICE', '22', '', ''],
            ['CAN/STATE', '23', '', ''],
            ['CAN/DIST', '24', '', ''],
            ['AMENDED CD', '25', '', ''],
            ['TRAN ID', '26', '', ''],
    ]
