class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['NAME (Payee)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['PURPOSE/EVENT', '10', '', ''],
            ['DATE', '11', '', ''],
            ['TOTAL AMOUNT', '12', '', ''],
            ['FEDERAL SHARE', '13', '', ''],
            ['NON FEDERAL SHARE', '14', '', ''],
            ['Activity Is Admin./Voter Drive', '15-', '', ''],
            ['Activity Is Fundrainsig', '16-', '', ''],
            ['Activity Is Exempt', '17-', '', ''],
            ['Act. Direct Can Support', '18-', '', ''],
            ['EVENT YEAR-TO-DATE', '19', '', ''],
            ['ADDITIONAL DESCRIPTION', '20', '', ''],
            ['FEC COMMITTEE ID NUMBER', '21', '', ''],
            ['FEC CANDIDATE ID NUMBER', '22', '', ''],
            ['CANDIDATE NAME', '23', '', ''],
            ['CAN/OFFICE', '24', '', ''],
            ['CAN/STATE', '25', '', ''],
            ['CAN/DIST', '26', '', ''],
            ['CONDUIT NAME', '27', '', ''],
            ['CONDUIT STREET 1', '28', '', ''],
            ['CONDUIT STREET 2', '29', '', ''],
            ['CONDUIT CITY', '30', '', ''],
            ['CONDUIT STATE', '31', '', ''],
            ['CONDUIT ZIP', '32', '', ''],
            ['AMENDED CD', '33', '', ''],
            ['TRAN ID', '34', '', ''],
            ['MEMO CODE', '35', '', ''],
            ['MEMO TEXT', '36', '', ''],
            ['BACK REF TRAN ID', '37', '', ''],
            ['BACK REF SCHED NAME', '38', '', ''],
    ]
