class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['Bank Account ID Number', '3', '', ''],
            ['NAME (Of Account)', '4', '', ''],
            ['Coverage From', '5-', '', ''],
            ['Coverage To', '6-', '', ''],
            ['Total Receipts', '7', '1', ''],
            ['Transfers to FED or allocation', '8', '2', ''],
            ['Transfers to state/local Party organizations', '9', '3', ''],
            ['Direct state/local candidate support', '10', '4', ''],
            ['Other Disbursements', '11', '5', ''],
            ['Total Disbursements', '12', '6', ''],
            ['Beginning COH', '13', '7', ''],
            ['Receipts', '15', '8', ''],
            ['Subtotal', '15', '9', ''],
            ['Disbursements', '16', '10', ''],
            ['Ending COH', '17', '11', ''],
            ['Total receipts', '18', '1', ''],
            ['Transfers to FED or allocation', '19', '2', ''],
            ['Transfers to state/local Party organizations', '20', '3', ''],
            ['Direct state/local candidate support', '21', '4', ''],
            ['Other Disbursements', '22', '5', ''],
            ['Total Disbursements', '23', '6', ''],
            ['Beginning COH (as of Jan 1)', '24', '7', ''],
            ['Receipts', '25', '8', ''],
            ['Subtotal', '26', '9', ''],
            ['Disbursements', '27', '10', ''],
            ['Ending COH', '28', '11', ''],
            ['AMENDED CD', '29', '', ''],
            ['TRAN ID', '30', '', ''],
            ['Account Number for Account named in Field #4', '31', '', ''],
    ]
