class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['CONTRIB ORGANIZATION NAME', '4', '', ''],
            ['CONTRIBUTOR LAST NAME', '5', '', ''],
            ['CONTRIBUTOR FIRST NAME', '6', '', ''],
            ['CONTRIBUTOR MIDDLE NAME', '7', '', ''],
            ['CONTRIBUTOR PREFIX', '8', '', ''],
            ['CONTRIBUTOR SUFFIX', '9', '', ''],
            ['STREET 1', '10', '', ''],
            ['STREET 2', '11', '', ''],
            ['CITY', '12', '', ''],
            ['STATE', '13', '', ''],
            ['ZIP', '14', '', ''],
            ['DATE RECEIVED', '15', '', ''],
            ['AMOUNT RECEIVED', '16', '', ''],
            ['AGGREGATE AMT TO DATE', '17', '', ''],
            ['INTERNAL USE ONLY', '18', '', ''],
            ['TRAN ID', '19', '', ''],
            ['BACK REF TRAN ID', '20', '', ''],
            ['BACK REF SCHED NAME', '21', '', ''],
    ]
