import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER FEC CMTE ID', 'number': '2'},
            {'name': 'Total Contributions (No Loans)', 'number': '3-(6a)'},
            {'name': 'Total Contribution Refunds', 'number': '4-(6b)'},
            {'name': 'Net Contributions', 'number': '5-(6c)'},
            {'name': 'Total Operating Expenditures', 'number': '6-(7a)'},
            {'name': 'Total Offsets to Operating Expenditures', 'number': '7-(7b)'},
            {'name': 'NET Operating Expenditures.', 'number': '8-(7c)'},
            {'name': 'Individuals Itemized', 'number': '9-11(a.i)'},
            {'name': 'Individuals Unitemized', 'number': '10-11(a.ii)'},
            {'name': 'Individuals Total', 'number': '11-11(a.iii)'},
            {'name': 'Political Party Committees', 'number': '12-11(b)'},
            {'name': 'All Other Political Committees (PACS)', 'number': '13-11(c)'},
            {'name': 'The Candidate', 'number': '14-11(d)'},
            {'name': 'Total Contributions', 'number': '15-11(e)'},
            {'name': 'Transfers From Other AUTH Committees', 'number': '16-12.'},
            {'name': 'Loans made or guarn. by the Candidate', 'number': '17-13(a)'},
            {'name': 'All Other Loans', 'number': '18-13(b)'},
            {'name': 'Total Loans', 'number': '19-13(c)'},
            {'name': 'Offsets to Operating Expenditures', 'number': '20-14.'},
            {'name': 'Other Receipts', 'number': '21-15.'},
            {'name': 'Total Receipts', 'number': '22-16.'},
            {'name': 'Operating Expenditures', 'number': '23-17'},
            {'name': 'Transfers To Other AUTH Committees', 'number': '24-18.'},
            {'name': 'Loan Repayment By Candidate', 'number': '25-19(a)'},
            {'name': 'Loan Repayments, ALL Other Loans', 'number': '26-19(b)'},
            {'name': 'Total Loan Repayments', 'number': '27-19(c)'},
            {'name': 'Refund/Individuals Other than Political Committees', 'number': '28-20(a)'},
            {'name': 'Refund, Political Party Committees', 'number': '29-20(b)'},
            {'name': 'Refund, Other Political Committees', 'number': '30-20(c)'},
            {'name': 'Total Contributions Refunds', 'number': '31-20(d)'},
            {'name': 'Other Disbursements', 'number': '32-21.'},
            {'name': 'Total Disbursements', 'number': '33-22.'},
            {'name': 'Date - General Election', 'number': '34'},
            {'name': 'Date - Day after General Election', 'number': '35'},
    ]
        self.fields_names = self.hash_names(self.fields)
