class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['NAME (Contributor/Lender)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['INDEMP', '10', '', ''],
            ['INDOCC', '11', '', ''],
            ['Of Contribution', '12-', '', ''],
            ['AMOUNT', '13', '', ''],
            ['FEC COMMITTEE ID NUMBER', '14', '', ''],
            ['FEC CANDIDATE ID NUMBER', '15', '', ''],
            ['CANDIDATE NAME', '16', '', ''],
            ['CAN/OFFICE', '17', '', ''],
            ['CAN/STATE', '18', '', ''],
            ['CAN/DIST', '19', '', ''],
            ['CONDUIT NAME', '20', '', ''],
            ['CONDUIT STREET 1', '21', '', ''],
            ['CONDUIT STREET 2', '22', '', ''],
            ['CONDUIT CITY', '23', '', ''],
            ['CONDUIT STATE', '24', '', ''],
            ['CONDUIT ZIP', '25', '', ''],
            ['AMENDED CD', '26', '', ''],
            ['TRAN ID', '27', '', ''],
    ]
