from fec.version.records_base import RecordsBase
class Records(RecordsBase):
    def __init__(self):
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER FEC CMTE ID', 'number': '2'},
            {'name': 'ENTITY TYPE', 'number': '3'},
            {'name': 'RECIPIENT NAME', 'number': '4'},
            {'name': 'STREET 1', 'number': '5'},
            {'name': 'STREET 2', 'number': '6'},
            {'name': 'CITY', 'number': '7'},
            {'name': 'STATE', 'number': '8'},
            {'name': 'ZIP', 'number': '9'},
            {'name': 'TRANS Purpose CODE', 'number': '10'},
            {'name': 'TRANS Purpose DESCRIP', 'number': '11'},
            {'name': 'ITEM ELECT CD', 'number': '12'},
            {'name': 'ITEM ELECT OTHER', 'number': '13'},
            {'name': 'DATE OF EXPENDITURE', 'number': '14'},
            {'name': 'AMOUNT OF EXPENDITURE', 'number': '15'},
            {'name': 'FEC COMMITTEE ID NUMBER', 'number': '16'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '17'},
            {'name': 'CANDIDATE NAME', 'number': '18'},
            {'name': 'CAN/OFFICE', 'number': '19'},
            {'name': 'CAN/STATE', 'number': '20'},
            {'name': 'CAN/DIST', 'number': '21'},
            {'name': 'CONDUIT NAME', 'number': '22'},
            {'name': 'CONDUIT STREET 1', 'number': '23'},
            {'name': 'CONDUIT STREET 2', 'number': '24'},
            {'name': 'CONDUIT CITY', 'number': '25'},
            {'name': 'CONDUIT STATE', 'number': '26'},
            {'name': 'CONDUIT ZIP', 'number': '27'},
            {'name': 'MEMO CODE', 'number': '28'},
            {'name': 'MEMO TEXT', 'number': '29'},
            {'name': 'AMENDED CD', 'number': '30'},
            {'name': 'TRAN ID', 'number': '31'},
            {'name': 'BACK REF TRAN ID', 'number': '32'},
            {'name': 'BACK REF SCHED NAME', 'number': '33'},
            {'name': 'Reference to SI or SL system code that identifies the Account', 'number': '34'},
            {'name': 'REFUND OR DISPOSAL OF EXCESS', 'number': '35'},
            {'name': 'CATEGORY CODE', 'number': '36'},
            {'name': 'COMMUNICATION DATE', 'number': '37'},
            {'name': 'RECIPIENT ORGANIZATION NAME', 'number': '38'},
            {'name': 'RECIPIENT LAST NAME', 'number': '39'},
            {'name': 'RECIPIENT FIRST NAME', 'number': '40'},
            {'name': 'RECIPIENT MIDDLE NAME', 'number': '41'},
            {'name': 'RECIPIENT PREFIX', 'number': '42'},
            {'name': 'RECIPIENT SUFFIX', 'number': '43'},
    ]
