from fec.version.records_base import RecordsBase
class Records(RecordsBase):
    def __init__(self):
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER FEC CMTE ID', 'number': '2'},
            {'name': 'SPACE HOLDER', 'number': '3'},
            {'name': 'SPACE HOLDER', 'number': '4'},
            {'name': 'SPACE HOLDER', 'number': '5'},
            {'name': 'SPACE HOLDER', 'number': '6'},
            {'name': 'SPACE HOLDER', 'number': '7'},
            {'name': 'SPACE HOLDER', 'number': '8'},
            {'name': 'SPACE HOLDER', 'number': '9'},
            {'name': 'SPACE HOLDER', 'number': '10'},
            {'name': 'SPACE HOLDER', 'number': '11'},
            {'name': 'SPACE HOLDER', 'number': '12'},
            {'name': 'SPACE HOLDER', 'number': '13'},
            {'name': 'SPACE HOLDER', 'number': '14'},
            {'name': 'SPACE HOLDER', 'number': '15'},
            {'name': 'SPACE HOLDER', 'number': '16'},
            {'name': 'SPACE HOLDER', 'number': '17'},
            {'name': 'SPACE HOLDER', 'number': '18'},
            {'name': 'SPACE HOLDER', 'number': '19'},
            {'name': 'SPACE HOLDER', 'number': '20'},
            {'name': 'SPACE HOLDER', 'number': '21'},
            {'name': 'SPACE HOLDER', 'number': '22'},
            {'name': 'SPACE HOLDER', 'number': '23'},
            {'name': 'SPACE HOLDER', 'number': '24'},
            {'name': 'SPACE HOLDER', 'number': '25'},
            {'name': 'SPACE HOLDER', 'number': '26'},
            {'name': 'SPACE HOLDER', 'number': '27'},
            {'name': 'INTERNAL USE ONLY', 'number': '28'},
            {'name': 'TRAN ID', 'number': '29'},
            {'name': 'State and Local Party Committee Presidential-Only Election Year (28% Federal)', 'number': '30'},
            {'name': 'State and Local Party Committee Presidential and Senate Election Year (36% Federal)', 'number': '31'},
            {'name': 'State and Local Party Committee Senate-Only Election Year (21% Federal)', 'number': '32'},
            {'name': 'State and Local Party Committee Non-Presidential and Non-Senate Election Year (15% Federal)', 'number': '33'},
            {'name': 'FLAT MINIMUM FEDERAL PERCENTAGE', 'number': '34'},
            {'name': 'FEDERAL PERCENT', 'number': '35'},
            {'name': 'NONFEDERAL PERCENT', 'number': '36'},
            {'name': 'ADMINISTRATIVE RATIO APPLIES', 'number': '37'},
            {'name': 'GENERIC VOTER DRIVE RATIO APPLIES', 'number': '38'},
            {'name': 'PUBLIC COMMUNICATIONS REFERENCING PARTY ONLY RATIO APPLIES', 'number': '39'},
    ]
