class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['CHANGE OF ADDRESS', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['REPORT CODE', '10', '', ''],
            ['AMENDMENT DATE', '11', '', ''],
            ['COVERAGE FROM DATE', '12', '', ''],
            ['COVERAGE THROUGH DATE', '13', '', ''],
            ['TOTAL DONATIONS ACCEPTED', '14', '5', ''],
            ['TOTAL DONATIONS REFUNDED', '15', '6', ''],
            ['NET DONATIONS', '16', '7', ''],
            ['DESIGNATED LAST NAME', '17', '', ''],
            ['DESIGNATED FIRST NAME', '18', '', ''],
            ['DESIGNATED MIDDLE NAME', '19', '', ''],
            ['DESIGNATED PREFIX', '20', '', ''],
            ['DESIGNATED SUFFIX', '21', '', ''],
            ['DATE SIGNED', '22', '', ''],
    ]
