class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['COMMITTEE TYPE', '9', '', ''],
            ['AFFILIATED - DATE FORM F1 FILED', '10', '', ''],
            ['AFFILIATED COMMITTEE FEC ID', '11', '', ''],
            ['AFFILIATED COMMITTEE NAME', '12', '', ''],
            ['CANDIDATE ID NUMBER', '13', 'I', ''],
            ['CANDIDATE LAST NAME', '14', 'I', ''],
            ['CANDIDATE FIRST NAME', '15', 'I', ''],
            ['CANDIDATE MIDDLE NAME', '16', 'I', ''],
            ['CANDIDATE PREFIX', '17', 'I', ''],
            ['CANDIDATE SUFFIX', '18', 'I', ''],
            ['CANDIDATE OFFICE', '19', 'I', ''],
            ['CANDIDATE STATE', '20', 'I', ''],
            ['CANDIDATE DIST', '21', 'I', ''],
            ['DATE OF CONTRIBUTION', '22', 'I', ''],
            ['CANDIDATE ID NUMBER', '23', 'II', ''],
            ['CANDIDATE LAST NAME', '24', 'II', ''],
            ['CANDIDATE FIRST NAME', '25', 'II', ''],
            ['CANDIDATE MIDDLE NAME', '26', 'II', ''],
            ['CANDIDATE PREFIX', '27', 'II', ''],
            ['CANDIDATE SUFFIX', '28', 'II', ''],
            ['CANDIDATE OFFICE', '29', 'II', ''],
            ['CANDIDATE STATE', '30', 'II', ''],
            ['CANDIDATE DIST', '31', 'II', ''],
            ['DATE OF CONTRIBUTION', '32', 'II', ''],
            ['CANDIDATE ID NUMBER', '33', 'III', ''],
            ['CANDIDATE LAST NAME', '34', 'III', ''],
            ['CANDIDATE FIRST NAME', '35', 'III', ''],
            ['CANDIDATE MIDDLE NAME', '36', 'III', ''],
            ['CANDIDATE PREFIX', '37', 'III', ''],
            ['CANDIDATE SUFFIX', '38', 'III', ''],
            ['CANDIDATE OFFICE', '39', 'III', ''],
            ['CANDIDATE STATE', '40', 'III', ''],
            ['CANDIDATE DIST', '41', 'III', ''],
            ['DATE OF CONTRIBUTION', '42', 'III', ''],
            ['CANDIDATE ID NUMBER', '43', 'IV', ''],
            ['CANDIDATE LAST NAME', '44', 'IV', ''],
            ['CANDIDATE FIRST NAME', '45', 'IV', ''],
            ['CANDIDATE MIDDLE NAME', '46', 'IV', ''],
            ['CANDIDATE PREFIX', '47', 'IV', ''],
            ['CANDIDATE SUFFIX', '48', 'IV', ''],
            ['CANDIDATE OFFICE', '49', 'IV', ''],
            ['CANDIDATE STATE', '50', 'IV', ''],
            ['CANDIDATE DIST', '51', 'IV', ''],
            ['DATE OF CONTRIBUTION', '52', 'IV', ''],
            ['CANDIDATE ID NUMBER', '53', 'V', ''],
            ['CANDIDATE LAST NAME', '54', 'V', ''],
            ['CANDIDATE FIRST NAME', '55', 'V', ''],
            ['CANDIDATE MIDDLE NAME', '56', 'V', ''],
            ['CANDIDATE PREFIX', '57', 'V', ''],
            ['CANDIDATE SUFFIX', '58', 'V', ''],
            ['CANDIDATE OFFICE', '59', 'V', ''],
            ['CANDIDATE STATE', '60', 'V', ''],
            ['CANDIDATE DIST', '61', 'V', ''],
            ['DATE OF CONTRIBUTION', '62', 'V', ''],
            ['Of 51st Contributor', '63-', '', ''],
            ['Of Orig Registration', '64-', '', ''],
            ['Cmte Met Requirements', '65-', '', ''],
            ['TREASURER LAST NAME', '66', '', ''],
            ['TREASURER FIRST NAME', '67', '', ''],
            ['TREASURER MIDDLE NAME', '68', '', ''],
            ['TREASURER PREFIX', '69', '', ''],
            ['TREASURER SUFFIX', '70', '', ''],
            ['DATE SIGNED', '71', '', ''],
    ]
