class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['JOINT FUND PARTICIPANT Committee NAME', '3', '5', ''],
            ['JOINT FUND PARTICIPANT Committee FEC-ID', '4', '5', ''],
            ['AFFILIATED Committee ID NUM', '5', '6', ''],
            ['AFFILIATED Committee NAME', '6', '6', ''],
            ['AFFILIATED CANDIDATE ID NUM', '7', '6', ''],
            ['AFFILIATED LAST NAME', '8', '6', ''],
            ['AFFILIATED FIRST NAME', '9', '6', ''],
            ['AFFILIATED MIDDLE NAME', '10', '6', ''],
            ['AFFILIATED PREFIX', '11', '6', ''],
            ['AFFILIATED SUFFIX', '12', '6', ''],
            ['AFFILIATED STREET 1', '13', '6', ''],
            ['AFFILIATED STREET 2', '14', '6', ''],
            ['AFFILIATED CITY', '15', '6', ''],
            ['AFFILIATED STATE', '16', '6', ''],
            ['AFFILIATED ZIP', '17', '6', ''],
            ['AFFILIATED RELATIONSHIP CODE', '18', '6', ''],
            ['AGENT LAST NAME', '19', '8', ''],
            ['AGENT FIRST NAME', '20', '8', ''],
            ['AGENT MIDDLE NAME', '21', '8', ''],
            ['AGENT PREFIX', '22', '8', ''],
            ['AGENT SUFFIX', '23', '8', ''],
            ['AGENT STREET 1', '24', '8', ''],
            ['AGENT STREET 2', '25', '8', ''],
            ['AGENT CITY', '26', '8', ''],
            ['AGENT STATE', '27', '8', ''],
            ['AGENT ZIP', '28', '8', ''],
            ['AGENT TITLE', '29', '8', ''],
            ['AGENT TELEPHONE', '30', '8', ''],
            ['BANK NAME', '31', '9', ''],
            ['BANK STREET 1', '32', '9', ''],
            ['BANK STREET 2', '33', '9', ''],
            ['BANK CITY', '34', '9', ''],
            ['BANK STATE', '35', '9', ''],
            ['BANK ZIP', '36', '9', ''],
    ]
