from fec.version.records_base import RecordsBase
class Records(RecordsBase):
    def __init__(self):
        RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER COMMITTEE ID NUMBER', 'number': '2'},
            {'name': 'COMMITTEE NAME', 'number': '3'},
            {'name': 'CHANGE OF ADDRESS', 'number': '4'},
            {'name': 'STREET 1', 'number': '5'},
            {'name': 'STREET 2', 'number': '6'},
            {'name': 'CITY', 'number': '7'},
            {'name': 'STATE', 'number': '8'},
            {'name': 'ZIP', 'number': '9'},
            {'name': 'ELECTION STATE', 'number': '10'},
            {'name': 'ELECTION DISTRICT', 'number': '11'},
            {'name': 'REPORT CODE', 'number': '12'},
            {'name': 'ELECTION CODE', 'number': '13'},
            {'name': 'DATE OF ELECTION', 'number': '14'},
            {'name': 'STATE OF ELECTION', 'number': '15'},
            {'name': 'COVERAGE FROM DATE', 'number': '16'},
            {'name': 'COVERAGE THROUGH DATE', 'number': '17'},
            {'name': 'TREASURER LAST NAME', 'number': '18'},
            {'name': 'TREASURER FIRST NAME', 'number': '19'},
            {'name': 'TREASURER MIDDLE NAME', 'number': '20'},
            {'name': 'TREASURER PREFIX', 'number': '21'},
            {'name': 'TREASURER SUFFIX', 'number': '22'},
            {'name': 'DATE SIGNED', 'number': '23'},
            {'name': 'Total Contributions (NO Loans)', 'number': '24-(6a)'},
            {'name': 'Total Contribution Refunds', 'number': '25-(6b)'},
            {'name': 'Net Contributions', 'number': '26-(6c)'},
            {'name': 'Total Operating Expenditures', 'number': '27-(7a)'},
            {'name': 'Total Offset to Operating Expenditures', 'number': '28-(7b)'},
            {'name': 'NET Operating Expenditures.', 'number': '29-(7c)'},
            {'name': 'CASH ON HAND AT CLOSE ...', 'number': '30-8.'},
            {'name': 'DEBTS TO ( Totals from SCH C and/or D)', 'number': '31-9.'},
            {'name': 'DEBTS BY (Totals from SCH C and/or D)', 'number': '32-10.'},
            {'name': 'Individuals Itemized', 'number': '33-11(a i.)'},
            {'name': 'Individuals Unitemized', 'number': '34-11(a.ii)'},
            {'name': 'Individual Contribution Total', 'number': '35-11(a.iii)'},
            {'name': 'Political Party Committees', 'number': '36-11(b)'},
            {'name': 'Other Political Committees', 'number': '37-11(c)'},
            {'name': 'The Candidate', 'number': '38-11(d)'},
            {'name': 'Total Contributions', 'number': '39-11(e)'},
            {'name': 'Transfers From Other Authorized Committees', 'number': '40-12.'},
            {'name': 'Loans made or guarn. by the Candidate', 'number': '41-13(a)'},
            {'name': 'All Other Loans', 'number': '42-13(b)'},
            {'name': 'Total Loans', 'number': '43-13(c)'},
            {'name': 'Offsets to Operating Expenditures', 'number': '44-14.'},
            {'name': 'Other Receipts', 'number': '45-15.'},
            {'name': 'Total Receipts', 'number': '46-16.'},
            {'name': 'Operating Expenditures', 'number': '47-17.'},
            {'name': 'Transfers to Other Authorized Committees', 'number': '48-18.'},
            {'name': 'Of Loans made or guar. by the Cand.', 'number': '49-19(a)'},
            {'name': 'Loan Repayments, All Other Loans', 'number': '50-19(b)'},
            {'name': 'Total Loan Repayments', 'number': '51-19(c)'},
            {'name': 'Refund/Individuals Other than Political Committees', 'number': '52-20(a)'},
            {'name': 'Refund/Political Party Committees', 'number': '53-20(b)'},
            {'name': 'Refund/Other Political Committees', 'number': '54-20(c)'},
            {'name': 'Total Contribution Refunds', 'number': '55-20(d)'},
            {'name': 'Other Disbursements', 'number': '56-21.'},
            {'name': 'Total Disbursements', 'number': '57-22.'},
            {'name': 'Cash Beginning Reporting Period', 'number': '58-23.'},
            {'name': 'Total Receipts this Period', 'number': '59-24.'},
            {'name': 'Subtotals', 'number': '60-25.'},
            {'name': 'Total Disbursements this Period', 'number': '61-26.'},
            {'name': 'Cash on hand at Close Period', 'number': '62-27.'},
            {'name': 'Total Contributions (No Loans)', 'number': '63-(6a)'},
            {'name': 'Total Contribution Refunds', 'number': '64-(6b)'},
            {'name': 'Net Contributions', 'number': '65-(6c)'},
            {'name': 'Total Operating Expenditures', 'number': '66-(7a)'},
            {'name': 'Total Offsets to Operating Expenditures', 'number': '67-(7b)'},
            {'name': 'NET Operating Expenditures.', 'number': '68-(7c)'},
            {'name': 'Individuals Itemized', 'number': '69-11(a i.)'},
            {'name': 'Individuals Unitemized', 'number': '70-11(a.ii)'},
            {'name': 'Individuals Total', 'number': '71-11(a.iii)'},
            {'name': 'Political Party Committees', 'number': '72-11(b)'},
            {'name': 'All Other Political Committees (PACS)', 'number': '73-11(c)'},
            {'name': 'The Candidate', 'number': '74-11(d)'},
            {'name': 'Total Contributions', 'number': '75-11(e)'},
            {'name': 'Transfers From Other AUTH Committees', 'number': '76-12.'},
            {'name': 'Loans made or guarn. by the Candidate', 'number': '77-13(a)'},
            {'name': 'All Other Loans', 'number': '78-13(b)'},
            {'name': 'Total Loans', 'number': '79-13(c)'},
            {'name': 'Offsets to Operating Expenditures', 'number': '80-14.'},
            {'name': 'Other Receipts', 'number': '81-15.'},
            {'name': 'Total Receipts', 'number': '82-16.'},
            {'name': 'Operating Expenditures', 'number': '83-17'},
            {'name': 'Transfers To Other AUTH Committees', 'number': '84-18.'},
            {'name': 'Loan Repayment By Candidate', 'number': '85-19(a)'},
            {'name': 'Loan Repayments, ALL Other Loans', 'number': '86-19(b)'},
            {'name': 'Total Loan Repayments', 'number': '87-19(c)'},
            {'name': 'Refund/Individuals Other than Political Committees', 'number': '88-20(a)'},
            {'name': 'Refund, Political Party Committees', 'number': '89-20(b)'},
            {'name': 'Refund, Other Political Committees', 'number': '90-20(c)'},
            {'name': 'Total Contributions Refunds', 'number': '91-20(d)'},
            {'name': 'Other Disbursements', 'number': '92-21.'},
            {'name': 'Total Disbursements', 'number': '93-22.'},
    ]
        self.fields_names = self.hash_names(self.fields)
