class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['CHANGE OF ADDRESS', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['ACTIVITY PRIMARY', '10', '', ''],
            ['ACTIVITY GENERAL', '11', '', ''],
            ['REPORT CODE', '12', '', ''],
            ['ELECTION CODE', '13', '', ''],
            ['DATE OF ELECTION', '14', '', ''],
            ['STATE OF ELECTION', '15', '', ''],
            ['COVERAGE FROM DATE', '16', '', ''],
            ['COVERAGE THROUGH DATE', '17', '', ''],
            ['TREASURER LAST NAME', '18', '', ''],
            ['TREASURER FIRST NAME', '19', '', ''],
            ['TREASURER MIDDLE NAME', '20', '', ''],
            ['TREASURER PREFIX', '21', '', ''],
            ['TREASURER SUFFIX', '22', '', ''],
            ['DATE SIGNED', '23', '', ''],
            ['Cash on Hand Beginning Period', '24', '6', ''],
            ['Total Receipts', '25', '7', ''],
            ['Subtotal', '26', '8', ''],
            ['Total Disbursements', '27', '9', ''],
            ['Cash on Hand Close of Period', '28', '10', ''],
            ['Debts to', '29', '11', ''],
            ['Debts by', '30', '12', ''],
            ['Expenditures Subject to Limits', '31', '13', ''],
            ['Net Contributions', '32', '14', ''],
            ['Net Operating Expenditures', '33', '15', ''],
            ['Federal Funds', '34', '16', ''],
            ['Individuals Itemized', '35', '17', 'a.i'],
            ['Individuals Unitemized', '36', '17', 'a.ii'],
            ['Individual Contribution Total', '37', '17', 'a.iii'],
            ['Political Party Committees', '38', '17', 'b'],
            ['Other Political Committees (PACs)', '39', '17', 'c'],
            ['The Candidate', '40', '17', 'd'],
            ['Total Contributions', '41', '17', 'e'],
            ['Transfers From Aff/Other Party Committees', '42', '18', ''],
            ['Received from or Guaranteed by Cand.', '43', '19', 'a'],
            ['Other Loans', '44', '19', 'b'],
            ['Total Loans', '45', '19', 'c'],
            ['Operating', '46', '20', 'a'],
            ['Fundraising', '47', '20', 'b'],
            ['Legal and Accounting', '48', '20', 'c'],
            ['Total offsets to Expenditures', '49', '20', 'd'],
            ['Other Receipts', '50', '21', ''],
            ['Total Receipts', '51', '22', ''],
            ['Operating Expenditures', '52', '23', ''],
            ['Transfers to Other Authorized Committees', '53', '24', ''],
            ['Fundraising Disbursements', '54', '25', ''],
            ['Exempt Legal & Accounting Disbursement', '55', '26', ''],
            ['Made or guaranteed by Candidate', '56', '27', 'a'],
            ['Other Repayments', '57', '27', 'b'],
            ['Total Loan Repayments Made', '58', '27', 'c'],
            ['Individuals', '59', '28', 'a'],
            ['Political Party Committees', '60', '28', 'b'],
            ['Other Political Committees', '61', '28', 'c'],
            ['Total Contributions Refunds', '62', '28', 'd'],
            ['Other Disbursements', '63', '29', ''],
            ['Total Disbursements', '64', '30', ''],
            ['Items on Hand to be Liquidated', '65', '31', ''],
            ['ALABAMA', '66', '', ''],
            ['ALASKA', '67', '', ''],
            ['ARIZONA', '68', '', ''],
            ['ARKANSAS', '69', '', ''],
            ['CALIFORNIA', '70', '', ''],
            ['COLORADO', '71', '', ''],
            ['CONNECTICUT', '72', '', ''],
            ['DELAWARE', '73', '', ''],
            ['DIST OF COLUMBIA', '74', '', ''],
            ['FLORIDA', '75', '', ''],
            ['GEORGIA', '76', '', ''],
            ['HAWAII', '77', '', ''],
            ['IDAHO', '78', '', ''],
            ['ILLINOIS', '79', '', ''],
            ['INDIANA', '80', '', ''],
            ['IOWA', '81', '', ''],
            ['KANSAS', '82', '', ''],
            ['KENTUCKY', '83', '', ''],
            ['LOUISIANA', '84', '', ''],
            ['MAINE', '85', '', ''],
            ['MARYLAND', '86', '', ''],
            ['MASSACHUSETTS', '87', '', ''],
            ['MICHIGAN', '88', '', ''],
            ['MINNESOTA', '89', '', ''],
            ['MISSISSIPPI', '90', '', ''],
            ['MISSOURI', '91', '', ''],
            ['MONTANA', '92', '', ''],
            ['NEBRASKA', '93', '', ''],
            ['NEVADA', '94', '', ''],
            ['NEW HAMPSHIRE', '95', '', ''],
            ['NEW JERSEY', '96', '', ''],
            ['NEW MEXICO', '97', '', ''],
            ['NEW YORK', '98', '', ''],
            ['NORTH CAROLINA', '99', '', ''],
            ['NORTH DAKOTA', '100', '', ''],
            ['OHIO', '101', '', ''],
            ['OKLAHOMA', '102', '', ''],
            ['OREGON', '103', '', ''],
            ['PENNSYLVANIA', '104', '', ''],
            ['RHODE ISLAND', '105', '', ''],
            ['SOUTH CAROLINA', '106', '', ''],
            ['SOUTH DAKOTA', '107', '', ''],
            ['TENNESSEE', '108', '', ''],
            ['TEXAS', '109', '', ''],
            ['UTAH', '110', '', ''],
            ['VERMONT', '111', '', ''],
            ['VIRGINIA', '112', '', ''],
            ['WASHINGTON', '113', '', ''],
            ['WEST VIRGINIA', '114', '', ''],
            ['WISCONSIN', '115', '', ''],
            ['WYOMING', '116', '', ''],
            ['PUERTO RICO', '117', '', ''],
            ['GUAM', '118', '', ''],
            ['VIRGIN ISLANDS', '119', '', ''],
            ['TOTALS', '120', '', ''],
            ['Federal Funds', '121', '16', ''],
            ['Individuals Itemized', '122', '17', 'a.i'],
            ['Individuals Unitemized', '123', '17', 'a.ii'],
            ['Individual Contribution Total', '124', '17', 'a.iii'],
            ['Political Party Committees', '125', '17', 'b'],
            ['Other Political Committees (PACs)', '126', '17', 'c'],
            ['The Candidate', '127', '17', 'd'],
            ['Total contributions (Other than Loans)', '128', '17', 'e'],
            ['Transfers From Aff/Other Party Committees', '129', '18', ''],
            ['Received from or Guaranteed by Cand.', '130', '19', 'a'],
            ['Other Loans', '131', '19', 'b'],
            ['Total Loans', '132', '19', 'c'],
            ['Operating', '133', '20', 'a'],
            ['Fundraising', '134', '20', 'b'],
            ['Legal and Accounting', '135', '20', 'c'],
            ['Total Offsets to Operating Expenditures', '136', '20', 'd'],
            ['Other Receipts', '137', '21', ''],
            ['Total Receipts', '138', '22', ''],
            ['Operating Expenditures', '139', '23', ''],
            ['Transfers to Other Authorized Committees', '140', '24', ''],
            ['Fundraising Disbursements', '141', '25', ''],
            ['Exempt Legal & Accounting Disbursement', '142', '26', ''],
            ['Made or Guaranteed by the Candidate', '143', '27', 'a'],
            ['Other Repayments', '144', '27', 'b'],
            ['Total Loan Repayments Made', '145', '27', 'c'],
            ['Individuals', '146', '28', 'a'],
            ['Political Party Committees', '147', '28', 'b'],
            ['Other Political Committees', '148', '28', 'c'],
            ['Total Contributions Refunds', '149', '28', 'd'],
            ['Other Disbursements', '150', '29', ''],
            ['Total Disbursements', '151', '30', ''],
            ['ALABAMA', '152', '', ''],
            ['ALASKA', '153', '', ''],
            ['ARIZONA', '154', '', ''],
            ['ARKANSAS', '155', '', ''],
            ['CALIFORNIA', '156', '', ''],
            ['COLORADO', '157', '', ''],
            ['CONNECTICUT', '158', '', ''],
            ['DELAWARE', '159', '', ''],
            ['DIST OF COLUMBIA', '160', '', ''],
            ['FLORIDA', '161', '', ''],
            ['GEORGIA', '162', '', ''],
            ['HAWAII', '163', '', ''],
            ['IDAHO', '164', '', ''],
            ['ILLINOIS', '165', '', ''],
            ['INDIANA', '166', '', ''],
            ['IOWA', '167', '', ''],
            ['KANSAS', '168', '', ''],
            ['KENTUCKY', '169', '', ''],
            ['LOUISIANA', '170', '', ''],
            ['MAINE', '171', '', ''],
            ['MARYLAND', '172', '', ''],
            ['MASSACHUSETTS', '173', '', ''],
            ['MICHIGAN', '174', '', ''],
            ['MINNESOTA', '175', '', ''],
            ['MISSISSIPPI', '176', '', ''],
            ['MISSOURI', '177', '', ''],
            ['MONTANA', '178', '', ''],
            ['NEBRASKA', '179', '', ''],
            ['NEVADA', '180', '', ''],
            ['NEW HAMPSHIRE', '181', '', ''],
            ['NEW JERSEY', '182', '', ''],
            ['NEW MEXICO', '183', '', ''],
            ['NEW YORK', '184', '', ''],
            ['NORTH CAROLINA', '185', '', ''],
            ['NORTH DAKOTA', '186', '', ''],
            ['OHIO', '187', '', ''],
            ['OKLAHOMA', '188', '', ''],
            ['OREGON', '189', '', ''],
            ['PENNSYLVANIA', '190', '', ''],
            ['RHODE ISLAND', '191', '', ''],
            ['SOUTH CAROLINA', '192', '', ''],
            ['SOUTH DAKOTA', '193', '', ''],
            ['TENNESSEE', '194', '', ''],
            ['TEXAS', '195', '', ''],
            ['UTAH', '196', '', ''],
            ['VERMONT', '197', '', ''],
            ['VIRGINIA', '198', '', ''],
            ['WASHINGTON', '199', '', ''],
            ['WEST VIRGINIA', '200', '', ''],
            ['WISCONSIN', '201', '', ''],
            ['WYOMING', '202', '', ''],
            ['PUERTO RICO', '203', '', ''],
            ['GUAM', '204', '', ''],
            ['VIRGIN ISLANDS', '205', '', ''],
            ['TOTALS', '206', '', ''],
    ]
