class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['ENTITY TYPE', '4', '', ''],
            ['CONTRIBUTOR ORGANIZATION NAME', '5', '', ''],
            ['CONTRIBUTOR LAST NAME', '6', '', ''],
            ['CONTRIBUTOR FIRST NAME', '7', '', ''],
            ['CONTRIBUTOR MIDDLE NAME', '8', '', ''],
            ['CONTRIBUTOR PREFIX', '9', '', ''],
            ['CONTRIBUTOR SUFFIX', '10', '', ''],
            ['CONTRIBUTOR STREET 1', '11', '', ''],
            ['CONTRIBUTOR STREET 2', '12', '', ''],
            ['CONTRIBUTOR CITY', '13', '', ''],
            ['CONTRIBUTOR STATE', '14', '', ''],
            ['CONTRIBUTOR ZIP', '15', '', ''],
            ['ELECTION CODE', '16', '', ''],
            ['ITEM DESCRIPTION', '17', '', ''],
            ['ITEM CONTRIBUTION/AQUIRED DATE', '18', '', ''],
            ['ITEM FAIR MARKET VALUE', '19', '', ''],
            ['CONTRIBUTOR EMPLOYER', '20', '', ''],
            ['CONTRIBUTOR OCCUPATION', '21', '', ''],
            ['MEMO CODE', '22', '', ''],
            ['MEMO TEXT/DESCRIPTION', '23', '', ''],
    ]
