from fec.version.records_base import RecordsBase
class Records(RecordsBase):
    def __init__(self):
        RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER COMMITTEE ID NUMBER', 'number': '2'},
            {'name': 'COMMITTEE NAME', 'number': '3'},
            {'name': 'CHANGE OF ADDRESS', 'number': '4'},
            {'name': 'STREET 1', 'number': '5'},
            {'name': 'STREET 2', 'number': '6'},
            {'name': 'CITY', 'number': '7'},
            {'name': 'STATE', 'number': '8'},
            {'name': 'ZIP', 'number': '9'},
            {'name': 'REPORT CODE', 'number': '10'},
            {'name': 'ELECTION CODE', 'number': '11'},
            {'name': 'DATE OF ELECTION', 'number': '12'},
            {'name': 'STATE OF ELECTION', 'number': '13'},
            {'name': 'COVERAGE FROM DATE', 'number': '14'},
            {'name': 'COVERAGE THROUGH DATE', 'number': '15'},
            {'name': 'QUALIFIED COMMITTEE', 'number': '16'},
            {'name': 'TREASURER LAST NAME', 'number': '17'},
            {'name': 'TREASURER FIRST NAME', 'number': '18'},
            {'name': 'TREASURER MIDDLE NAME', 'number': '19'},
            {'name': 'TREASURER PREFIX', 'number': '20'},
            {'name': 'TREASURER SUFFIX', 'number': '21'},
            {'name': 'DATE SIGNED', 'number': '22'},
            {'name': 'Cash on Hand beginning', 'number': '23-6(b)'},
            {'name': 'Total Receipts', 'number': '24-6(c)'},
            {'name': 'Subtotal', 'number': '25-6(d)'},
            {'name': 'Total Disbursements', 'number': '26-7.'},
            {'name': 'Cash on Hand at Close', 'number': '27-8.'},
            {'name': 'Debts to', 'number': '28-9.'},
            {'name': 'Debts by', 'number': '29-10.'},
            {'name': 'Itemized', 'number': '30-11(a)i'},
            {'name': 'Unitemized', 'number': '31-11(a)ii'},
            {'name': 'Total', 'number': '32-11(a)iii'},
            {'name': 'Political Party Committees', 'number': '33-11(b)'},
            {'name': 'Other Political Committees (PACs)', 'number': '34-11(c)'},
            {'name': 'Total Contributions', 'number': '35-11(d)'},
            {'name': 'Transfers from Affiliated/Other Party Committees', 'number': '36-12.'},
            {'name': 'All Loans Received', 'number': '37-13.'},
            {'name': 'Loan Repayments Received', 'number': '38-14.'},
            {'name': 'Offsets to Operating Expenditures (refunds)', 'number': '39-15.'},
            {'name': 'Refunds of Federal Contributions', 'number': '40-16.'},
            {'name': 'Other Federal Receipts (dividends)', 'number': '41-17.'},
            {'name': 'Transfers from Nonfederal Account (H3)', 'number': '42-18(a)'},
            {'name': 'Transfers from Non-Federal (Levin - H5)', 'number': '43-18(b)'},
            {'name': 'Total Non-Federal Transfers (18a+18b)', 'number': '44-18(c)'},
            {'name': 'Total Receipts', 'number': '45-19.'},
            {'name': 'Total Federal Receipts', 'number': '46-20.'},
            {'name': 'Federal Share', 'number': '47-21(a)i'},
            {'name': 'Non-Federal Share', 'number': '48-21(a)ii'},
            {'name': 'Other Federal Operating Expenditures', 'number': '49-21(b)'},
            {'name': 'Total Operating Expenditures', 'number': '50-21(c)'},
            {'name': 'Transfers to Affiliated/Other Party Committees', 'number': '51-22.'},
            {'name': 'Contributions to Federal Candidates/Committees', 'number': '52-23.'},
            {'name': 'Independent Expenditures', 'number': '53-24.'},
            {'name': 'Coordinated Expend made by Party Committees', 'number': '54-25.'},
            {'name': 'Loan Repayments', 'number': '55-26.'},
            {'name': 'Loans Made', 'number': '56-27.'},
            {'name': 'Individuals/Persons', 'number': '57-28(a)'},
            {'name': 'Political Party Committees', 'number': '58-28(b)'},
            {'name': 'Other Political Committees', 'number': '59-28(c)'},
            {'name': 'Total Contributions Refunds', 'number': '60-28(d)'},
            {'name': 'Other Disbursements', 'number': '61-29.'},
            {'name': 'Shared Federal Activity (H6) Fed Share', 'number': '62-30(a)i'},
            {'name': 'Shared Federal Activity (H6) Non-Fed', 'number': '63-30(a)ii'},
            {'name': 'Non-Allocable 100% Fed Election Activity', 'number': '64-30(b)'},
            {'name': 'Total Federal Election Activity', 'number': '65-30(c)'},
            {'name': 'Total Disbursements', 'number': '66-31.'},
            {'name': 'Total Federal Disbursements', 'number': '67-32.'},
            {'name': 'Total Contributions', 'number': '68-33.'},
            {'name': 'Total Contribution Refunds', 'number': '69-34.'},
            {'name': 'Net Contributions', 'number': '70-35.'},
            {'name': 'Total Federal Operating Expenditures', 'number': '71-36.'},
            {'name': 'Offsets to Operating Expenditures', 'number': '72-37.'},
            {'name': 'Net Operating Expenditures', 'number': '73-38.'},
            {'name': 'Cash on Hand Jan 1, 19', 'number': '74-6(a)'},
            {'name': 'Year for Above', 'number': '75'},
            {'name': 'Total Receipts', 'number': '76-6(c)'},
            {'name': 'Subtotal', 'number': '77-6(d)'},
            {'name': 'Total disbursements', 'number': '78-7.'},
            {'name': 'Cash on Hand Close', 'number': '79-8.'},
            {'name': 'Itemized', 'number': '80-11(a)i'},
            {'name': 'Unitemized', 'number': '81-11(a)ii'},
            {'name': 'Total', 'number': '82-11(a)iii'},
            {'name': 'Political Party committees', 'number': '83-11(b)'},
            {'name': 'Other Political Committees (PACs)', 'number': '84-11(c)'},
            {'name': 'Total Contributions', 'number': '85-11(d)'},
            {'name': 'Transfers from Affiliated/Other Party Committees', 'number': '86-12.'},
            {'name': 'All Loans Received', 'number': '87-13.'},
            {'name': 'Loan Repayments Received', 'number': '88-14.'},
            {'name': 'Offsets to Operating Expenditures (refunds)', 'number': '89-15.'},
            {'name': 'Refunds of Federal Contributions', 'number': '90-16.'},
            {'name': 'Other Federal Receipts (dividends)', 'number': '91-17.'},
            {'name': 'Transfers from Nonfederal Account (H3)', 'number': '92-18(a)'},
            {'name': 'Transfers from Non-Federal (Levin - H5)', 'number': '93-18(b)'},
            {'name': 'Total Non-Federal Transfers (18a+18b)', 'number': '94-18(c)'},
            {'name': 'Total Receipts', 'number': '95-19.'},
            {'name': 'Total Federal Receipts', 'number': '96-20.'},
            {'name': 'Federal Share', 'number': '97-21(a)i'},
            {'name': 'Non-Federal Share', 'number': '98-21(a)ii'},
            {'name': 'Other Federal Operating Expenditures', 'number': '99-21(b)'},
            {'name': 'Total operating Expenditures', 'number': '100-21(c)'},
            {'name': 'Transfers to Affiliated/Other Party Committees', 'number': '101-22.'},
            {'name': 'Contributions to Federal Candidates/Committees', 'number': '102-23.'},
            {'name': 'Independent Expenditures', 'number': '103-24.'},
            {'name': 'Coordinated Expend made by Party Committees', 'number': '104-25.'},
            {'name': 'Loan Repayments Made', 'number': '105-26.'},
            {'name': 'Loans Made', 'number': '106-27.'},
            {'name': 'Individuals/Persons', 'number': '107-28(a)'},
            {'name': 'Political Party Committees', 'number': '108-28(b)'},
            {'name': 'Other Political Committees', 'number': '109-28(c)'},
            {'name': 'Total contributions Refunds', 'number': '110-28(d)'},
            {'name': 'Other Disbursements', 'number': '111-29.'},
            {'name': 'Shared Federal Activity (H6) Fed Share', 'number': '112-30(a)i'},
            {'name': 'Shared Federal Activity (H6) Non-Fed', 'number': '113-30(a)ii'},
            {'name': 'Non-Allocable 100% Fed Election Activity', 'number': '114-30(b)'},
            {'name': 'Total Federal Election Activity', 'number': '115-30(c)'},
            {'name': 'Total Disbursements', 'number': '116-31.'},
            {'name': 'Total Federal Disbursements', 'number': '117-32.'},
            {'name': 'Total Contributions', 'number': '118-33.'},
            {'name': 'Total Contribution Refunds', 'number': '119-34.'},
            {'name': 'Net contributions', 'number': '120-35.'},
            {'name': 'Total Federal Operating Expenditures', 'number': '121-36.'},
            {'name': 'Offsets to Operating Expenditures', 'number': '122-37.'},
            {'name': 'Net Operating Expenditures', 'number': '123-38.'},
    ]
        self.fields_names = self.hash_names(self.fields)
