class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['BACK REFERENCE TRAN ID NUMBER', '4', '', ''],
            ['LENDER ORGANIZATION NAME', '5', '', ''],
            ['LENDER STREET 1', '6', '', ''],
            ['LENDER STREET 2', '7', '', ''],
            ['LENDER CITY', '8', '', ''],
            ['LENDER STATE', '9', '', ''],
            ['LENDER ZIP', '10', '', ''],
            ['LOAN AMOUNT', '11', '', ''],
            ['LOAN INTEREST RATE %', '12', '', ''],
            ['LOAN INCURRED DATE', '13', '', ''],
            ['LOAN DUE DATE', '14', '', ''],
            ['Loan Restructured?', '15-A1.', '', ''],
            ['Original', '16-A2. LOAN INCCURED ', '', ''],
            ['CREDIT AMOUNT THIS DRAW', '17-B.1.', '', ''],
            ['TOTAL BALANCE', '18-B.2.', '', ''],
            ['Others liable?', '19-C. ', '', ''],
            ['Collateral?', '20-D. ', '', ''],
            ['DESCRIPTION (IF YES, Specify)', '21', 'D.1', ''],
            ['COLLATERAL VALUE/AMOUNT', '22', 'D.2', ''],
            ['Perfected Interest?', '23-D.3 ', '', ''],
            ['Future Income?', '24-E.1 ', '', ''],
            ['DESCRIPTION (IF YES, Specify)', '25', 'E.2', ''],
            ['ESTIMATED VALUE', '26', 'E.3', ''],
            ['Depository account', '27-E.4 ESTABLISHED ', '', ''],
            ['ACCOUNT LOCATION NAME', '28', 'E.5', ''],
            ['STREET 1', '29', 'E.6', ''],
            ['STREET 2', '30', 'E.7', ''],
            ['CITY', '31', 'E.8', ''],
            ['STATE', '32', 'E.9', ''],
            ['ZIP', '33', 'E.10', ''],
            ['Presidential', '34-E.11 DEPOSIT ACCT AUTH ', '', ''],
            ['BASIS OF LOAN DESCRIPTION', '35-F.', '', ''],
            ['TREASURER LAST NAME', '36', 'G', ''],
            ['TREASURER FIRST NAME', '37', 'G', ''],
            ['TREASURER MIDDLE NAME', '38', 'G', ''],
            ['TREASURER PREFIX', '39', 'G', ''],
            ['TREASURER SUFFIX', '40', 'G', ''],
            ['DATE SIGNED', '41', 'G', ''],
            ['AUTHORIZED LAST NAME', '42', 'H', ''],
            ['AUTHORIZED FIRST NAME', '43', 'H', ''],
            ['AUTHORIZED MIDDLE NAME', '44', 'H', ''],
            ['AUTHORIZED PREFIX', '45', 'H', ''],
            ['AUTHORIZED SUFFIX', '46', 'H', ''],
            ['AUTHORIZED TITLE', '47', 'H', ''],
            ['DATE SIGNED', '48', 'H', ''],
    ]
