class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC COMMITTEE ID', '2', '', ''],
            ['CANDIDATE NAME', '3', '', ''],
            ['CANDIDATE ID', '4', '', ''],
            ['CAN/OFFICE', '5', '', ''],
            ['CANDIDATE STATE', '6', '', ''],
            ['CANDIDATE DISTRICT', '7', '', ''],
            ['COMMITTEE NAME', '8', '', ''],
            ['STREET 1', '9', '', ''],
            ['STREET 2', '10', '', ''],
            ['CITY', '11', '', ''],
            ['STATE', '12', '', ''],
            ['ZIP', '13', '', ''],
            ['PREVIOUS EXPENDITURE AGGREGATE', '14', '', ''],
            ['EXP TOTAL THIS REPORT', '15', '', ''],
            ['EXP TOTAL CYCLE-TO-DATE', '16', '', ''],
            ['as signed', '17-NAME/CANDI', '', ''],
            ['Signed', '18-', '', ''],
            ['MEETS F6 FILING REQUIREMENTS', '19', '', ''],
            ['CANDIDATE EMPLOYER', '20', '', ''],
            ['CANDIDATE OCCUPATION', '21', '', ''],
    ]
