class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['Submitted', '9-', '', ''],
            ['CHG OF COMMITTEE NAME', '10', '', ''],
            ['CHG OF ADDRESS', '11', '', ''],
            ['COMMITTEE TYPE', '12', '5', ''],
            ['FEC CANDIDATE ID NUMBER', '13', '5', ''],
            ['CANDIDATE NAME', '14', '5', ''],
            ['CAN/OFFICE', '15', '5', ''],
            ['CAN/STATE', '16', '5', ''],
            ['CAN/DIST', '17', '5', ''],
            ['PARTY CODE', '18', '5', ''],
            ['PARTY TYPE', '19', '5', ''],
            ['FEC COMMITTEE ID NUMBER', '20', '6', ''],
            ['COMMITTEE NAME (Affiliated)', '21', '6', ''],
            ['STREET 1', '22', '6', ''],
            ['STREET 2', '23', '6', ''],
            ['CITY', '24', '6', ''],
            ['STATE', '25', '6', ''],
            ['ZIP', '26', '6', ''],
            ['RELATIONSHIP (w/ Above Cmte)', '27', '6', ''],
            ['ORGANIZATION TYPE', '28', '6', ''],
            ['Custodian Name', '29-7. ', '', ''],
            ['STREET 1', '30', '7', ''],
            ['STREET 2', '31', '7', ''],
            ['CITY', '32', '7', ''],
            ['STATE', '33', '7', ''],
            ['ZIP', '34', '7', ''],
            ['TITLE', '35', '7', ''],
            ['TELEPHONE', '36', '7', ''],
            ['Treasurer', '37-8. ', '', ''],
            ['STREET 1', '38', '8', ''],
            ['STREET 2', '39', '8', ''],
            ['CITY', '40', '8', ''],
            ['STATE', '41', '8', ''],
            ['ZIP', '42', '8', ''],
            ['TITLE', '43', '8', ''],
            ['TELEPHONE', '44', '8', ''],
            ['Designated Agent', '45-8. ', '', ''],
            ['STREET 1', '46', '8', ''],
            ['STREET 2', '47', '8', ''],
            ['CITY', '48', '8', ''],
            ['STATE', '49', '8', ''],
            ['ZIP', '50', '8', ''],
            ['TITLE', '51', '8', ''],
            ['TELEPHONE', '52', '8', ''],
            ['Bank/Depository', '53-9. ', '', ''],
            ['STREET 1', '54', '9', ''],
            ['STREET 2', '55', '9', ''],
            ['CITY', '56', '9', ''],
            ['STATE', '57', '9', ''],
            ['ZIP', '58', '9', ''],
            ['NAME/TREASURER (as signed)', '59', '', ''],
            ['Signed', '60-', '', ''],
            ['COMMITTEE EMAIL', '61', '', ''],
            ['COMMITTEE WEB URL', '62', '', ''],
            ['COMMITTEE FAX NUMBER', '63', '', ''],
    ]
