class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['COMMITTEENAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['CHG OF ADDRESS', '9', '', ''],
            ['ACTIVITY PRIMARY', '10', '', ''],
            ['ACTIVITY GENERAL', '11', '', ''],
            ['RPTCODE', '12', '', ''],
            ['RPTPGI', '13', '', ''],
            ['Of Election', '14-', '', ''],
            ['STATE (Of Election)', '15', '', ''],
            ['Coverage From', '16-', '', ''],
            ['Coverage To', '17-', '', ''],
            ['Cash on Hand Beginning Period', '18', '6', ''],
            ['Total Receipts', '19', '7', ''],
            ['SubTotal', '20', '8', ''],
            ['Total Disbursements', '21', '9', ''],
            ['Cash on Hand Close of Period', '22', '10', ''],
            ['Debts to', '23', '11', ''],
            ['Debts by', '24', '12', ''],
            ['Expenditures Subject to Limits', '25', '13', ''],
            ['Net Contributions', '26', '14', ''],
            ['Net Operating Expenditures', '27', '15', ''],
            ['Federal Funds', '28', '16', ''],
            ['Individuals', '29', '17', 'a'],
            ['Political Party Committees', '30', '17', 'b'],
            ['Other Political Committees (PACs)', '31', '17', 'c'],
            ['The Candidate', '32', '17', 'd'],
            ['Total Contributions', '33', '17', 'e'],
            ['Transfers From Aff/Other Party Committees', '34', '18', ''],
            ['Received from or Guaranteed by Candidate', '35', '19', 'a'],
            ['Other Loans', '36', '19', 'b'],
            ['Total Loans', '37', '19', 'c'],
            ['Operating', '38', '20', 'a'],
            ['Fundraising', '39', '20', 'b'],
            ['Legal and Accounting', '40', '20', 'c'],
            ['Total offsets to Expenditures', '41', '20', 'd'],
            ['Other Receipts', '42', '21', ''],
            ['Total Receipts', '43', '22', ''],
            ['Operating Expenditures', '44', '23', ''],
            ['Transfers to Other Authorized Committees', '45', '24', ''],
            ['Fundraising Disbursements', '46', '25', ''],
            ['Exempt Legal and Accounting Disbursements', '47', '26', ''],
            ['Made or guaranteed by Candidate', '48', '27', 'a'],
            ['Other Repayments', '49', '27', 'b'],
            ['Total Loan Repayments Made', '50', '27', 'c'],
            ['Individuals', '51', '28', 'a'],
            ['Political Party Committees', '52', '28', 'b'],
            ['Other Political Committees', '53', '28', 'c'],
            ['Total Contributions Refunds', '54', '28', 'd'],
            ['Other Disbursements', '55', '29', ''],
            ['Total Disbursements', '56', '30', ''],
            ['Items on Hand to be Liquidated', '57', '31', ''],
            ['ALABAMA', '58', '', ''],
            ['ALASKA', '59', '', ''],
            ['ARIZONA', '60', '', ''],
            ['ARKANSAS', '61', '', ''],
            ['CALIFORNIA', '62', '', ''],
            ['COLORADO', '63', '', ''],
            ['CONNECTICUT', '64', '', ''],
            ['DELAWARE', '65', '', ''],
            ['DIST OF COLUMBIA', '66', '', ''],
            ['FLORIDA', '67', '', ''],
            ['GEORGIA', '68', '', ''],
            ['HAWAII', '69', '', ''],
            ['IDAHO', '70', '', ''],
            ['ILLINOIS', '71', '', ''],
            ['INDIANA', '72', '', ''],
            ['IOWA', '73', '', ''],
            ['KANSAS', '74', '', ''],
            ['KENTUCKY', '75', '', ''],
            ['LOUISIANA', '76', '', ''],
            ['MAINE', '77', '', ''],
            ['MARYLAND', '78', '', ''],
            ['MASSACHUSETTS', '79', '', ''],
            ['MICHIGAN', '80', '', ''],
            ['MINNESOTA', '81', '', ''],
            ['MISSISSIPPI', '82', '', ''],
            ['MISSOURI', '83', '', ''],
            ['MONTANA', '84', '', ''],
            ['NEBRASKA', '85', '', ''],
            ['NEVADA', '86', '', ''],
            ['NEW HAMPSHIRE', '87', '', ''],
            ['NEW JERSEY', '88', '', ''],
            ['NEW MEXICO', '89', '', ''],
            ['NEW YORK', '90', '', ''],
            ['NORTH CAROLINA', '91', '', ''],
            ['NORTH DAKOTA', '92', '', ''],
            ['OHIO', '93', '', ''],
            ['OKLAHOMA', '94', '', ''],
            ['OREGON', '95', '', ''],
            ['PENNSYLVANIA', '96', '', ''],
            ['RHODE ISLAND', '97', '', ''],
            ['SOUTH CAROLINA', '98', '', ''],
            ['SOUTH DAKOTA', '99', '', ''],
            ['TENNESSEE', '100', '', ''],
            ['TEXAS', '101', '', ''],
            ['UTAH', '102', '', ''],
            ['VERMONT', '103', '', ''],
            ['VIRGINIA', '104', '', ''],
            ['WASHINGTON', '105', '', ''],
            ['WEST VIRGINIA', '106', '', ''],
            ['WISCONSIN', '107', '', ''],
            ['WYOMING', '108', '', ''],
            ['PUERTO RICO', '109', '', ''],
            ['GUAM', '110', '', ''],
            ['VIRGIN ISLANDS', '111', '', ''],
            ['TOTALS', '112', '', ''],
            ['Federal Funds', '113', '16', ''],
            ['Individuals', '114', '17', 'a'],
            ['Political Party Committees', '115', '17', 'b'],
            ['Other Political Committees (PACs)', '116', '17', 'c'],
            ['The Candidate', '117', '17', 'd'],
            ['Total contributions (Other than Loans)', '118', '17', 'e'],
            ['Transfers From Aff/Other Party Committees', '119', '18', ''],
            ['Received from or Guaranteed by Candidate', '120', '19', 'a'],
            ['Other Loans', '121', '19', 'b'],
            ['Total Loans', '122', '19', 'c'],
            ['Operating', '123', '20', 'a'],
            ['Fundraising', '124', '20', 'b'],
            ['Legal and Accounting', '125', '20', 'c'],
            ['Total Offsets to Operating Expenditures', '126', '20', 'd'],
            ['Other Receipts', '127', '21', ''],
            ['Total Receipts', '128', '22', ''],
            ['Operating Expenditures', '129', '23', ''],
            ['Transfers to Other Authorized Committees', '130', '24', ''],
            ['Fundraising Disbursements', '131', '25', ''],
            ['Exempt Legal and Accounting Disbursements', '132', '26', ''],
            ['Made or Guaranteed by the Candidate', '133', '27', 'a'],
            ['Other Repayments', '134', '27', 'b'],
            ['Total Loan Repayments Made', '135', '27', 'c'],
            ['Individuals', '136', '28', 'a'],
            ['Political Party Committees', '137', '28', 'b'],
            ['Other Political Committees', '138', '28', 'c'],
            ['Total Contributions Refunds', '139', '28', 'd'],
            ['Other Disbursements', '140', '29', ''],
            ['Total Disbursements', '141', '30', ''],
            ['ALABAMA', '142', '', ''],
            ['ALASKA', '143', '', ''],
            ['ARIZONA', '144', '', ''],
            ['ARKANSAS', '145', '', ''],
            ['CALIFORNIA', '146', '', ''],
            ['COLORADO', '147', '', ''],
            ['CONNECTICUT', '148', '', ''],
            ['DELAWARE', '149', '', ''],
            ['DIST OF COLUMBIA', '150', '', ''],
            ['FLORIDA', '151', '', ''],
            ['GEORGIA', '152', '', ''],
            ['HAWAII', '153', '', ''],
            ['IDAHO', '154', '', ''],
            ['ILLINOIS', '155', '', ''],
            ['INDIANA', '156', '', ''],
            ['IOWA', '157', '', ''],
            ['KANSAS', '158', '', ''],
            ['KENTUCKY', '159', '', ''],
            ['LOUISIANA', '160', '', ''],
            ['MAINE', '161', '', ''],
            ['MARYLAND', '162', '', ''],
            ['MASSACHUSETTS', '163', '', ''],
            ['MICHIGAN', '164', '', ''],
            ['MINNESOTA', '165', '', ''],
            ['MISSISSIPPI', '166', '', ''],
            ['MISSOURI', '167', '', ''],
            ['MONTANA', '168', '', ''],
            ['NEBRASKA', '169', '', ''],
            ['NEVADA', '170', '', ''],
            ['NEW HAMPSHIRE', '171', '', ''],
            ['NEW JERSEY', '172', '', ''],
            ['NEW MEXICO', '173', '', ''],
            ['NEW YORK', '174', '', ''],
            ['NORTH CAROLINA', '175', '', ''],
            ['NORTH DAKOTA', '176', '', ''],
            ['OHIO', '177', '', ''],
            ['OKLAHOMA', '178', '', ''],
            ['OREGON', '179', '', ''],
            ['PENNSYLVANIA', '180', '', ''],
            ['RHODE ISLAND', '181', '', ''],
            ['SOUTH CAROLINA', '182', '', ''],
            ['SOUTH DAKOTA', '183', '', ''],
            ['TENNESSEE', '184', '', ''],
            ['TEXAS', '185', '', ''],
            ['UTAH', '186', '', ''],
            ['VERMONT', '187', '', ''],
            ['VIRGINIA', '188', '', ''],
            ['WASHINGTON', '189', '', ''],
            ['WEST VIRGINIA', '190', '', ''],
            ['WISCONSIN', '191', '', ''],
            ['WYOMING', '192', '', ''],
            ['PUERTO RICO', '193', '', ''],
            ['GUAM', '194', '', ''],
            ['VIRGIN ISLANDS', '195', '', ''],
            ['TOTALS', '196', '', ''],
            ['NAME/TREASURER (as signed)', '197', '', ''],
            ['Signed', '198-', '', ''],
    ]
