class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['Total Contributions (No Loans)', '3', '6a', ''],
            ['Total Contribution Refunds', '4', '6b', ''],
            ['Net Contributions', '5', '6c', ''],
            ['Total Operating Expenditures', '6', '7a', ''],
            ['Total Offsets to Operating Expenditures', '7', '7b', ''],
            ['NET Operating Expenditures.', '8', '7c', ''],
            ['Individuals Itemized', '9', '11', 'a.i'],
            ['Individuals Unitemized', '10', '11', 'a.ii'],
            ['Individuals Total', '11', '11', 'a.iii'],
            ['Political Party Committees', '12', '11', 'b'],
            ['All Other Political Committees (PACS)', '13', '11', 'c'],
            ['The Candidate', '14', '11', 'd'],
            ['Total Contributions', '15', '11', 'e'],
            ['Transfers From Other AUTH Committees', '16', '12', ''],
            ['Loans made or guarn. by the Candidate', '17', '13', 'a'],
            ['All Other Loans', '18', '13', 'b'],
            ['Total Loans', '19', '13', 'c'],
            ['Offsets to Operating Expenditures', '20', '14', ''],
            ['Other Receipts', '21', '15', ''],
            ['Total Receipts', '22', '16', ''],
            ['Operating Expenditures', '23', '17', ''],
            ['Transfers To Other AUTH Committees', '24', '18', ''],
            ['Loan Repayment By Candidate', '25', '19', 'a'],
            ['Loan Repayments, ALL Other Loans', '26', '19', 'b'],
            ['Total Loan Repayments', '27', '19', 'c'],
            ['Refund/Individuals Other than Political Committees', '28', '20', 'a'],
            ['Refund, Political Party Committees', '29', '20', 'b'],
            ['Refund, Other Political Committees', '30', '20', 'c'],
            ['Total Contributions Refunds', '31', '20', 'd'],
            ['Other Disbursements', '32', '21', ''],
            ['Total Disbursements', '33', '22', ''],
            ['Date - General Election', '34', '', ''],
            ['Date - Day after General Election', '35', '', ''],
    ]
