class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['CHG OF ADDRESS', '9', '', ''],
            ['Qual/Non Q', '10-', '', ''],
            ['INDEMP', '11', '', ''],
            ['INDOCC', '12', '', ''],
            ['RPTCODE', '13', '', ''],
            ['SPACE HOLDER', '14', '', ''],
            ['SPACE HOLDER', '15', '', ''],
            ['SPACE HOLDER', '16', '', ''],
            ['Coverage From', '17-', '', ''],
            ['Coverage To', '18-', '', ''],
            ['TOTAL CONTRIBUTION', '19', '', ''],
            ['TOTAL INDEP. EXPEND', '20', '', ''],
            ['Person Completing Form', '21-', '', ''],
            ['Signed', '22-', '', ''],
            ['SPACE HOLDER', '23', '', ''],
            ['SPACE HOLDER', '24', '', ''],
            ['SPACE HOLDER', '25', '', ''],
            ['HOUR 48HOUR CODE', '26', '24', ''],
    ]
