class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['CONTRIBUTOR NAME', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['ITEM ELECT CD', '10', '', ''],
            ['ITEM ELECT OTHER', '11', '', ''],
            ['INDEMP', '12', '', ''],
            ['INDOCC', '13', '', ''],
            ['AGGREGATE AMT Y-T-D', '14', '', ''],
            ['DATE RECEIVED', '15', '', ''],
            ['AMOUNT RECEIVED', '16', '', ''],
            ['TRANS CODE', '17', '', ''],
            ['SPACE HOLDER', '18', '', ''],
            ['SPACE HOLDER', '19', '', ''],
            ['SPACE HOLDER', '20', '', ''],
            ['SPACE HOLDER', '21', '', ''],
            ['SPACE HOLDER', '22', '', ''],
            ['SPACE HOLDER', '23', '', ''],
            ['SPACE HOLDER', '24', '', ''],
            ['SPACE HOLDER', '25', '', ''],
            ['SPACE HOLDER', '26', '', ''],
            ['SPACE HOLDER', '27', '', ''],
            ['SPACE HOLDER', '28', '', ''],
            ['SPACE HOLDER', '29', '', ''],
            ['SPACE HOLDER', '30', '', ''],
            ['SPACE HOLDER', '31', '', ''],
            ['SPACE HOLDER', '32', '', ''],
            ['SPACE HOLDER', '33', '', ''],
            ['TRAN ID', '34', '', ''],
            ['BACK REF TRAN ID', '35', '', ''],
            ['BACK REF SCHED NAME', '36', '', ''],
            ['SPACE HOLDER', '37', '', ''],
            ['SPACE HOLDER', '38', '', ''],
            ['CONTRIB ORGANIZATION NAME', '39', '', ''],
            ['CONTRIBUTOR LAST NAME', '40', '', ''],
            ['CONTRIBUTOR FIRST NAME', '41', '', ''],
            ['CONTRIBUTOR MIDDLE NAME', '42', '', ''],
            ['CONTRIBUTOR PREFIX', '43', '', ''],
            ['CONTRIBUTOR SUFFIX', '44', '', ''],
    ]
