class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['RECIPIENT NAME', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['TRANS Purpose CODE', '10', '', ''],
            ['TRANS Purpose DESCRIP', '11', '', ''],
            ['ITEM ELECT CD', '12', '', ''],
            ['ITEM ELECT OTHER', '13', '', ''],
            ['DATE OF EXPENDITURE', '14', '', ''],
            ['AMOUNT OF EXPENDITURE', '15', '', ''],
            ['SPACE HOLDER', '16', '', ''],
            ['SPACE HOLDER', '17', '', ''],
            ['SPACE HOLDER', '18', '', ''],
            ['SPACE HOLDER', '19', '', ''],
            ['SPACE HOLDER', '20', '', ''],
            ['SPACE HOLDER', '21', '', ''],
            ['SPACE HOLDER', '22', '', ''],
            ['SPACE HOLDER', '23', '', ''],
            ['SPACE HOLDER', '24', '', ''],
            ['SPACE HOLDER', '25', '', ''],
            ['SPACE HOLDER', '26', '', ''],
            ['SPACE HOLDER', '27', '', ''],
            ['SPACE HOLDER', '28', '', ''],
            ['SPACE HOLDER', '29', '', ''],
            ['SPACE HOLDER', '30', '', ''],
            ['TRAN ID', '31', '', ''],
            ['BACK REF TRAN ID', '32', '', ''],
            ['BACK REF SCHED NAME', '33', '', ''],
            ['SPACE HOLDER', '34', '', ''],
            ['SPACE HOLDER', '35', '', ''],
            ['CATEGORY CODE', '36', '', ''],
            ['COMMUNICATION DATE', '37', '', ''],
            ['RECIPIENT ORGANIZATION NAME', '38', '', ''],
            ['RECIPIENT LAST NAME', '39', '', ''],
            ['RECIPIENT FIRST NAME', '40', '', ''],
            ['RECIPIENT MIDDLE NAME', '41', '', ''],
            ['RECIPIENT PREFIX', '42', '', ''],
            ['RECIPIENT SUFFIX', '43', '', ''],
    ]
