class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['SPACE HOLDER', '3', '', ''],
            ['SPACE HOLDER', '4', '', ''],
            ['SPACE HOLDER', '5', '', ''],
            ['SPACE HOLDER', '6', '', ''],
            ['SPACE HOLDER', '7', '', ''],
            ['SPACE HOLDER', '8', '', ''],
            ['SPACE HOLDER', '9', '', ''],
            ['SPACE HOLDER', '10', '', ''],
            ['SPACE HOLDER', '11', '', ''],
            ['SPACE HOLDER', '12', '', ''],
            ['SPACE HOLDER', '13', '', ''],
            ['SPACE HOLDER', '14', '', ''],
            ['SPACE HOLDER', '15', '', ''],
            ['SPACE HOLDER', '16', '', ''],
            ['SPACE HOLDER', '17', '', ''],
            ['SPACE HOLDER', '18', '', ''],
            ['SPACE HOLDER', '19', '', ''],
            ['SPACE HOLDER', '20', '', ''],
            ['SPACE HOLDER', '21', '', ''],
            ['SPACE HOLDER', '22', '', ''],
            ['SPACE HOLDER', '23', '', ''],
            ['SPACE HOLDER', '24', '', ''],
            ['SPACE HOLDER', '25', '', ''],
            ['SPACE HOLDER', '26', '', ''],
            ['SPACE HOLDER', '27', '', ''],
            ['INTERNAL USE ONLY', '28', '', ''],
            ['TRAN ID', '29', '', ''],
            ['State and Local Party Committee Presidential-Only Election Year (28% Federal)', '30', '', ''],
            ['State and Local Party Committee Presidential and Senate Election Year (36% Federal)', '31', '', ''],
            ['State and Local Party Committee Senate-Only Election Year (21% Federal)', '32', '', ''],
            ['State and Local Party Committee Non-Presidential and Non-Senate Election Year (15% Federal)', '33', '', ''],
            ['FLAT MINIMUM FEDERAL PERCENTAGE', '34', '', ''],
            ['FEDERAL PERCENT', '35', '', ''],
            ['NONFEDERAL PERCENT', '36', '', ''],
            ['ADMINISTRATIVE RATIO APPLIES', '37', '', ''],
            ['GENERIC VOTER DRIVE RATIO APPLIES', '38', '', ''],
            ['PUBLIC COMMUNICATIONS REFERENCING PARTY ONLY RATIO APPLIES', '39', '', ''],
    ]
