class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['COMMITTEE TYPE', '9', '', ''],
            ['Of Affiliation', '10-', '', ''],
            ['FEC COMMITTEE ID NUMBER', '11', '', ''],
            ['COMMITTEE NAME', '12', '', ''],
            ['FEC CANDIDATE ID NUMBER', '13', '', ''],
            ['CANDIDATE NAME', '14', '', ''],
            ['CAN/OFF', '15', '', ''],
            ['STATE (Of Election)', '16', '', ''],
            ['CAN/DIST', '17', '', ''],
            ['Of Contribution', '18-', '', ''],
            ['FEC CANDIDATE ID NUMBER', '19', '', ''],
            ['CANDIDATE NAME', '20', '', ''],
            ['CAN/OFF', '21', '', ''],
            ['STATE (Of Election)', '22', '', ''],
            ['CAN/DIST', '23', '', ''],
            ['Of Contribution', '24-', '', ''],
            ['FEC CANDIDATE ID NUMBER', '25', '', ''],
            ['CANDIDATE NAME', '26', '', ''],
            ['CAN/OFF', '27', '', ''],
            ['STATE (Of Election)', '28', '', ''],
            ['CAN/DIST', '29', '', ''],
            ['Of Contribution', '30-', '', ''],
            ['FEC CANDIDATE ID NUMBER', '31', '', ''],
            ['CANDIDATE NAME', '32', '', ''],
            ['CAN/OFF', '33', '', ''],
            ['STATE (Of Election)', '34', '', ''],
            ['CAN/DIST', '35', '', ''],
            ['Of Contribution', '36-', '', ''],
            ['FEC CANDIDATE ID NUMBER', '37', '', ''],
            ['CANDIDATE NAME', '38', '', ''],
            ['CAN/OFF', '39', '', ''],
            ['STATE (Of Election)', '40', '', ''],
            ['CAN/DIST', '41', '', ''],
            ['Of Contribution', '42-', '', ''],
            ['Of 51st Contributor', '43-', '', ''],
            ['Of Orig Registration', '44-', '', ''],
            ['Cmte Met Requirements', '45-', '', ''],
            ['Treasurer', '46-', '', ''],
            ['Signed', '47-', '', ''],
    ]
