from fec.version.records_base import RecordsBase
class Records(RecordsBase):
    def __init__(self):
        RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER FEC CMTE ID', 'number': '2'},
            {'name': 'COMMITTEE NAME', 'number': '3'},
            {'name': 'STREET 1', 'number': '4'},
            {'name': 'STREET 2', 'number': '5'},
            {'name': 'CITY', 'number': '6'},
            {'name': 'STATE', 'number': '7'},
            {'name': 'ZIP', 'number': '8'},
            {'name': 'COMMITTEE TYPE', 'number': '9'},
            {'name': 'Of Affiliation', 'number': '10-'},
            {'name': 'FEC COMMITTEE ID NUMBER', 'number': '11'},
            {'name': 'COMMITTEE NAME', 'number': '12'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '13'},
            {'name': 'CANDIDATE NAME', 'number': '14'},
            {'name': 'CAN/OFF', 'number': '15'},
            {'name': 'STATE (Of Election)', 'number': '16'},
            {'name': 'CAN/DIST', 'number': '17'},
            {'name': 'Of Contribution', 'number': '18-'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '19'},
            {'name': 'CANDIDATE NAME', 'number': '20'},
            {'name': 'CAN/OFF', 'number': '21'},
            {'name': 'STATE (Of Election)', 'number': '22'},
            {'name': 'CAN/DIST', 'number': '23'},
            {'name': 'Of Contribution', 'number': '24-'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '25'},
            {'name': 'CANDIDATE NAME', 'number': '26'},
            {'name': 'CAN/OFF', 'number': '27'},
            {'name': 'STATE (Of Election)', 'number': '28'},
            {'name': 'CAN/DIST', 'number': '29'},
            {'name': 'Of Contribution', 'number': '30-'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '31'},
            {'name': 'CANDIDATE NAME', 'number': '32'},
            {'name': 'CAN/OFF', 'number': '33'},
            {'name': 'STATE (Of Election)', 'number': '34'},
            {'name': 'CAN/DIST', 'number': '35'},
            {'name': 'Of Contribution', 'number': '36-'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '37'},
            {'name': 'CANDIDATE NAME', 'number': '38'},
            {'name': 'CAN/OFF', 'number': '39'},
            {'name': 'STATE (Of Election)', 'number': '40'},
            {'name': 'CAN/DIST', 'number': '41'},
            {'name': 'Of Contribution', 'number': '42-'},
            {'name': 'Of 51st Contributor', 'number': '43-'},
            {'name': 'Of Orig Registration', 'number': '44-'},
            {'name': 'Cmte Met Requirements', 'number': '45-'},
            {'name': 'Treasurer', 'number': '46-'},
            {'name': 'Signed', 'number': '47-'},
    ]
        self.fields_names = self.hash_names(self.fields)
