class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET1', '4', '', ''],
            ['STREET2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['Net Operating Expenditures', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['CHG OF ADDRESS', '10', '', ''],
            ['ELECTION STATE', '11', '', ''],
            ['ELECTION DISTRICT', '12', '', ''],
            ['RPTCODE', '13', '', ''],
            ['RPTPGI', '14', '', ''],
            ['DATE(Of Election)', '15', '', ''],
            ['STATE (Of Election)', '16', '', ''],
            ['PRIMARY ELECTION', '17', '', ''],
            ['GENERAL ELECTION', '18', '', ''],
            ['SPECIAL ELECTION', '19', '', ''],
            ['RUNOFF ELECTION', '20', '', ''],
            ['Coverage From', '21-', '', ''],
            ['Coverage To', '22-', '', ''],
            ['Total Contributions (NO Loans)', '23', '6a', ''],
            ['Total Contribution Refunds', '24', '6b', ''],
            ['Net Contributions', '25', '6c', ''],
            ['Total Operating Expenditures', '26', '7a', ''],
            ['Total Offset to Operating Expenditures', '27', '7b', ''],
            ['NET Operating Expenditures', '28', '7c', ''],
            ['CASH ON HAND AT CLOSE OF REPORTING PD:', '29', '8', ''],
            ['DEBTS TO ( Totals from SCH C and/or D)', '30', '9', ''],
            ['DEBTS BY (Totals from SCH C and/or D)', '31', '10', ''],
            ['Individuals Itemized', '32', '11', 'a i'],
            ['Individuals Unitemized', '33', '11', 'aii'],
            ['Individual Contribution Total', '34', '11', 'aiii'],
            ['Political Party Committees', '35', '11', 'b'],
            ['Other Political Committees', '36', '11', 'c'],
            ['The Candidate', '37', '11', 'd'],
            ['Total Contributions', '38', '11', 'e'],
            ['TransfersFrom Other Authorized Committees', '39', '12', ''],
            ['Loans made or guarnby the Candidate', '40', '13', 'a'],
            ['All Other Loans', '41', '13', 'b'],
            ['Total Loans', '42', '13', 'c'],
            ['Offsets to Operating Expenditures', '43', '14', ''],
            ['Other Receipts', '44', '15', ''],
            ['Total Receipts', '45', '16', ''],
            ['Operating Expenditures', '46', '17', ''],
            ['Transfers to Other Authorized Committees', '47', '18', ''],
            ['Of Loans made or guarby the Candidate', '48', '19', 'a'],
            ['Loan Repayments, All Other Loans', '49', '19', 'b'],
            ['Total Loan Repayments', '50', '19', 'c'],
            ['Refund/Individuals Other than Political Committees', '51', '20', 'a'],
            ['Refund/Political Party Committees', '52', '20', 'b'],
            ['Refund/Other Political Committees', '53', '20', 'c'],
            ['Total Contribution Refunds', '54', '20', 'd'],
            ['Other Disbursements', '55', '21', ''],
            ['Total Disbursements', '56', '22', ''],
            ['Cash Beginning Reporting Period', '57', '23', ''],
            ['Total Receipts this Period', '58', '24', ''],
            ['SubTotal)', '59', '25', ''],
            ['Total Disbursements this Period', '60', '26', ''],
            ['Cash on hand at Close Period', '61', '27', ''],
            ['Total Contributions (No Loans)', '62', '6a', ''],
            ['Total Contribution Refunds', '63', '6b', ''],
            ['Net Contributions', '64', '6c', ''],
            ['Total Operating Expenditures', '65', '7a', ''],
            ['Total Offsets to Operating Expenditures', '66', '7b', ''],
            ['NET Operating Expenditures', '67', '7c', ''],
            ['Individuals Itemized', '68', '11', 'ai'],
            ['Individuals Unitemized', '69', '11', 'aii'],
            ['Individuals Total', '70', '11', 'aiii'],
            ['Political Party Committees', '71', '11', 'b'],
            ['All Other Political Committees (PACS)', '72', '11', 'c'],
            ['The Candidate', '73', '11', 'd'],
            ['Total Contributions', '74', '11', 'e'],
            ['Transfers From Other AUTH Committees', '75', '12', ''],
            ['Loans made or guarnby the Candidate', '76', '13', 'a'],
            ['All Other Loans', '77', '13', 'b'],
            ['Total Loans', '78', '13', 'c'],
            ['Offsets to Operating Expenditures', '79', '14', ''],
            ['Other Receipts', '80', '15', ''],
            ['Total Receipts', '81', '16', ''],
            ['Operating Expenditures', '82', '17', ''],
            ['Transfers To Other AUTH Committees', '83', '18', ''],
            ['Loan Repayment By Candidate', '84', '19', 'a'],
            ['Loan Repayments,ALL Other Loans', '85', '19', 'b'],
            ['Total Loan Repayments', '86', '19', 'c'],
            ['Refund/Individuals Other than Political Committees', '87', '20', 'a'],
            ['Refund, Political Party Committees', '88', '20', 'b'],
            ['Refund, Other Political Committees', '89', '20', 'c'],
            ['Total Contributions Refunds', '90', '20', 'd'],
            ['Other Disbursements', '91', '21', ''],
            ['Total Disbursements', '92', '22', ''],
            ['Treasurer', '93-', '', ''],
            ['Signed', '94-', '', ''],
    ]
