class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['CHG OF ADDRESS', '9', '', ''],
            ['QUALIFIED CMTE', '10', '', ''],
            ['RPTCODE', '11', '', ''],
            ['RPTPGI', '12', '', ''],
            ['OF ELECTION', '13-', '', ''],
            ['STATE (OF ELECTION)', '14', '', ''],
            ['COVERAGE FROM', '15-', '', ''],
            ['COVERAGE TO', '16-', '', ''],
            ['Cash on Hand beginning', '17', '6', 'b'],
            ['total receipts', '18', '6', 'c'],
            ['subtotal', '19', '6', 'd'],
            ['total disbursements', '20', '7', ''],
            ['Cash on Hand at Close', '21', '8', ''],
            ['Debts to', '22', '9', ''],
            ['Debts by', '23', '10', ''],
            ['itemized', '24', '11', '(a)i'],
            ['unitemized', '25', '11', '(a)ii'],
            ['total', '26', '11', '(a)iii'],
            ['Political party committees', '27', '11', 'b'],
            ['Other Political Committees (PACs)', '28', '11', 'c'],
            ['total contributions', '29', '11', 'd'],
            ['Transfers from Affiliated/Other Party Committees', '30', '12', ''],
            ['All loans Received', '31', '13', ''],
            ['loan repayments received', '32', '14', ''],
            ['offsets to Operating Expenditures (refunds)', '33', '15', ''],
            ['Refunds of Federal contributions', '34', '16', ''],
            ['Other Federal Receipts (dividends)', '35', '17', ''],
            ['transfers from Nonfederal Account', '36', '18', ''],
            ['Total Receipts', '37', '19', ''],
            ['Total Federal Receipts', '38', '20', ''],
            ['Federal Share', '39', '21', '(a)i'],
            ['non-federal share', '40', '21', '(a)ii'],
            ['other Federal operating expenditures', '41', '21', 'b'],
            ['total operating expenditures', '42', '21', 'c'],
            ['Transfers to Affiliated/Other Party Committees', '43', '22', ''],
            ['Contributions to Federal Candidates/Committees', '44', '23', ''],
            ['Independent expenditures', '45', '24', ''],
            ['Coordinated Expenditures made by party Committees', '46', '25', ''],
            ['Loan repayments', '47', '26', ''],
            ['Loans Made', '48', '27', ''],
            ['Individuals/Persons', '49', '28', 'a'],
            ['Political Party Committees', '50', '28', 'b'],
            ['Other Political Committees', '51', '28', 'c'],
            ['Total contributions refunds', '52', '28', 'd'],
            ['Other disbursements', '53', '29', ''],
            ['Total disbursements', '54', '30', ''],
            ['Total Federal Disbursements', '55', '31', ''],
            ['Total contributions', '56', '32', ''],
            ['Total Contribution Refunds', '57', '33', ''],
            ['Net Contributions', '58', '34', ''],
            ['Total Federal Operating Expenditures', '59', '35', ''],
            ['Offsets to operating Expenditures', '60', '36', ''],
            ['Net operating Expenditures', '61', '37', ''],
            ['cash on hand Jan 1, 19', '62', '6', 'a'],
            ['Year for above', '63', '', ''],
            ['total receipts', '64', '6', 'c'],
            ['subtotal', '65', '6', 'd'],
            ['Total disbursements', '66', '7', ''],
            ['Cash on Hand Close', '67', '8', ''],
            ['itemized', '68', '11', '(a)i'],
            ['unitemized', '69', '11', '(a)ii'],
            ['Total', '70', '11', '(a)iii'],
            ['Political Party committees', '71', '11', 'b'],
            ['Other Political Committees (PACs)', '72', '11', 'c'],
            ['Total contributions', '73', '11', 'd'],
            ['Transfers from Affiliated/Other Party Committees', '74', '12', ''],
            ['All loans Received', '75', '13', ''],
            ['loan repayments received', '76', '14', ''],
            ['offsets to Operating Expenditures (refunds)', '77', '15', ''],
            ['Refunds of Federal contributions', '78', '16', ''],
            ['Other Federal Receipts (dividends)', '79', '17', ''],
            ['transfers from Nonfederal Account', '80', '18', ''],
            ['Total receipts', '81', '19', ''],
            ['Total federal receipts', '82', '20', ''],
            ['Federal Share', '83', '21', '(a)i'],
            ['non-federal share', '84', '21', '(a)ii'],
            ['other Federal operating expenditures', '85', '21', 'b'],
            ['Total operating Expenditures', '86', '21', 'c'],
            ['Transfers to Affiliated/Other Party Committees', '87', '22', ''],
            ['Contributions to Federal Candidates/Committees', '88', '23', ''],
            ['Independent Expenditures', '89', '24', ''],
            ['Coordinated Expenditures made by party Committees', '90', '25', ''],
            ['Loan repayments Made', '91', '26', ''],
            ['Loans Made', '92', '27', ''],
            ['individuals/Persons', '93', '28', 'a'],
            ['Political Party Committees', '94', '28', 'b'],
            ['Other Political Committees', '95', '28', 'c'],
            ['Total contributions refunds', '96', '28', 'd'],
            ['Other Disbursements', '97', '29', ''],
            ['Total Disbursements', '98', '30', ''],
            ['Total Federal Disbursements', '99', '31', ''],
            ['Total Contributions', '100', '32', ''],
            ['Total Contribution Refunds', '101', '33', ''],
            ['Net contributions', '102', '34', ''],
            ['Total Federal Operating Expenditures', '103', '35', ''],
            ['Offsets to Operating Expenditures', '104', '36', ''],
            ['Net Operating Expenditures', '105', '37', ''],
            ['Treasurer', '106-', '', ''],
            ['Signed', '107-', '', ''],
    ]
