class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['CHG OF ADDRESS', '9', '', ''],
            ['QUAL/NON-Q', '10-', '', ''],
            ['INDEMP', '11', '', ''],
            ['INDOCC', '12', '', ''],
            ['RPTCODE', '13', '', ''],
            ['RPTPGI', '14', '', ''],
            ['OF ELECTION', '15-', '', ''],
            ['STATE (OF ELECTION)', '16', '', ''],
            ['COVERAGE FROM', '17-', '', ''],
            ['COVERAGE TO', '18-', '', ''],
            ['TOTAL CONTRIBUTION', '19', '', ''],
            ['TOTAL INDEP EXPEND', '20', '', ''],
            ['PERSON COMPLETING FORM', '21-', '', ''],
            ['SIGNED', '22-', '', ''],
            ['NOTARIZED', '23-', '', ''],
            ['NOTARY COMMISSION EXPIRES', '24-', '', ''],
            ['NOTARY', '25-', '', ''],
    ]
