class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['NAME(Contributor/Lender)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['INDEMP', '10', '', ''],
            ['INDOCC', '11', '', ''],
            ['OF CONTRIBUTION', '12-', '', ''],
            ['AMOUNT CONTRIBUTION AMOUNT', '13', '', ''],
            ['FEC-COMMITTEE-ID-NUMBER', '14', '', ''],
            ['FEC-CANDIDATE-ID-NUMBER', '15', '', ''],
            ['CANDIDATE-NAME', '16', '', ''],
            ['CAND-OFFICE', '17', '', ''],
            ['CAND-STATE (OF ELECTION)', '18', '', ''],
            ['CAND-DISTRICT', '19', '', ''],
            ['CONDUIT-NAME', '20', '', ''],
            ['CONDUIT-STREET-1', '21', '', ''],
            ['CONDUIT-STREET-2', '22', '', ''],
            ['CONDUIT-CITY', '23', '', ''],
            ['CONDUIT-STATE', '24', '', ''],
            ['CONDUIT-ZIP', '25', '', ''],
            ['AMENDED-CD', '26', '', ''],
            ['TRAN_ID', '27', '', ''],
            ['ORIG_TRAN_ID', '28', '', ''],
            ['SUPR_TRAN_ID', '29', '', ''],
    ]
