class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['NAME (Payee)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['TRANSDESC', '10', '', ''],
            ['OF EXPENDITURE', '11-', '', ''],
            ['AMOUNT CONTRIBUTION AMOUNT', '12', '', ''],
            ['SUPPORT/OPPOSE', '13', '', ''],
            ['S/O FEC CAN ID NUMBER', '14', '', ''],
            ['S/O CAN/NAME', '15', '', ''],
            ['S/O CAN/OFF', '16', '', ''],
            ['S/O STATE', '17', '', ''],
            ['S/O CAN/DIST', '18', '', ''],
            ['FEC-COMMITTEE-ID-NUMBER', '19', '', ''],
            ['FEC-CANDIDATE-ID-NUMBER', '20', '', ''],
            ['CANDIDATE-NAME', '21', '', ''],
            ['CAND-OFFICE', '22', '', ''],
            ['CAND-STATE (OF ELECTION)', '23', '', ''],
            ['CAND-DISTRICT', '24', '', ''],
            ['CONDUIT-NAME', '25', '', ''],
            ['CONDUIT-STREET-1', '26', '', ''],
            ['CONDUIT-STREET-2', '27', '', ''],
            ['CONDUIT-CITY', '28', '', ''],
            ['CONDUIT-STATE', '29', '', ''],
            ['CONDUIT-ZIP', '30', '', ''],
            ['AMENDED-CD', '31', '', ''],
            ['TRAN_ID', '32', '', ''],
            ['ORIG_TRAN_ID', '33', '', ''],
            ['SUPR_TRAN_ID', '34', '', ''],
    ]
