class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['CREDITOR CODE', '3', '', ''],
            ['NAME (Contributor/Lender)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['INCURRED', '10-', '', ''],
            ['AMOUNT OWED TO CREDITOR', '11', '', ''],
            ['AMOUNT OFFERED IN SETTLEMENT', '12', '', ''],
            ['INITIAL TERMS AND NATURE OF DEBT', '13-A ', '', ''],
            ['EFFORTS MADE BY CMTE TO PAY DEBT', '14-B ', '', ''],
            ['STEPS TAKEN BY CREDITOR TO COLLECT', '15-C ', '', ''],
            ['WAS THE effort made BY creditor to collect similar to other debt collection efforts', '16-D ', '', ''],
            ['N IF NO EXPLAIN', '17-D ', '', ''],
            ['Are the terms of the debt settlement comparable to other settlements', '18-E ', '', ''],
            ['N IF NO EXPLAIN', '19-E ', '', ''],
            ['FEC-COMMITTEE-ID-NUMBER', '20', '', ''],
            ['FEC-CANDIDATE-ID-NUMBER', '21', '', ''],
            ['CANDIDATE-NAME', '22', '', ''],
            ['CAND-OFFICE', '23', '', ''],
            ['CAND-STATE (OF ELECTION)', '24', '', ''],
            ['CAND-DISTRICT', '25', '', ''],
            ['NAME of creditor or representative', '26', '', ''],
            ['SIGNED', '27-', '', ''],
            ['AMENDED-CD', '28', '', ''],
            ['TRAN_ID', '29', '', ''],
            ['ORIG_TRAN_ID', '30', '', ''],
            ['SUPR_TRAN_ID', '31', '', ''],
    ]
