class Records:
    def __init__(self):
        self.fields = [
            ['FORM-TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY-TYPE', '3', '', ''],
            ['CONTRIBUTOR-NAME', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['ITEM-ELECT-CD', '10', '', ''],
            ['ITEM-ELECT-OTHER', '11', '', ''],
            ['IND-EMPLOYER', '12', '', ''],
            ['IND-OCCUP', '13', '', ''],
            ['AGGREGATE-AMT-YTD', '14', '', ''],
            ['DATE-RECEIVED', '15', '', ''],
            ['AMOUNT-RECEIVED', '16', '', ''],
            ['TRANS-CODE', '17', '', ''],
            ['TRANS-DESCRIP', '18', '', ''],
            ['FEC-COMMITTEE-ID-NUMBER', '19', '', ''],
            ['FEC-CANDIDATE-ID-NUMBER', '20', '', ''],
            ['CANDIDATE-NAME', '21', '', ''],
            ['CAND-OFFICE', '22', '', ''],
            ['CAND-STATE (OF ELECTION)', '23', '', ''],
            ['CAND-DISTRICT', '24', '', ''],
            ['CONDUIT-NAME', '25', '', ''],
            ['CONDUIT-STREET-1', '26', '', ''],
            ['CONDUIT-STREET-2', '27', '', ''],
            ['CONDUIT-CITY', '28', '', ''],
            ['CONDUIT-STATE', '29', '', ''],
            ['CONDUIT-ZIP', '30', '', ''],
            ['MEMO-CODE', '31', '', ''],
            ['MEMO-TEXT', '32', '', ''],
            ['AMENDED-CD', '33', '', ''],
            ['TRAN-ID', '34', '', ''],
            ['ORIG-TRAN-ID', '35', '', ''],
            ['SUPR-TRAN-ID', '36', '', ''],
    ]
