class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['NAME (Loan Source)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['ELECTION', '10', '', ''],
            ['ELECTION DESCRIPTION', '11', '', ''],
            ['ORIG AMT OF LOAN AMOUNT', '12', '', ''],
            ['PAYMENT TO DATE', '13', '', ''],
            ['LOAN BALANCE', '14', '', ''],
            ['INCURRED', '15-', '', ''],
            ['DUE-DATE-TERMS', '16', '', ''],
            ['PCT-RATE-TERMS', '17', '', ''],
            ['SECURED LOAN', '18-', '', ''],
            ['FEC-COMMITTEE-ID-NUMBER', '19', '', ''],
            ['FEC-CANDIDATE-ID-NUMBER', '20', '', ''],
            ['CANDIDATE-NAME', '21', '', ''],
            ['CAND-OFFICE', '22', '', ''],
            ['CAND-STATE (OF ELECTION)', '23', '', ''],
            ['CAND-DISTRICT', '24', '', ''],
            ['AMENDED-CD', '25', '', ''],
            ['TRAN_ID', '26', '', ''],
            ['ORIG_TRAN_ID', '27', '', ''],
            ['SUPR_TRAN_ID', '28', '', ''],
    ]
