class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['BACK REFERENCE TRAN ID', '3', '', ''],
            ['ENTITY TYPE', '4', '', ''],
            ['NAME (Loan Source)', '5', '', ''],
            ['STREET 1', '6', '', ''],
            ['STREET 2', '7', '', ''],
            ['CITY', '8', '', ''],
            ['STATE', '9', '', ''],
            ['ZIP', '10', '', ''],
            ['AMT OF LOAN', '11', '', ''],
            ['LOAN INTEREST RATE PERCENT', '12', '', ''],
            ['INCURRED', '13-', '', ''],
            ['DUE', '14-', '', ''],
            ['LOAN RESTRUCTURED', '15-A1 ', '', ''],
            ['OF ORIGINAL LOAN', '16-A2 ', '', ''],
            ['CREDIT AMOUNT THIS DRAW', '17-B1', '', ''],
            ['TOTAL BALANCE', '18-B2', '', ''],
            ['OTHERS LIABLE?', '19-C ', '', ''],
            ['COLLATERAL?', '20-D ', '', ''],
            ['DESC (COLLATERAL', '21-D 1', '', ''],
            ['COLLATERAL VALUE/AMOUNT', '22-D 2', '', ''],
            ['PERFECTED INTEREST?', '23-D 3 ', '', ''],
            ['FUTURE INCOME PLEDGED AS COLLATERAL?', '24-E 1 ', '', ''],
            ['SPECIFICATION OF THE ABOVE', '25-E 2 ', '', ''],
            ['ESTIMATED VALUE', '26-E 3', '', ''],
            ['Depository account established', '27-E 4 ', '', ''],
            ['Account Location', '28-E 5 ', '', ''],
            ['STREET 1', '29-E 6', '', ''],
            ['STREET 2', '30-E 7', '', ''],
            ['CITY', '31-E 8', '', ''],
            ['STATE', '32-E 9', '', ''],
            ['ZIP', '33-E 10', '', ''],
            ['Presidential', '34-E 11 DEP ACCT AUTH ', '', ''],
            ['IF NECESS STATE BASIS OF LOAN', '35-F ', '', ''],
            ['Treasurer', '36-G ', '', ''],
            ['SIGNED', '37-G ', '', ''],
            ['AUTH NAME (Lending Inst Rep)', '38', 'H', ''],
            ['AUTH TITLE (Lending Inst Representative)', '39', 'H', ''],
    ]
