class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY-TYPE', '3', '', ''],
            ['NAME (Debtor/Creditor)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['NATURE/PURPOSE DEBT DESCRIPTION', '10', '', ''],
            ['BEGINNING BALANCE', '11', '', ''],
            ['INCURRED THIS PERIOD', '12', '', ''],
            ['PAYMENT THIS PERIOD', '13', '', ''],
            ['BALANCE AT CLOSE', '14', '', ''],
            ['FEC-COMMITTEE-ID-NUMBER', '15', '', ''],
            ['FEC-CANDIDATE-ID-NUMBER', '16', '', ''],
            ['CANDIDATE-NAME', '17', '', ''],
            ['CAND-OFFICE', '18', '', ''],
            ['CAND-STATE (OF ELECTION)', '19', '', ''],
            ['CAND-DISTRICT', '20', '', ''],
            ['CONDUIT-NAME', '21', '', ''],
            ['CONDUIT-STREET-1', '22', '', ''],
            ['CONDUIT-STREET-2', '23', '', ''],
            ['CONDUIT-CITY', '24', '', ''],
            ['CONDUIT-STATE', '25', '', ''],
            ['CONDUIT-ZIP', '26', '', ''],
            ['AMENDED-CD', '27', '', ''],
            ['TRAN_ID', '28', '', ''],
            ['ORIG_TRAN_ID', '29', '', ''],
            ['SUPR_TRAN_ID', '30', '', ''],
    ]
