class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY_TYPE', '3', '', ''],
            ['NAME (Payee)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['TRANSDESC', '10', '', ''],
            ['DATE', '11', '', ''],
            ['AMOUNT EXPENDED', '12', '', ''],
            ['SUPPORT/OPPOSE', '13', '', ''],
            ['S/O FEC CAN ID NUMBER', '14', '', ''],
            ['S/O CAN/NAME', '15', '', ''],
            ['S/O CAN/OFF', '16', '', ''],
            ['S/O STATE', '17', '', ''],
            ['S/O CAN/DIST', '18', '', ''],
            ['FEC COMMITTEE ID NUMBER', '19', '', ''],
            ['FEC CANDIDATE ID NUMBER', '20', '', ''],
            ['CANDIDATE NAME', '21', '', ''],
            ['CAN/OFF', '22', '', ''],
            ['STATE (OF ELECTION)', '23', '', ''],
            ['CAN/DIST', '24', '', ''],
            ['CONDUIT-NAME', '25', '', ''],
            ['CONDUIT-STREET-1', '26', '', ''],
            ['CONDUIT-STREET-2', '27', '', ''],
            ['CONDUIT-CITY', '28', '', ''],
            ['CONDUIT-STATE', '29', '', ''],
            ['CONDUIT-ZIP', '30', '', ''],
            ['Person Completing Form', '31-', '', ''],
            ['SIGNED', '32-', '', ''],
            ['NOTARIZED', '33-', '', ''],
            ['NOTARY COMMISSION EXPIRES', '34-', '', ''],
            ['NOTARY', '35-', '', ''],
            ['AMENDED-CD', '36', '', ''],
            ['TRAN_ID', '37', '', ''],
            ['ORIG_TRAN_ID', '38', '', ''],
            ['SUPR_TRAN_ID', '39', '', ''],
    ]
