from fec.version.records_base import RecordsBase
class Records(RecordsBase):
    def __init__(self):
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER FEC CMTE ID', 'number': '2'},
            {'name': 'HAS FILER BEEN DESIG TO MAKE CORD. EXPEND.', 'number': '3-'},
            {'name': 'FEC COMMITTEE ID NUMBER', 'number': '4'},
            {'name': 'DESIGNATING COMMITTEES. COMMITTEE NAME', 'number': '5'},
            {'name': 'FEC COMMITTEE ID NUMBER SUBORDINATE CMTE', 'number': '6'},
            {'name': 'COMMITTEE NAME', 'number': '7'},
            {'name': 'STREET 1', 'number': '8'},
            {'name': 'STREET 2', 'number': '9'},
            {'name': 'CITY', 'number': '10'},
            {'name': 'STATE', 'number': '11'},
            {'name': 'ZIP', 'number': '12'},
            {'name': 'ENTITY TYPE', 'number': '13'},
            {'name': 'NAME (Payee)', 'number': '14'},
            {'name': 'STREET 1', 'number': '15'},
            {'name': 'STREET 2', 'number': '16'},
            {'name': 'CITY', 'number': '17'},
            {'name': 'STATE', 'number': '18'},
            {'name': 'ZIP', 'number': '19'},
            {'name': 'AGG GEN ELE AMOUNT EXPENDED', 'number': '20'},
            {'name': 'TRANSDESC', 'number': '21'},
            {'name': 'DATE', 'number': '22'},
            {'name': 'AMOUNT EXPENDED', 'number': '23'},
            {'name': 'FEC COMMITTEE ID NUMBER', 'number': '24'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '25'},
            {'name': 'CANDIDATE NAME', 'number': '26'},
            {'name': 'CAN/OFF', 'number': '27'},
            {'name': 'STATE (OF ELECTION)', 'number': '28'},
            {'name': 'CAN/DIST', 'number': '29'},
            {'name': 'CONDUIT-NAME', 'number': '30'},
            {'name': 'CONDUIT-STREET-1', 'number': '31'},
            {'name': 'CONDUIT-STREET-2', 'number': '32'},
            {'name': 'CONDUIT-CITY', 'number': '33'},
            {'name': 'CONDUIT-STATE', 'number': '34'},
            {'name': 'CONDUIT-ZIP', 'number': '35'},
            {'name': 'AMENDED-CD', 'number': '36'},
            {'name': 'TRAN_ID', 'number': '37'},
            {'name': 'ORIG_TRAN_ID', 'number': '38'},
            {'name': 'SUPR_TRAN_ID', 'number': '39'},
    ]
