class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['HAS FILER BEEN DESIG TO MAKE CORD. EXPEND.', '3-', '', ''],
            ['FEC COMMITTEE ID NUMBER', '4', '', ''],
            ['DESIGNATING COMMITTEES. COMMITTEE NAME', '5', '', ''],
            ['FEC COMMITTEE ID NUMBER SUBORDINATE CMTE', '6', '', ''],
            ['COMMITTEE NAME', '7', '', ''],
            ['STREET 1', '8', '', ''],
            ['STREET 2', '9', '', ''],
            ['CITY', '10', '', ''],
            ['STATE', '11', '', ''],
            ['ZIP', '12', '', ''],
            ['ENTITY TYPE', '13', '', ''],
            ['NAME (Payee)', '14', '', ''],
            ['STREET 1', '15', '', ''],
            ['STREET 2', '16', '', ''],
            ['CITY', '17', '', ''],
            ['STATE', '18', '', ''],
            ['ZIP', '19', '', ''],
            ['AGG GEN ELE AMOUNT EXPENDED', '20', '', ''],
            ['TRANSDESC', '21', '', ''],
            ['DATE', '22', '', ''],
            ['AMOUNT EXPENDED', '23', '', ''],
            ['FEC COMMITTEE ID NUMBER', '24', '', ''],
            ['FEC CANDIDATE ID NUMBER', '25', '', ''],
            ['CANDIDATE NAME', '26', '', ''],
            ['CAN/OFF', '27', '', ''],
            ['STATE (OF ELECTION)', '28', '', ''],
            ['CAN/DIST', '29', '', ''],
            ['CONDUIT-NAME', '30', '', ''],
            ['CONDUIT-STREET-1', '31', '', ''],
            ['CONDUIT-STREET-2', '32', '', ''],
            ['CONDUIT-CITY', '33', '', ''],
            ['CONDUIT-STATE', '34', '', ''],
            ['CONDUIT-ZIP', '35', '', ''],
            ['AMENDED-CD', '36', '', ''],
            ['TRAN_ID', '37', '', ''],
            ['ORIG_TRAN_ID', '38', '', ''],
            ['SUPR_TRAN_ID', '39', '', ''],
    ]
