class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['NAT PARTY COMMITTEES %', '3', '', ''],
            ['HSE/SEN PTY COMMITTEES', '4', '', ''],
            ['HSE/SEN PTY COMMITTEES PERCENTAGE', '5', '', ''],
            ['HSE/SEN PTY COMMITTEES PERCENTAGE', '6', '', ''],
            ['HSE/SEN PTY COMMITTEES', '7', '', ''],
            ['HSE/SEN PTY COMMITTEES', '8', '', ''],
            ['HSE/SEN PTY COMMITTEES PERCENTAGE', '9', '', ''],
            ['SEP. SEG FUNDS & PERCENTAGE', '10', '', ''],
            ['SEP. SEG FUNDS & PERCENTAGE', '11', '', ''],
            ['SEP. SEG FUNDS &', '12', '', ''],
            ['SEP. SEG FUNDS &', '13', '', ''],
            ['SEP. SEG FUNDS & PERCENTAGE', '14', '', ''],
            ['BALLOT COMP PRES BLANK OR 1', '15', '1', ''],
            ['BALLOT COMP SEN BLANK OR 1', '16', '2', ''],
            ['BALLOT COMP HSE BLANK OR 1', '17', '3', ''],
            ['SUBTOTAL-FED', '18', '4', ''],
            ['BALLOT COMP GOV BLANK OR 1', '19', '5', ''],
            ['OTHER STATEWIDE', '20', '6', ''],
            ['STATE SENATE', '21', '7', ''],
            ['STATE REP.', '22', '8', ''],
            ['LOCAL CANDIDATES BLANK, 1 OR 2', '23', '9', ''],
            ['EXTRA NON-FED POINT BLANK OR 1', '24', '10', ''],
            ['SUBTOTAL', '25', '11', ''],
            ['TOTAL POINTS', '26', '12', ''],
            ['FEDERAL ALLOCATION PERCENTAGE', '27', '', ''],
            ['AMENDED-CD', '28', '', ''],
            ['TRAN_ID', '29', '', ''],
            ['ORIG_TRAN_ID', '30', '', ''],
            ['SUPR_TRAN_ID', '31', '', ''],
    ]
