from fec.version.records_base import RecordsBase
class Records(RecordsBase):
    def __init__(self):
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER FEC CMTE ID', 'number': '2'},
            {'name': 'ENTITY_TYPE', 'number': '3'},
            {'name': 'NAME (Payee)', 'number': '4'},
            {'name': 'STREET 1', 'number': '5'},
            {'name': 'STREET 2', 'number': '6'},
            {'name': 'CITY', 'number': '7'},
            {'name': 'STATE', 'number': '8'},
            {'name': 'ZIP', 'number': '9'},
            {'name': 'PURPOSE/EVENT', 'number': '10'},
            {'name': 'DATE', 'number': '11'},
            {'name': 'TOTAL AMOUNT', 'number': '12'},
            {'name': 'FEDERAL SHARE', 'number': '13'},
            {'name': 'NON-FEDERAL SHARE', 'number': '14'},
            {'name': 'ACTIVITY IS ADMIN/VOTER DRIVE', 'number': '15-'},
            {'name': 'ACTIVITY IS FUNDRAISING', 'number': '16-'},
            {'name': 'ACTIVITY IS EXEMPT', 'number': '17-'},
            {'name': 'ACT DIRECT CAN SUPPORT', 'number': '18-'},
            {'name': 'EVENT YEAR-TO-DATE', 'number': '19'},
            {'name': 'ADDITIONAL DESCRIPTION', 'number': '20'},
            {'name': 'FEC COMMITTEE ID NUMBER', 'number': '21'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '22'},
            {'name': 'CANDIDATE NAME', 'number': '23'},
            {'name': 'CAN/OFF', 'number': '24'},
            {'name': 'STATE (OF ELECTION)', 'number': '25'},
            {'name': 'CAN/DIST', 'number': '26'},
            {'name': 'CONDUIT-NAME', 'number': '27'},
            {'name': 'CONDUIT-STREET-1', 'number': '28'},
            {'name': 'CONDUIT-STREET-2', 'number': '29'},
            {'name': 'CONDUIT-CITY', 'number': '30'},
            {'name': 'CONDUIT-STATE', 'number': '31'},
            {'name': 'CONDUIT-ZIP', 'number': '32'},
            {'name': 'AMENDED-CD', 'number': '33'},
            {'name': 'TRAN_ID', 'number': '34'},
            {'name': 'ORIG_TRAN_ID', 'number': '35'},
            {'name': 'SUPR_TRAN_ID', 'number': '36'},
    ]
