class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER FEC CMTE ID', '2', '', ''],
            ['ENTITY_TYPE', '3', '', ''],
            ['NAME (Payee)', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['PURPOSE/EVENT', '10', '', ''],
            ['DATE', '11', '', ''],
            ['TOTAL AMOUNT', '12', '', ''],
            ['FEDERAL SHARE', '13', '', ''],
            ['NON-FEDERAL SHARE', '14', '', ''],
            ['ACTIVITY IS ADMIN/VOTER DRIVE', '15-', '', ''],
            ['ACTIVITY IS FUNDRAISING', '16-', '', ''],
            ['ACTIVITY IS EXEMPT', '17-', '', ''],
            ['ACT DIRECT CAN SUPPORT', '18-', '', ''],
            ['EVENT YEAR-TO-DATE', '19', '', ''],
            ['ADDITIONAL DESCRIPTION', '20', '', ''],
            ['FEC COMMITTEE ID NUMBER', '21', '', ''],
            ['FEC CANDIDATE ID NUMBER', '22', '', ''],
            ['CANDIDATE NAME', '23', '', ''],
            ['CAN/OFF', '24', '', ''],
            ['STATE (OF ELECTION)', '25', '', ''],
            ['CAN/DIST', '26', '', ''],
            ['CONDUIT-NAME', '27', '', ''],
            ['CONDUIT-STREET-1', '28', '', ''],
            ['CONDUIT-STREET-2', '29', '', ''],
            ['CONDUIT-CITY', '30', '', ''],
            ['CONDUIT-STATE', '31', '', ''],
            ['CONDUIT-ZIP', '32', '', ''],
            ['AMENDED-CD', '33', '', ''],
            ['TRAN_ID', '34', '', ''],
            ['ORIG_TRAN_ID', '35', '', ''],
            ['SUPR_TRAN_ID', '36', '', ''],
    ]
