class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['CHANGE OF COMMITTEE NAME', '3', '', ''],
            ['COMMITTEE NAME', '4', '', ''],
            ['CHANGE OF ADDRESS', '5', '', ''],
            ['STREET 1', '6', '', ''],
            ['STREET 2', '7', '', ''],
            ['CITY', '8', '', ''],
            ['STATE', '9', '', ''],
            ['ZIP', '10', '', ''],
            ['COMMITTEE EMAIL', '11', '', ''],
            ['COMMITTEE WEB URL', '12', '', ''],
            ['COMMITTEE FAX NUMBER', '13', '', ''],
            ['SUBMISSION DATE', '14', '', ''],
            ['SIGNATURE LAST NAME', '15', '', ''],
            ['SIGNATURE FIRST NAME', '16', '', ''],
            ['SIGNATURE MIDDLE NAME', '17', '', ''],
            ['SIGNATURE PREFIX', '18', '', ''],
            ['SIGNATURE SUFFIX', '19', '', ''],
            ['DATE SIGNED', '20', '', ''],
            ['COMMITTEE TYPE', '21', '5', ''],
            ['CANDIDATE ID NUMBER', '22', '5', ''],
            ['CANDIDATE LAST NAME', '23', '5', ''],
            ['CANDIDATE FIRST NAME', '24', '5', ''],
            ['CANDIDATE MIDDLE NAME', '25', '5', ''],
            ['CANDIDATE PREFIX', '26', '5', ''],
            ['CANDIDATE SUFFIX', '27', '5', ''],
            ['CANDIDATE OFFICE', '28', '5', ''],
            ['CANDIDATE STATE', '29', '5', ''],
            ['CANDIDATE DISTRICT', '30', '5', ''],
            ['PARTY CODE', '31', '5', ''],
            ['PARTY TYPE', '32', '5', ''],
            ['ORGANIZATION TYPE', '33', '5', 'e'],
            ['LEADERSHIP PAC', '34', '5', 'f'],
            ['AFFILIATED Committee ID NUM', '35', '6', ''],
            ['AFFILIATED Committee NAME', '36', '6', ''],
            ['AFFILIATED STREET 1', '37', '6', ''],
            ['AFFILIATED STREET 2', '38', '6', ''],
            ['AFFILIATED CITY', '39', '6', ''],
            ['AFFILIATED STATE', '40', '6', ''],
            ['AFFILIATED ZIP', '41', '6', ''],
            ['AFFILIATED RELATIONSHIP CODE', '42', '6', ''],
            ['CUSTODIAN LAST NAME', '43', '7', ''],
            ['CUSTODIAN FIRST NAME', '44', '7', ''],
            ['CUSTODIAN MIDDLE NAME', '45', '7', ''],
            ['CUSTODIAN PREFIX', '46', '7', ''],
            ['CUSTODIAN SUFFIX', '47', '7', ''],
            ['CUSTODIAN STREET 1', '48', '7', ''],
            ['CUSTODIAN STREET 2', '49', '7', ''],
            ['CUSTODIAN CITY', '50', '7', ''],
            ['CUSTODIAN STATE', '51', '7', ''],
            ['CUSTODIAN ZIP', '52', '7', ''],
            ['CUSTODIAN TITLE', '53', '7', ''],
            ['CUSTODIAN TELEPHONE', '54', '7', ''],
            ['TREASURER LAST NAME', '55', '8', ''],
            ['TREASURER FIRST NAME', '56', '8', ''],
            ['TREASURER MIDDLE NAME', '57', '8', ''],
            ['TREASURER PREFIX', '58', '8', ''],
            ['TREASURER SUFFIX', '59', '8', ''],
            ['TREASURER STREET 1', '60', '8', ''],
            ['TREASURER STREET 2', '61', '8', ''],
            ['TREASURER CITY', '62', '8', ''],
            ['TREASURER STATE', '63', '8', ''],
            ['TREASURER ZIP', '64', '8', ''],
            ['TREASURER TITLE', '65', '8', ''],
            ['TREASURER TELEPHONE', '66', '8', ''],
            ['AGENT LAST NAME', '67', '8', ''],
            ['AGENT FIRST NAME', '68', '8', ''],
            ['AGENT MIDDLE NAME', '69', '8', ''],
            ['AGENT PREFIX', '70', '8', ''],
            ['AGENT SUFFIX', '71', '8', ''],
            ['AGENT STREET 1', '72', '8', ''],
            ['AGENT STREET 2', '73', '8', ''],
            ['AGENT CITY', '74', '8', ''],
            ['AGENT STATE', '75', '8', ''],
            ['AGENT ZIP', '76', '8', ''],
            ['AGENT TITLE', '77', '8', ''],
            ['AGENT TELEPHONE', '78', '8', ''],
            ['BANK NAME', '79', '9. a', ''],
            ['BANK STREET 1', '80', '9. a', ''],
            ['BANK STREET 2', '81', '9. a', ''],
            ['BANK CITY', '82', '9. a', ''],
            ['BANK STATE', '83', '9. a', ''],
            ['BANK ZIP', '84', '9. a', ''],
            ['BANK NAME', '85', '9. b', ''],
            ['BANK STREET 1', '86', '9. b', ''],
            ['BANK STREET 2', '87', '9. b', ''],
            ['BANK CITY', '88', '9. b', ''],
            ['BANK STATE', '89', '9. b', ''],
            ['BANK ZIP', '90', '9. b', ''],
    ]
