class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['JOINT FUND PARTICIPANT Committee NAME', '3', '5', ''],
            ['JOINT FUND PARTICIPANT Committee FEC-ID', '4', '5', ''],
            ['AFFILIATED Committee ID NUM', '5', '6', ''],
            ['AFFILIATED Committee NAME', '6', '6', ''],
            ['AFFILIATED STREET 1', '7', '6', ''],
            ['AFFILIATED STREET 2', '8', '6', ''],
            ['AFFILIATED CITY', '9', '6', ''],
            ['AFFILIATED STATE', '10', '6', ''],
            ['AFFILIATED ZIP', '11', '6', ''],
            ['AFFILIATED RELATIONSHIP CODE', '12', '6', ''],
            ['AGENT LAST NAME', '13', '8', ''],
            ['AGENT FIRST NAME', '14', '8', ''],
            ['AGENT MIDDLE NAME', '15', '8', ''],
            ['AGENT PREFIX', '16', '8', ''],
            ['AGENT SUFFIX', '17', '8', ''],
            ['AGENT STREET 1', '18', '8', ''],
            ['AGENT STREET 2', '19', '8', ''],
            ['AGENT CITY', '20', '8', ''],
            ['AGENT STATE', '21', '8', ''],
            ['AGENT ZIP', '22', '8', ''],
            ['AGENT TITLE', '23', '8', ''],
            ['AGENT TELEPHONE', '24', '8', ''],
            ['BANK NAME', '25', '9', ''],
            ['BANK STREET 1', '26', '9', ''],
            ['BANK STREET 2', '26', '9', ''],
            ['BANK CITY', '28', '9', ''],
            ['BANK STATE', '29', '9', ''],
            ['BANK ZIP', '30', '9', ''],
    ]
