class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['CHANGE OF ADDRESS', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['ACTIVITY PRIMARY', '10', '', ''],
            ['ACTIVITY GENERAL', '11', '', ''],
            ['REPORT CODE', '12', '', ''],
            ['ELECTION CODE', '13', '', ''],
            ['DATE OF ELECTION', '14', '', ''],
            ['STATE OF ELECTION', '15', '', ''],
            ['COVERAGE FROM DATE', '16', '', ''],
            ['COVERAGE THROUGH DATE', '17', '', ''],
            ['TREASURER LAST NAME', '18', '', ''],
            ['TREASURER FIRST NAME', '19', '', ''],
            ['TREASURER MIDDLE NAME', '20', '', ''],
            ['TREASURER PREFIX', '21', '', ''],
            ['TREASURER SUFFIX', '22', '', ''],
            ['DATE SIGNED', '23', '', ''],
            ['Cash on Hand Beginning Period', '24', '6', ''],
            ['Total Receipts', '25', '7', ''],
            ['SubTotal', '26', '8', ''],
            ['Total Disbursements', '27', '9', ''],
            ['Cash on Hand Close of Period', '28', '10', ''],
            ['Debts to', '29', '11', ''],
            ['Debts by', '30', '12', ''],
            ['Expenditures Subject to Limits', '31', '13', ''],
            ['Net Contributions', '32', '14', ''],
            ['Net Operating Expenditures', '33', '15', ''],
            ['Federal Funds', '34', '16', ''],
            ['Individuals', '35', '17', 'a'],
            ['Political Party Committees', '36', '17', 'b'],
            ['Other Political Committees (PACs)', '37', '17', 'c'],
            ['The Candidate', '38', '17', 'd'],
            ['Total Contributions', '39', '17', 'e'],
            ['Transfers From Aff/Other Party Committees', '40', '18', ''],
            ['Received from or Guaranteed by Cand.', '41', '19', 'a'],
            ['Other Loans', '42', '19', 'b'],
            ['Total Loans', '43', '19', 'c'],
            ['Operating', '44', '20', 'a'],
            ['Fundraising', '45', '20', 'b'],
            ['Legal and Accounting', '46', '20', 'c'],
            ['Total offsets to Expenditures', '47', '20', 'd'],
            ['Other Receipts', '48', '21', ''],
            ['Total Receipts', '49', '22', ''],
            ['Operating Expenditures', '50', '23', ''],
            ['Transfers to Other Authorized Committees', '51', '24', ''],
            ['Fundraising Disbursements', '52', '25', ''],
            ['Exempt Legal & Accounting Disbursement', '53', '26', ''],
            ['Made or guaranteed by Candidate', '54', '27', 'a'],
            ['Other Repayments', '55', '27', 'b'],
            ['Total Loan Repayments Made', '56', '27', 'c'],
            ['Individuals', '57', '28', 'a'],
            ['Political Party Committees', '58', '28', 'b'],
            ['Other Political Committees', '59', '28', 'c'],
            ['Total Contributions Refunds', '60', '28', 'd'],
            ['Other Disbursements', '61', '29', ''],
            ['Total Disbursements', '62', '30', ''],
            ['Items on Hand to be Liquidated', '63', '31', ''],
            ['ALABAMA', '64', '', ''],
            ['ALASKA', '65', '', ''],
            ['ARIZONA', '66', '', ''],
            ['ARKANSAS', '67', '', ''],
            ['CALIFORNIA', '68', '', ''],
            ['COLORADO', '69', '', ''],
            ['CONNECTICUT', '70', '', ''],
            ['DELAWARE', '71', '', ''],
            ['DIST OF COLUMBIA', '72', '', ''],
            ['FLORIDA', '73', '', ''],
            ['GEORGIA', '74', '', ''],
            ['HAWAII', '75', '', ''],
            ['IDAHO', '76', '', ''],
            ['ILLINOIS', '77', '', ''],
            ['INDIANA', '78', '', ''],
            ['IOWA', '79', '', ''],
            ['KANSAS', '80', '', ''],
            ['KENTUCKY', '81', '', ''],
            ['LOUISIANA', '82', '', ''],
            ['MAINE', '83', '', ''],
            ['MARYLAND', '84', '', ''],
            ['MASSACHUSETTS', '85', '', ''],
            ['MICHIGAN', '86', '', ''],
            ['MINNESOTA', '87', '', ''],
            ['MISSISSIPPI', '88', '', ''],
            ['MISSOURI', '89', '', ''],
            ['MONTANA', '90', '', ''],
            ['NEBRASKA', '91', '', ''],
            ['NEVADA', '92', '', ''],
            ['NEW HAMPSHIRE', '93', '', ''],
            ['NEW JERSEY', '94', '', ''],
            ['NEW MEXICO', '95', '', ''],
            ['NEW YORK', '96', '', ''],
            ['NORTH CAROLINA', '97', '', ''],
            ['NORTH DAKOTA', '98', '', ''],
            ['OHIO', '99', '', ''],
            ['OKLAHOMA', '100', '', ''],
            ['OREGON', '101', '', ''],
            ['PENNSYLVANIA', '102', '', ''],
            ['RHODE ISLAND', '103', '', ''],
            ['SOUTH CAROLINA', '104', '', ''],
            ['SOUTH DAKOTA', '105', '', ''],
            ['TENNESSEE', '106', '', ''],
            ['TEXAS', '107', '', ''],
            ['UTAH', '108', '', ''],
            ['VERMONT', '109', '', ''],
            ['VIRGINIA', '110', '', ''],
            ['WASHINGTON', '111', '', ''],
            ['WEST VIRGINIA', '112', '', ''],
            ['WISCONSIN', '113', '', ''],
            ['WYOMING', '114', '', ''],
            ['PUERTO RICO', '115', '', ''],
            ['GUAM', '116', '', ''],
            ['VIRGIN ISLANDS', '117', '', ''],
            ['TOTALS', '118', '', ''],
            ['Federal Funds', '119', '16', ''],
            ['Individuals', '120', '17', 'a'],
            ['Political Party Committees', '121', '17', 'b'],
            ['Other Political Committees (PACs)', '122', '17', 'c'],
            ['The Candidate', '123', '17', 'd'],
            ['Total contributions (Other than Loans)', '124', '17', 'e'],
            ['Transfers From Aff/Other Party Committees', '125', '18', ''],
            ['Received from or Guaranteed by Cand.', '126', '19', 'a'],
            ['Other Loans', '127', '19', 'b'],
            ['Total Loans', '128', '19', 'c'],
            ['Operating', '129', '20', 'a'],
            ['Fundraising', '130', '20', 'b'],
            ['Legal and Accounting', '131', '20', 'c'],
            ['Total Offsets to Operating Expenditures', '132', '20', 'd'],
            ['Other Receipts', '133', '21', ''],
            ['Total Receipts', '134', '22', ''],
            ['Operating Expenditures', '135', '23', ''],
            ['Transfers to Other Authorized Committees', '136', '24', ''],
            ['Fundraising Disbursements', '137', '25', ''],
            ['Exempt Legal & Accounting Disbursement', '138', '26', ''],
            ['Made or Guaranteed by the Candidate', '139', '27', 'a'],
            ['Other Repayments', '140', '27', 'b'],
            ['Total Loan Repayments Made', '141', '27', 'c'],
            ['Individuals', '142', '28', 'a'],
            ['Political Party Committees', '143', '28', 'b'],
            ['Other Political Committees', '144', '28', 'c'],
            ['Total Contributions Refunds', '145', '28', 'd'],
            ['Other Disbursements', '146', '29', ''],
            ['Total Disbursements', '147', '30', ''],
            ['ALABAMA', '148', '', ''],
            ['ALASKA', '149', '', ''],
            ['ARIZONA', '150', '', ''],
            ['ARKANSAS', '151', '', ''],
            ['CALIFORNIA', '152', '', ''],
            ['COLORADO', '153', '', ''],
            ['CONNECTICUT', '154', '', ''],
            ['DELAWARE', '155', '', ''],
            ['DIST OF COLUMBIA', '156', '', ''],
            ['FLORIDA', '157', '', ''],
            ['GEORGIA', '158', '', ''],
            ['HAWAII', '159', '', ''],
            ['IDAHO', '160', '', ''],
            ['ILLINOIS', '161', '', ''],
            ['INDIANA', '162', '', ''],
            ['IOWA', '163', '', ''],
            ['KANSAS', '164', '', ''],
            ['KENTUCKY', '165', '', ''],
            ['LOUISIANA', '166', '', ''],
            ['MAINE', '167', '', ''],
            ['MARYLAND', '168', '', ''],
            ['MASSACHUSETTS', '169', '', ''],
            ['MICHIGAN', '170', '', ''],
            ['MINNESOTA', '171', '', ''],
            ['MISSISSIPPI', '172', '', ''],
            ['MISSOURI', '173', '', ''],
            ['MONTANA', '174', '', ''],
            ['NEBRASKA', '175', '', ''],
            ['NEVADA', '176', '', ''],
            ['NEW HAMPSHIRE', '177', '', ''],
            ['NEW JERSEY', '178', '', ''],
            ['NEW MEXICO', '179', '', ''],
            ['NEW YORK', '180', '', ''],
            ['NORTH CAROLINA', '181', '', ''],
            ['NORTH DAKOTA', '182', '', ''],
            ['OHIO', '183', '', ''],
            ['OKLAHOMA', '184', '', ''],
            ['OREGON', '185', '', ''],
            ['PENNSYLVANIA', '186', '', ''],
            ['RHODE ISLAND', '187', '', ''],
            ['SOUTH CAROLINA', '188', '', ''],
            ['SOUTH DAKOTA', '189', '', ''],
            ['TENNESSEE', '190', '', ''],
            ['TEXAS', '191', '', ''],
            ['UTAH', '192', '', ''],
            ['VERMONT', '193', '', ''],
            ['VIRGINIA', '194', '', ''],
            ['WASHINGTON', '195', '', ''],
            ['WEST VIRGINIA', '196', '', ''],
            ['WISCONSIN', '197', '', ''],
            ['WYOMING', '198', '', ''],
            ['PUERTO RICO', '199', '', ''],
            ['GUAM', '200', '', ''],
            ['VIRGIN ISLANDS', '201', '', ''],
            ['TOTALS', '202', '', ''],
    ]
