class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['CHANGE OF ADDRESS', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['REPORT CODE', '10', '', ''],
            ['ELECTION CODE', '11', '', ''],
            ['DATE OF ELECTION', '12', '', ''],
            ['STATE OF ELECTION', '13', '', ''],
            ['COVERAGE FROM DATE', '14', '', ''],
            ['COVERAGE THROUGH DATE', '15', '', ''],
            ['QUALIFIED COMMITTEE', '16', '', ''],
            ['TREASURER LAST NAME', '17', '', ''],
            ['TREASURER FIRST NAME', '18', '', ''],
            ['TREASURER MIDDLE NAME', '19', '', ''],
            ['TREASURER PREFIX', '20', '', ''],
            ['TREASURER SUFFIX', '21', '', ''],
            ['DATE SIGNED', '22', '', ''],
            ['Cash on Hand beginning', '23', '6', 'b'],
            ['Total Receipts', '24', '6', 'c'],
            ['Subtotal', '25', '6', 'd'],
            ['Total Disbursements', '26', '7', ''],
            ['Cash on Hand at Close', '27', '8', ''],
            ['Debts to', '28', '9', ''],
            ['Debts by', '29', '10', ''],
            ['Itemized', '30', '11', '(a)i'],
            ['Unitemized', '31', '11', '(a)ii'],
            ['Total', '32', '11', '(a)iii'],
            ['Political Party Committees', '33', '11', 'b'],
            ['Other Political Committees (PACs)', '34', '11', 'c'],
            ['Total Contributions', '35', '11', 'd'],
            ['Transfers from Affiliated/Other Party Committees', '36', '12', ''],
            ['All Loans Received', '37', '13', ''],
            ['Loan Repayments Received', '38', '14', ''],
            ['Offsets to Operating Expenditures (refunds)', '39', '15', ''],
            ['Refunds of Federal Contributions', '40', '16', ''],
            ['Other Federal Receipts (dividends)', '41', '17', ''],
            ['Transfers from Nonfederal Account (H3)', '42', '18', 'a'],
            ['Transfers from Non-Federal (Levin - H5)', '43', '18', 'b'],
            ['Total Non-Federal Transfers (18a+18b)', '44', '18', 'c'],
            ['Total Receipts', '45', '19', ''],
            ['Total Federal Receipts', '46', '20', ''],
            ['Federal Share', '47', '21', '(a)i'],
            ['Non-Federal Share', '48', '21', '(a)ii'],
            ['Other Federal Operating Expenditures', '49', '21', 'b'],
            ['Total Operating Expenditures', '50', '21', 'c'],
            ['Transfers to Affiliated/Other Party Committees', '51', '22', ''],
            ['Contributions to Federal Candidates/Committees', '52', '23', ''],
            ['Independent Expenditures', '53', '24', ''],
            ['Coordinated Expend made by Party Committees', '54', '25', ''],
            ['Loan Repayments', '55', '26', ''],
            ['Loans Made', '56', '27', ''],
            ['Individuals/Persons', '57', '28', 'a'],
            ['Political Party Committees', '58', '28', 'b'],
            ['Other Political Committees', '59', '28', 'c'],
            ['Total Contributions Refunds', '60', '28', 'd'],
            ['Other Disbursements', '61', '29', ''],
            ['Shared Federal Activity (H6) Fed Share', '62', '30', '(a)i'],
            ['Shared Federal Activity (H6) Non-Fed', '63', '30', '(a)ii'],
            ['Non-Allocable 100% Fed Election Activity', '64', '30', 'b'],
            ['Total Federal Election Activity', '65', '30', 'c'],
            ['Total Disbursements', '66', '31', ''],
            ['Total Federal Disbursements', '67', '32', ''],
            ['Total Contributions', '68', '33', ''],
            ['Total Contribution Refunds', '69', '34', ''],
            ['Net Contributions', '70', '35', ''],
            ['Total Federal Operating Expenditures', '71', '36', ''],
            ['Offsets to Operating Expenditures', '72', '37', ''],
            ['Net Operating Expenditures', '73', '38', ''],
            ['Cash on Hand Jan 1, 19', '74', '6', 'a'],
            ['Year for Above', '75', '', ''],
            ['Total Receipts', '76', '6', 'c'],
            ['Subtotal', '77', '6', 'd'],
            ['Total disbursements', '78', '7', ''],
            ['Cash on Hand Close', '79', '8', ''],
            ['Itemized', '80', '11', '(a)i'],
            ['Unitemized', '81', '11', '(a)ii'],
            ['Total', '82', '11', '(a)iii'],
            ['Political Party committees', '83', '11', 'b'],
            ['Other Political Committees (PACs)', '84', '11', 'c'],
            ['Total Contributions', '85', '11', 'd'],
            ['Transfers from Affiliated/Other Party Committees', '86', '12', ''],
            ['All Loans Received', '87', '13', ''],
            ['Loan Repayments Received', '88', '14', ''],
            ['Offsets to Operating Expenditures (refunds)', '89', '15', ''],
            ['Refunds of Federal Contributions', '90', '16', ''],
            ['Other Federal Receipts (dividends)', '91', '17', ''],
            ['Transfers from Nonfederal Account (H3)', '92', '18', 'a'],
            ['Transfers from Non-Federal (Levin - H5)', '93', '18', 'b'],
            ['Total Non-Federal Transfers (18a+18b)', '94', '18', 'c'],
            ['Total Receipts', '95', '19', ''],
            ['Total Federal Receipts', '96', '20', ''],
            ['Federal Share', '97', '21', '(a)i'],
            ['Non-Federal Share', '98', '21', '(a)ii'],
            ['Other Federal Operating Expenditures', '99', '21', 'b'],
            ['Total operating Expenditures', '100', '21', 'c'],
            ['Transfers to Affiliated/Other Party Committees', '101', '22', ''],
            ['Contributions to Federal Candidates/Committees', '102', '23', ''],
            ['Independent Expenditures', '103', '24', ''],
            ['Coordinated Expend made by Party Committees', '104', '25', ''],
            ['Loan Repayments Made', '105', '26', ''],
            ['Loans Made', '106', '27', ''],
            ['Individuals/Persons', '107', '28', 'a'],
            ['Political Party Committees', '108', '28', 'b'],
            ['Other Political Committees', '109', '28', 'c'],
            ['Total contributions Refunds', '110', '28', 'd'],
            ['Other Disbursements', '111', '29', ''],
            ['Shared Federal Activity (H6) Fed Share', '112', '30', '(a)i'],
            ['Shared Federal Activity (H6) Non-Fed', '113', '30', '(a)ii'],
            ['Non-Allocable 100% Fed Election Activity', '114', '30', 'b'],
            ['Total Federal Election Activity', '115', '30', 'c'],
            ['Total Disbursements', '116', '31', ''],
            ['Total Federal Disbursements', '117', '32', ''],
            ['Total Contributions', '118', '33', ''],
            ['Total Contribution Refunds', '119', '34', ''],
            ['Net contributions', '120', '35', ''],
            ['Total Federal Operating Expenditures', '121', '36', ''],
            ['Offsets to Operating Expenditures', '122', '37', ''],
            ['Net Operating Expenditures', '123', '38', ''],
    ]
