from fec.version.records_base import RecordsBase
class Records(RecordsBase):
    def __init__(self):
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER COMMITTEE ID NUMBER', 'number': '2'},
            {'name': 'COMMITTEE NAME', 'number': '3'},
            {'name': 'STREET 1', 'number': '4'},
            {'name': 'STREET 2', 'number': '5'},
            {'name': 'CITY', 'number': '6'},
            {'name': 'STATE', 'number': '7'},
            {'name': 'ZIP', 'number': '8'},
            {'name': 'CASH ON HAND', 'number': '9-1.'},
            {'name': 'AS OF', 'number': '10-1(a).'},
            {'name': 'Total assets to be liquidated', 'number': '11-2.'},
            {'name': 'Total (assets)', 'number': '12-3.'},
            {'name': 'Year to date receipts', 'number': '13-4.'},
            {'name': 'Year to date disbursements', 'number': '14-5.'},
            {'name': 'Total amount of debts owed by committee', 'number': '15-6.'},
            {'name': 'Total number of creditors owed', 'number': '16-7.'},
            {'name': 'Number of creditors in part II of this plan', 'number': '17-8.'},
            {'name': 'Total amount of debts owed to creditors in part II of plan', 'number': '18-9.'},
            {'name': 'Total amount to be paid to creditors', 'number': '19-10.'},
            {'name': 'Is the committee terminating activities', 'number': '20-11. '},
            {'name': 'PLANNED FOR TERMINATION REPORT', 'number': '21-11. YES '},
            {'name': 'If this is an AUTH committee are there other AUTH committees', 'number': '22-12. '},
            {'name': 'DESCRIPTION (IF YES list AUTH COMMITTEE ID/NAMES)', 'number': '23-12.'},
            {'name': 'sufficient funds to pay total amount', 'number': '24-13. '},
            {'name': 'DESCRIPTION (IF NO, steps taken to obtain the funds)', 'number': '25-13.'},
            {'name': 'Has the committee filed previous plans', 'number': '26-14. '},
            {'name': 'After disposing, any residual funds?', 'number': '27-15. '},
            {'name': 'DESCRIPTION (IF YES, how will the funds be disbursed)', 'number': '28-15.'},
            {'name': 'Does committee have sufficient funds to pay the remaining', 'number': '29-PART III '},
            {'name': 'PART III DESCRIPTION (IF NO, steps taken to obtain the funds.)', 'number': '30'},
            {'name': 'TREASURER LAST NAME', 'number': '31'},
            {'name': 'TREASURER FIRST NAME', 'number': '32'},
            {'name': 'TREASURER MIDDLE NAME', 'number': '33'},
            {'name': 'TREASURER PREFIX', 'number': '34'},
            {'name': 'TREASURER SUFFIX', 'number': '35'},
            {'name': 'DATE SIGNED', 'number': '36'},
    ]
