class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['ENTITY TYPE', '4', '', ''],
            ['CREDITOR ORGANIZATION NAME', '5', '', ''],
            ['CREDITOR LAST NAME', '6', '', ''],
            ['CREDITOR FIRST NAME', '7', '', ''],
            ['CREDITOR MIDDLE NAME', '8', '', ''],
            ['CREDITOR PREFIX', '9', '', ''],
            ['CREDITOR SUFFIX', '10', '', ''],
            ['CREDITOR STREET 1', '11', '', ''],
            ['CREDITOR STREET 2', '12', '', ''],
            ['CREDITOR CITY', '13', '', ''],
            ['CREDITOR STATE', '14', '', ''],
            ['CREDITOR ZIP', '15', '', ''],
            ['DATE INCURRED', '16', '', ''],
            ['AMOUNT OWED TO CREDITOR', '17', '', ''],
            ['AMOUNT EXPECTED TO PAY/OFFER', '18', '', ''],
            ['CREDITOR CODE', '19', '', ''],
            ['Disputed Debt?', '20-', '', ''],
            ['CREDITOR COMMITTEE ID NUMBER', '21', '', ''],
            ['CREDITOR CANDIDATE ID NUMBER', '22', '', ''],
            ['CREDITOR CANDIDATE LAST NAME', '23', '', ''],
            ['CREDITOR CANDIDATE FIRST NAME', '24', '', ''],
            ['CREDITOR CANDIDATE MIDDLE NAME', '25', '', ''],
            ['CREDITOR CANDIDATE PREFIX', '26', '', ''],
            ['CREDITOR CANDIDATE SUFFIX', '27', '', ''],
            ['CREDITOR CANDIDATE OFFICE', '28', '', ''],
            ['CREDITOR CANDIDATE STATE', '29', '', ''],
            ['CREDITOR CANDIDATE DISTRICT', '30', '', ''],
    ]
