class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['BACK REFERENCE TRAN ID NUMBER', '4', '', ''],
            ['BACK REFERENCE SCHED NAME', '5', '', ''],
            ['ENTITY TYPE', '6', '', ''],
            ['PAYEE ORGANIZATION NAME', '7', '', ''],
            ['PAYEE LAST NAME', '8', '', ''],
            ['PAYEE FIRST NAME', '9', '', ''],
            ['PAYEE MIDDLE NAME', '10', '', ''],
            ['PAYEE PREFIX', '11', '', ''],
            ['PAYEE SUFFIX', '12', '', ''],
            ['PAYEE STREET 1', '13', '', ''],
            ['PAYEE STREET 2', '14', '', ''],
            ['PAYEE CITY', '15', '', ''],
            ['PAYEE STATE', '16', '', ''],
            ['PAYEE ZIP', '17', '', ''],
            ['ACCOUNT/EVENT IDENTIFIER', '18', '', ''],
            ['EXPENDITURE DATE', '19', '', ''],
            ['TOTAL FED-LEVIN AMOUNT', '20', '', ''],
            ['FEDERAL SHARE', '21', '', ''],
            ['LEVIN SHARE', '22', '', ''],
            ['ACTIVITY/EVENT TOTAL YTD', '23', '', ''],
            ['EXPENDITURE PURPOSE CODE', '24', '', ''],
            ['EXPENDITURE PURPOSE DESCRIP', '25', '', ''],
            ['CATEGORY CODE', '26', '', ''],
            ['Activity Is Voter Registration', '27-', '', ''],
            ['Activity GOTV', '28-', '', ''],
            ['Activity Is Voter ID', '29-', '', ''],
            ['Activity is Generic Campaign', '30-', '', ''],
            ['MEMO CODE', '31', '', ''],
            ['MEMO TEXT/DESCRIPTION', '32', '', ''],
    ]
