import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER COMMITTEE ID', 'number': '2'},
            {'name': 'TRANSACTION ID NUMBER', 'number': '3'},
            {'name': 'RECORD ID NUMBER (for account name)', 'number': '4'},
            {'name': 'ACCOUNT NAME', 'number': '5'},
            {'name': 'COVERAGE FROM DATE', 'number': '6'},
            {'name': 'COVERAGE THROUGH DATE', 'number': '7'},
            {'name': 'Itemized Receipts From Persons', 'number': '8-1a.'},
            {'name': 'Unitemized Receipts From Persons', 'number': '9-1b.'},
            {'name': 'Total Receipts From Persons', 'number': '10-1c.'},
            {'name': 'OTHER RECEIPTS', 'number': '11-2.'},
            {'name': 'TOTAL RECEIPTS', 'number': '12-3.'},
            {'name': 'Voter Registration DISBURSEMENTS', 'number': '13-4(a).'},
            {'name': 'Voter ID DISBURSEMENTS', 'number': '14-4(b).'},
            {'name': 'GOTV DISBURSEMENTS', 'number': '15-4(c).'},
            {'name': 'Generic Campaign DISBURSEMENTS', 'number': '16-4(d).'},
            {'name': 'Line 4 Total', 'number': '17-4(e)'},
            {'name': 'OTHER DISBURSEMENTS', 'number': '18-5.'},
            {'name': 'TOTAL DISBURSEMENTS', 'number': '19-6.'},
            {'name': 'CASH ON HAND (Beginning)', 'number': '20-7.'},
            {'name': 'RECEIPTS', 'number': '21-8.'},
            {'name': 'SUBTOTAL', 'number': '22-9.'},
            {'name': 'DISBURSEMENTS', 'number': '23-10.'},
            {'name': 'ENDING CASH ON HAND', 'number': '24-11.'},
            {'name': 'Itemized Receipts From Persons', 'number': '25-1a.'},
            {'name': 'Unitemized Receipts From Persons', 'number': '26-1b.'},
            {'name': 'Total Receipts From Persons', 'number': '27-1c.'},
            {'name': 'OTHER RECEIPTS', 'number': '28-2.'},
            {'name': 'TOTAL RECEIPTS', 'number': '29-3.'},
            {'name': 'Voter Registration DISBURSEMENTS', 'number': '30-4(a).'},
            {'name': 'Voter ID DISBURSEMENTS', 'number': '31-4(b).'},
            {'name': 'GOTV DISBURSEMENTS', 'number': '32-4(c).'},
            {'name': 'Generic Campaign DISBURSEMENTS', 'number': '33-4(d).'},
            {'name': 'Line 4 Total', 'number': '34-4(e)'},
            {'name': 'OTHER DISBURSEMENTS', 'number': '35-5.'},
            {'name': 'TOTAL DISBURSEMENTS', 'number': '36-6.'},
            {'name': 'CASH ON HAND as of Jan 1', 'number': '37-7.'},
            {'name': 'RECEIPTS', 'number': '38-8.'},
            {'name': 'SUBTOTAL', 'number': '39-9.'},
            {'name': 'DISBURSEMENTS', 'number': '40-10.'},
            {'name': 'ENDING CASH ON HAND', 'number': '41-11.'},
    ]
        self.fields_names = self.hash_names(self.fields)
