class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FEC COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['SUBMITTED', '9-', '', ''],
            ['CHG OF COMMITTEE NAME', '10', '', ''],
            ['CHG OF ADDRESS', '11', '', ''],
            ['COMMITTEE TYPE', '12', '', ''],
            ['FEC CANDIDATE ID NUMBER', '13', '', ''],
            ['CANDIDATE NAME', '14', '', ''],
            ['CAND / OFFICE SOUGHT', '15', '', ''],
            ['CAND / STATE (of Election)', '16', '', ''],
            ['CAND / DISTRICT', '17', '', ''],
            ['PARTY CODE', '18', '', ''],
            ['PARTY TYPE', '19', '', ''],
            ['FEC COMMITTEE ID NUMBER', '20', '', ''],
            ['COMMITTEE NAME', '21', '', ''],
            ['STREET 1', '22', '', ''],
            ['STREET 2', '23', '', ''],
            ['CITY', '24', '', ''],
            ['STATE', '25', '', ''],
            ['ZIP', '26', '', ''],
            ['RELATIONSHIP WITH ABOVE CMTE', '27', '', ''],
            ['ORGANIZATION TYPE', '28', '', ''],
            ['CUSTODIAN NAME', '29-', '', ''],
            ['STREET 1', '30', '', ''],
            ['STREET 2', '31', '', ''],
            ['CITY', '32', '', ''],
            ['STATE', '33', '', ''],
            ['ZIP', '34', '', ''],
            ['TITLE', '35', '', ''],
            ['TELEPHONE', '36', '', ''],
            ['TREASURER', '37-', '', ''],
            ['STREET 1', '38', '', ''],
            ['STREET 2', '39', '', ''],
            ['CITY', '40', '', ''],
            ['STATE', '41', '', ''],
            ['ZIP', '42', '', ''],
            ['TITLE', '43', '', ''],
            ['TELEPHONE', '44', '', ''],
            ['DESIGNATED AGENT)', '45-', '', ''],
            ['STREET 1', '46', '', ''],
            ['STREET 2', '47', '', ''],
            ['CITY', '48', '', ''],
            ['STATE', '49', '', ''],
            ['ZIP', '50', '', ''],
            ['TITLE', '51', '', ''],
            ['TELEPHONE', '52', '', ''],
            ['BANK/OTHER', '53-', '', ''],
            ['STREET 1', '54', '', ''],
            ['STREET 2', '55', '', ''],
            ['CITY', '56', '', ''],
            ['STATE', '57', '', ''],
            ['ZIP', '58', '', ''],
            ['TREASURER', '59-', '', ''],
            ['SIGNED', '60-', '', ''],
    ]
