import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'Combines Form (F1M)', 'number': '1'},
            {'name': 'FEC COMMITTEE ID NUMBER', 'number': '2'},
            {'name': 'COMMITTEE NAME', 'number': '3'},
            {'name': 'STREET 1', 'number': '4'},
            {'name': 'STREET 2', 'number': '5'},
            {'name': 'CITY', 'number': '6'},
            {'name': 'STATE', 'number': '7'},
            {'name': 'ZIP', 'number': '8'},
            {'name': 'COMMITTEE TYPE', 'number': '9'},
            {'name': 'DATE ( OF AFFILIATION)', 'number': '10'},
            {'name': 'FEC COMMITTEE ID NUMBER', 'number': '11'},
            {'name': 'COMMITTEE NAME', 'number': '12'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '13'},
            {'name': 'CANDIDATE NAME', 'number': '14'},
            {'name': 'CAN/OFF', 'number': '15'},
            {'name': 'STATE (OF ELECTION)', 'number': '16'},
            {'name': 'CAN/DIST', 'number': '17'},
            {'name': 'OF CONTRIBUTION', 'number': '18-'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '19'},
            {'name': 'CANDIDATE NAME', 'number': '20'},
            {'name': 'CAN/OFF', 'number': '21'},
            {'name': 'STATE (OF ELECTION)', 'number': '22'},
            {'name': 'CAN/DIST', 'number': '23'},
            {'name': 'OF CONTRIBUTION', 'number': '24-'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '25'},
            {'name': 'CANDIDATE NAME', 'number': '26'},
            {'name': 'CAN/OFF', 'number': '27'},
            {'name': 'STATE (OF ELECTION)', 'number': '28'},
            {'name': 'CAN/DIST', 'number': '29'},
            {'name': 'OF CONTRIBUTION', 'number': '30-'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '31'},
            {'name': 'CANDIDATE NAME', 'number': '32'},
            {'name': 'CAN/OFF', 'number': '33'},
            {'name': 'STATE (OF ELECTION)', 'number': '34'},
            {'name': 'CAN/DIST', 'number': '35'},
            {'name': 'OF CONTRIBUTION', 'number': '36-'},
            {'name': 'FEC CANDIDATE ID NUMBER', 'number': '37'},
            {'name': 'CANDIDATE NAME', 'number': '38'},
            {'name': 'CAN/OFF', 'number': '39'},
            {'name': 'STATE (OF ELECTION)', 'number': '40'},
            {'name': 'CAN/DIST', 'number': '41'},
            {'name': 'OF CONTRIBUTION', 'number': '42-'},
            {'name': 'OF 51ST CONTRIBUTOR', 'number': '43-'},
            {'name': 'OF ORIGINAL REGISTRATION', 'number': '44-'},
            {'name': 'COMMITTEE MET REQUIREMENTS', 'number': '45-'},
            {'name': 'TREASURER', 'number': '46-'},
            {'name': 'SIGNED', 'number': '47-'},
    ]
        self.fields_names = self.hash_names(self.fields)
