class Records:
    def __init__(self):
        self.fields = [
            ['Combines Form (F1M)', '1', '', ''],
            ['FEC COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['COMMITTEE TYPE', '9', '', ''],
            ['DATE ( OF AFFILIATION)', '10', '', ''],
            ['FEC COMMITTEE ID NUMBER', '11', '', ''],
            ['COMMITTEE NAME', '12', '', ''],
            ['FEC CANDIDATE ID NUMBER', '13', '', ''],
            ['CANDIDATE NAME', '14', '', ''],
            ['CAN/OFF', '15', '', ''],
            ['STATE (OF ELECTION)', '16', '', ''],
            ['CAN/DIST', '17', '', ''],
            ['OF CONTRIBUTION', '18-', '', ''],
            ['FEC CANDIDATE ID NUMBER', '19', '', ''],
            ['CANDIDATE NAME', '20', '', ''],
            ['CAN/OFF', '21', '', ''],
            ['STATE (OF ELECTION)', '22', '', ''],
            ['CAN/DIST', '23', '', ''],
            ['OF CONTRIBUTION', '24-', '', ''],
            ['FEC CANDIDATE ID NUMBER', '25', '', ''],
            ['CANDIDATE NAME', '26', '', ''],
            ['CAN/OFF', '27', '', ''],
            ['STATE (OF ELECTION)', '28', '', ''],
            ['CAN/DIST', '29', '', ''],
            ['OF CONTRIBUTION', '30-', '', ''],
            ['FEC CANDIDATE ID NUMBER', '31', '', ''],
            ['CANDIDATE NAME', '32', '', ''],
            ['CAN/OFF', '33', '', ''],
            ['STATE (OF ELECTION)', '34', '', ''],
            ['CAN/DIST', '35', '', ''],
            ['OF CONTRIBUTION', '36-', '', ''],
            ['FEC CANDIDATE ID NUMBER', '37', '', ''],
            ['CANDIDATE NAME', '38', '', ''],
            ['CAN/OFF', '39', '', ''],
            ['STATE (OF ELECTION)', '40', '', ''],
            ['CAN/DIST', '41', '', ''],
            ['OF CONTRIBUTION', '42-', '', ''],
            ['OF 51ST CONTRIBUTOR', '43-', '', ''],
            ['OF ORIGINAL REGISTRATION', '44-', '', ''],
            ['COMMITTEE MET REQUIREMENTS', '45-', '', ''],
            ['TREASURER', '46-', '', ''],
            ['SIGNED', '47-', '', ''],
    ]
