class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FEC COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['CHG OF ADDRESS', '9', '', ''],
            ['ELECTION STATE', '10', '', ''],
            ['ELECTION DISTRICT', '11', '', ''],
            ['RPTCODE', '12', '', ''],
            ['RPTPGI', '13', '', ''],
            ['OF ELECTION', '14-', '', ''],
            ['STATE (OF ELECTION)', '15', '', ''],
            ['ACTIVITY PRIMARY', '16', '', ''],
            ['ACTIVITY GENERAL', '17', '', ''],
            ['ACTIVITY SPECIAL', '18', '', ''],
            ['ACTIVITY RUNOFF', '19', '', ''],
            ['COVERAGE FROM', '20-', '', ''],
            ['COVERAGE TO', '21-', '', ''],
            ['Total Contributions (NO Loans)', '22', '6a', ''],
            ['Total Contribution Refunds', '23', '6b', ''],
            ['Net Contributions', '24', '6c', ''],
            ['Total Operating Expenditures', '25', '7a', ''],
            ['Total Offset to Operating Expenditures', '26', '7b', ''],
            ['NET Operating Expenditures', '27', '7c', ''],
            ['Cash on Hand Close of reporting period', '28', '8', ''],
            ['DEBTS TO ( Totals from SCH C and/or D)', '29', '9', ''],
            ['DEBTS BY (Totals from SCH C and/or D)', '30', '10', ''],
            ['Individuals Itemized', '31', '11', 'ai'],
            ['Individuals UnItemized', '32', '11', 'aii'],
            ['Individual Contribution Total', '33', '11', 'aiii'],
            ['Political Party Committees', '34', '11', 'b'],
            ['Other Political Committees', '35', '11', 'c'],
            ['The Candidate', '36', '11', 'd'],
            ['Total Contributions', '37', '11', 'e'],
            ['Transfers from Other Authorized Committees', '38', '12', ''],
            ['Loans made or guarn. by the Candidate', '39', '13', 'a'],
            ['All Other Loans', '40', '13', 'b'],
            ['Total Loans', '41', '13', 'c'],
            ['Offsets to Operating Expenditures', '42', '14', ''],
            ['Other Receipts', '43', '15', ''],
            ['Total Receipts', '44', '16', ''],
            ['Operating Expenditures', '45', '17', ''],
            ['Transfers to Other Authorized Committees', '46', '18', ''],
            ['Of Loans made or guar by the Candidate', '47', '19', 'a'],
            ['Loan Repayments, All Other Loans', '48', '19', 'b'],
            ['Total Loan Repayments', '49', '19', 'c'],
            ['Refund/Individuals Other than Political Committees', '50', '20', 'a'],
            ['Refund Political Party Committees', '51', '20', 'b'],
            ['Refund Other Political Committees', '52', '20', 'c'],
            ['Total Contributions Refunds', '53', '20', 'd'],
            ['Other Disbursements', '54', '21', ''],
            ['Total Disbursements', '55', '22', ''],
            ['Cash Beginning Reporting Period', '56', '23', ''],
            ['Total Receipts this Period', '57', '24', ''],
            ['SubTotal)', '58', '25', ''],
            ['Total Disbursements this Period', '59', '26', ''],
            ['Cash on hand at Close Period', '60', '27', ''],
            ['Total Contributions (No Loans)', '61', '6a', ''],
            ['Total Contribution Refunds', '62', '6b', ''],
            ['Net Contributions', '63', '6c', ''],
            ['Total Operating Expenditures', '64', '7a', ''],
            ['Total Offsets to Operating Expenditures', '65', '7b', ''],
            ['NET Operating Expenditures', '66', '7c', ''],
            ['Individuals Itemized', '67', '11', 'ai'],
            ['Individuals UnItemized', '68', '11', 'aii'],
            ['Individuals Total', '69', '11', 'aiii'],
            ['Political Party Committees', '70', '11', 'b'],
            ['All Other Political Committees (PACS)', '71', '11', 'c'],
            ['THE CANDIDATE', '72', '11', 'd'],
            ['Total Contributions', '73', '11', 'e'],
            ['Transfers from Other AUTH Committees', '74', '12', ''],
            ['Loans made or guarn. by the Candidate', '75', '13', 'a'],
            ['All Other Loans', '76', '13', 'b'],
            ['Total Loans', '77', '13', 'c'],
            ['Offsets to Operating Expenditures', '78', '14', ''],
            ['Other Receipts', '79', '15', ''],
            ['Total Receipts', '80', '16', ''],
            ['Operating Expenditures', '81', '17', ''],
            ['Transfers To Other AUTH Committees', '82', '18', ''],
            ['Loan Repayment to Candidate', '83', '19', 'a'],
            ['Loan Repayments, ALL Other Loans', '84', '19', 'b'],
            ['Total Loan Repayments', '85', '19', 'c'],
            ['Refund/Individuals Other than Political Committees', '86', '20', 'a'],
            ['Refund, Political Party Committees', '87', '20', 'b'],
            ['Refund, Other Political Committees', '88', '20', 'c'],
            ['Total Contributions Refunds', '89', '20', 'd'],
            ['Other Disbursements', '90', '21', ''],
            ['Total Disbursements', '91', '22', ''],
            ['TREASURER', '92-', '', ''],
            ['SIGNED', '93-', '', ''],
    ]
