class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FEC COMMITTEE ID NUMBER', '2', '', ''],
            ['CONTRIB/LENDER', '3-', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['ITEM-PG', '9', '', ''],
            ['INDEMP', '10', '', ''],
            ['INDOCC', '11', '', ''],
            ['OF CONTRIBUTION', '12-', '', ''],
            ['FAIR MARKET VALUE OF ITEM', '13', '', ''],
            ['TRANSACTION CODE', '14', '', ''],
            ['TRANSDESC', '15', '', ''],
            ['FEC COMMITTEE ID NUMBER', '16', '', ''],
            ['COMMITTEE NAME', '17', '', ''],
            ['STREET 1', '18', '', ''],
            ['STREET 2', '19', '', ''],
            ['CITY', '20', '', ''],
            ['STATE', '21', '', ''],
            ['ZIP', '22', '', ''],
            ['FEC CANDIDATE ID NUMBER', '23', '', ''],
            ['CANDIDATE NAME', '24', '', ''],
            ['CAN/OFF', '25', '', ''],
            ['STATE (OF ELECTION)', '26', '', ''],
            ['CAN/DIST', '27', '', ''],
            ['MEMO CODE', '28', '', ''],
            ['MEMO-TEXT', '29', '', ''],
            ['AMENDED', '30', '', ''],
    ]
