class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FEC COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['CONVENTION TYPE', '9', '', ''],
            ['DESC ( IF 9 IS \xe2\x80\x9cOTHER\xe2\x80\x9d)', '10', '', ''],
            ['RPTCODE', '11', '', ''],
            ['COVERAGE FROM', '12-', '', ''],
            ['COVERAGE TO', '13-', '', ''],
            ['cash on hand beg report per', '14', '6', 'b'],
            ['Total receipts', '15', '6', 'c'],
            ['Subtotal', '16', '6', 'd'],
            ['Total disbursements', '17', '7', ''],
            ['COH CLOSE', '18', '8', ''],
            ['Debts to', '19', '9', ''],
            ['Debts by', '20', '10', ''],
            ['Convention expenditures', '21', '11', ''],
            ['refunds/rebates/returns relating to convention expend.', '22', '11', ''],
            ['Expenditures subject to limits', '23', '12', 'a'],
            ['expend from prior years subject to limits', '24', '12', 'b'],
            ['total expenditures subject to limits', '25', '12', 'c'],
            ['Federal Funds', '26', '13', ''],
            ['Itemized', '27', '14', 'a'],
            ['unitemized', '28', '14', 'b'],
            ['subtotal', '29', '14', 'c'],
            ['Transfers from affiliated Committees', '30', '15', ''],
            ['loans received', '31', '16', 'a'],
            ['loan repayments received', '32', '16', 'b'],
            ['subtotal loans/repayments', '33', '16', 'c'],
            ['Itemized', '34', '17', 'a'],
            ['unitemized', '35', '17', 'b'],
            ['subtotal', '36', '17', 'c'],
            ['Itemized', '37', '18', 'a'],
            ['unitemized', '38', '18', 'b'],
            ['subtotal', '39', '18', 'c'],
            ['Itemized', '40', '19', 'a'],
            ['unitemized', '41', '19', 'b'],
            ['subtotal', '42', '19', 'c'],
            ['total receipts', '43', '20', ''],
            ['Itemized', '44', '21', 'a'],
            ['unitemized', '45', '21', 'b'],
            ['subtotal', '46', '21', 'c'],
            ['Transfers to Affiliated Committees', '47', '22', ''],
            ['loans made', '48', '23', 'a'],
            ['loan repayments made', '49', '23', 'b'],
            ['subtotal', '50', '23', 'c'],
            ['Itemized', '51', '24', 'a'],
            ['unitemized', '52', '24', 'b'],
            ['subtotal', '53', '24', 'c'],
            ['Total disbursements', '54', '25', ''],
            ['Cash on Hand', '55', '6', 'a'],
            ['year', '56', '6(a) 19', ''],
            ['Total receipts', '57', '6', 'c'],
            ['Subtotal', '58', '6', 'd'],
            ['Total disbursements', '59', '7', ''],
            ['COH CLOSE', '60', '8', ''],
            ['Convention expenditures', '61', '11', ''],
            ['refunds/rebates/returns relating to convention expend.', '62', '12', ''],
            ['Expenditures subject to limits', '63', '12', 'a'],
            ['expend from prior years subject to limits', '64', '12', 'b'],
            ['total expenditures subject to limits', '65', '12', 'c'],
            ['Federal Funds', '66', '13', ''],
            ['subtotal', '67', '14', 'c'],
            ['Transfers from affiliated Committees', '68', '15', ''],
            ['subtotal loans/repayments', '69', '16', 'c'],
            ['subtotal', '70', '17', 'c'],
            ['subtotal', '71', '18', 'c'],
            ['subtotal', '72', '19', 'c'],
            ['total receipts', '73', '20', ''],
            ['subtotal', '74', '21', 'c'],
            ['Transfers to Affiliated Committees', '75', '22', ''],
            ['subtotal', '76', '23', 'c'],
            ['subtotal', '77', '24', 'c'],
            ['Total disbursements', '78', '25', ''],
            ['TREASURER', '79-', '', ''],
            ['SIGNED', '80-', '', ''],
    ]
