class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FEC COMMITTEE ID NUMBER', '2', '', ''],
            ['CONTRIB/LENDER', '3-', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['ITEM-PG-OTHER', '9', '', ''],
            ['PG-OTHER-DESCRIPTION', '10', '', ''],
            ['INDEMP', '11', '', ''],
            ['INDOCC', '12', '', ''],
            ['AGGR YTD AMOUNT (TOTAL FOR THE YEAR)', '13', '', ''],
            ['OF CONTRIBUTION', '14-', '', ''],
            ['AMOUNT RECEIVED', '15', '', ''],
            ['RECEIPTCODE', '16', '', ''],
            ['TRANSDESC', '17', '', ''],
            ['FEC COMMITTEE ID NUMBER', '18', '', ''],
            ['COMMITTEE NAME', '19', '', ''],
            ['STREET 1', '20', '', ''],
            ['STREET 2', '21', '', ''],
            ['CITY', '22', '', ''],
            ['STATE', '23', '', ''],
            ['ZIP', '24', '', ''],
            ['FEC CANDIDATE ID NUMBER', '25', '', ''],
            ['CANDIDATE NAME', '26', '', ''],
            ['CAN/OFF', '27', '', ''],
            ['STATE (OF ELECTION)', '28', '', ''],
            ['CAN/DIST', '29', '', ''],
            ['MEMO CODE', '30', '', ''],
            ['MEMO-TEXT', '31', '', ''],
            ['AMENDED', '32', '', ''],
    ]
