class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FEC COMMITTEE ID NUMBER', '2', '', ''],
            ['RECIPIENT', '3-', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['DISBURSCODE', '9', '', ''],
            ['TRANSDESC', '10', '', ''],
            ['ITEM-PG-OTHER', '11', '', ''],
            ['PG-OTHER-DESCRIPTION', '12', '', ''],
            ['OF DISBURSEMENT', '13-', '', ''],
            ['AMOUNT DISBURSED CONTRIB/LOAN', '14', '', ''],
            ['FEC COMMITTEE ID NUMBER', '15', '', ''],
            ['COMMITTEE NAME', '16', '', ''],
            ['STREET 1', '17', '', ''],
            ['STREET 2', '18', '', ''],
            ['CITY', '19', '', ''],
            ['STATE', '20', '', ''],
            ['ZIP', '21', '', ''],
            ['FEC CANDIDATE ID NUMBER', '22', '', ''],
            ['CANDIDATE NAME', '23', '', ''],
            ['CAN/OFF', '24', '', ''],
            ['STATE (OF ELECTION)', '25', '', ''],
            ['CAN/DIST', '26', '', ''],
            ['MEMO CODE', '27', '', ''],
            ['MEMO TEXT', '28', '', ''],
            ['AMENDED', '29', '', ''],
    ]
