import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FEC COMMITTEE ID NUMBER', 'number': '2'},
            {'name': 'REFERENCE ID NUMBER', 'number': '3'},
            {'name': 'LOAN SOURCE', 'number': '4-'},
            {'name': 'STREET 1', 'number': '5'},
            {'name': 'STREET 2', 'number': '6'},
            {'name': 'CITY', 'number': '7'},
            {'name': 'STATE', 'number': '8'},
            {'name': 'ZIP', 'number': '9'},
            {'name': 'ELECTION (PGI)', 'number': '10'},
            {'name': 'PGI SPECIFICATION DESCRIPTION', 'number': '11'},
            {'name': 'ORIG AMT OF LOAN AMOUNT', 'number': '12'},
            {'name': 'PAYMENT TO DATE', 'number': '13'},
            {'name': 'LOAN BALANCE', 'number': '14'},
            {'name': 'INCURRED', 'number': '15-'},
            {'name': 'DUE', 'number': '16-'},
            {'name': 'LOAN INTEREST RATE PERCENTAGE', 'number': '17'},
            {'name': 'SECURED LOAN', 'number': '18-'},
            {'name': 'ENDORSER/GUARANTOR', 'number': '19-'},
            {'name': 'STREET 1', 'number': '20'},
            {'name': 'STREET 2', 'number': '21'},
            {'name': 'CITY', 'number': '22'},
            {'name': 'STATE', 'number': '23'},
            {'name': 'ZIP', 'number': '24'},
            {'name': 'INDEMP', 'number': '25'},
            {'name': 'INDOCC', 'number': '26'},
            {'name': 'AMT GUARANTEED BAL AMOUNT', 'number': '27'},
            {'name': 'ENDORSER/GUARANTOR', 'number': '28-'},
            {'name': 'STREET 1', 'number': '29'},
            {'name': 'STREET 2', 'number': '30'},
            {'name': 'CITY', 'number': '31'},
            {'name': 'STATE', 'number': '32'},
            {'name': 'ZIP', 'number': '33'},
            {'name': 'INDEMP', 'number': '34'},
            {'name': 'INDOCC', 'number': '35'},
            {'name': 'AMT GUARANTEED BAL AMOUNT', 'number': '36'},
            {'name': 'ENDORSER/GUARANTOR', 'number': '37-'},
            {'name': 'STREET 1', 'number': '38'},
            {'name': 'STREET 2', 'number': '39'},
            {'name': 'CITY', 'number': '40'},
            {'name': 'STATE', 'number': '41'},
            {'name': 'ZIP', 'number': '42'},
            {'name': 'INDEMP', 'number': '43'},
            {'name': 'INDOCC', 'number': '44'},
            {'name': 'AMT GUARANTEED BAL AMOUNT', 'number': '45'},
            {'name': 'AMENDED', 'number': '46'},
    ]
        self.fields_names = self.hash_names(self.fields)
