class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FEC COMMITTEE ID NUMBER', '2', '', ''],
            ['REFERENCE ID NUMBER', '3', '', ''],
            ['LOAN SOURCE', '4-', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['ELECTION (PGI)', '10', '', ''],
            ['PGI SPECIFICATION DESCRIPTION', '11', '', ''],
            ['ORIG AMT OF LOAN AMOUNT', '12', '', ''],
            ['PAYMENT TO DATE', '13', '', ''],
            ['LOAN BALANCE', '14', '', ''],
            ['INCURRED', '15-', '', ''],
            ['DUE', '16-', '', ''],
            ['LOAN INTEREST RATE PERCENTAGE', '17', '', ''],
            ['SECURED LOAN', '18-', '', ''],
            ['ENDORSER/GUARANTOR', '19-', '', ''],
            ['STREET 1', '20', '', ''],
            ['STREET 2', '21', '', ''],
            ['CITY', '22', '', ''],
            ['STATE', '23', '', ''],
            ['ZIP', '24', '', ''],
            ['INDEMP', '25', '', ''],
            ['INDOCC', '26', '', ''],
            ['AMT GUARANTEED BAL AMOUNT', '27', '', ''],
            ['ENDORSER/GUARANTOR', '28-', '', ''],
            ['STREET 1', '29', '', ''],
            ['STREET 2', '30', '', ''],
            ['CITY', '31', '', ''],
            ['STATE', '32', '', ''],
            ['ZIP', '33', '', ''],
            ['INDEMP', '34', '', ''],
            ['INDOCC', '35', '', ''],
            ['AMT GUARANTEED BAL AMOUNT', '36', '', ''],
            ['ENDORSER/GUARANTOR', '37-', '', ''],
            ['STREET 1', '38', '', ''],
            ['STREET 2', '39', '', ''],
            ['CITY', '40', '', ''],
            ['STATE', '41', '', ''],
            ['ZIP', '42', '', ''],
            ['INDEMP', '43', '', ''],
            ['INDOCC', '44', '', ''],
            ['AMT GUARANTEED BAL AMOUNT', '45', '', ''],
            ['AMENDED', '46', '', ''],
    ]
