import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FEC COMMITTEE ID NUMBER', 'number': '2'},
            {'name': 'REFERENCE ID NUMBER', 'number': '3'},
            {'name': 'LOAN SOURCE', 'number': '4-'},
            {'name': 'STREET 1', 'number': '5'},
            {'name': 'STREET 2', 'number': '6'},
            {'name': 'CITY', 'number': '7'},
            {'name': 'STATE', 'number': '8'},
            {'name': 'ZIP', 'number': '9'},
            {'name': 'AMT OF LOAN', 'number': '10'},
            {'name': 'LOAN INTEREST RATE PERCENT', 'number': '11'},
            {'name': 'INCURRED', 'number': '12-'},
            {'name': 'DUE', 'number': '13-'},
            {'name': 'LOAN RESTRUCTURED', 'number': '14-A. '},
            {'name': 'OF ORIGINAL LOAN', 'number': '15-'},
            {'name': 'CREDIT AMOUNT THIS DRAW', 'number': '16-B.1.'},
            {'name': 'TOTAL BALANCE', 'number': '17-B.2.'},
            {'name': 'OTHERS LIABLE?', 'number': '18-C. '},
            {'name': 'COLLATERAL?', 'number': '19-D. '},
            {'name': 'DESC (COLLATERAL', 'number': '20-D.1'},
            {'name': 'COLLATERAL VALUE/AMOUNT', 'number': '21-D.2'},
            {'name': 'PERFECTED INTEREST?', 'number': '22-D.3 '},
            {'name': 'FUTURE INCOME PLEDGED AS COLLATERAL?', 'number': '23-E.1 '},
            {'name': 'SPECIFICATION OF THE ABOVE', 'number': '24-E.2 '},
            {'name': 'ESTIMATED VALUE', 'number': '25-E.3'},
            {'name': 'Depository account established', 'number': '26-E.4 '},
            {'name': 'ACCOUNT LOCATION', 'number': '27-E.5 '},
            {'name': 'STREET 1', 'number': '28-E.6'},
            {'name': 'STREET 2', 'number': '29-E.7'},
            {'name': 'CITY', 'number': '30-E.8'},
            {'name': 'STATE', 'number': '31-E.9'},
            {'name': 'ZIP', 'number': '32-E.10'},
            {'name': 'Presidential', 'number': '33-E.11 DEP ACCT AUTH '},
            {'name': 'IF NECESS. STATE BASIS OF LOAN', 'number': '34-F. '},
            {'name': 'TREASURER', 'number': '35-G. '},
            {'name': 'SIGNED', 'number': '36-G. '},
            {'name': 'AUTH NAME (Lending Inst Representative)', 'number': '37-H.'},
            {'name': 'AUTH TITLE (Lending Inst Representative)', 'number': '38-H.'},
            {'name': 'SIGNED', 'number': '39-H. AUTH '},
            {'name': 'AMENDED', 'number': '40'},
    ]
        self.fields_names = self.hash_names(self.fields)
