class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FEC COMMITTEE ID NUMBER', '2', '', ''],
            ['REFERENCE ID NUMBER', '3', '', ''],
            ['LOAN SOURCE', '4-', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['AMT OF LOAN', '10', '', ''],
            ['LOAN INTEREST RATE PERCENT', '11', '', ''],
            ['INCURRED', '12-', '', ''],
            ['DUE', '13-', '', ''],
            ['LOAN RESTRUCTURED', '14-A. ', '', ''],
            ['OF ORIGINAL LOAN', '15-', '', ''],
            ['CREDIT AMOUNT THIS DRAW', '16-B.1.', '', ''],
            ['TOTAL BALANCE', '17-B.2.', '', ''],
            ['OTHERS LIABLE?', '18-C. ', '', ''],
            ['COLLATERAL?', '19-D. ', '', ''],
            ['DESC (COLLATERAL', '20', 'D.1', ''],
            ['COLLATERAL VALUE/AMOUNT', '21', 'D.2', ''],
            ['PERFECTED INTEREST?', '22-D.3 ', '', ''],
            ['FUTURE INCOME PLEDGED AS COLLATERAL?', '23-E.1 ', '', ''],
            ['SPECIFICATION OF THE ABOVE', '24-E.2 ', '', ''],
            ['ESTIMATED VALUE', '25', 'E.3', ''],
            ['Depository account established', '26-E.4 ', '', ''],
            ['ACCOUNT LOCATION', '27-E.5 ', '', ''],
            ['STREET 1', '28', 'E.6', ''],
            ['STREET 2', '29', 'E.7', ''],
            ['CITY', '30', 'E.8', ''],
            ['STATE', '31', 'E.9', ''],
            ['ZIP', '32', 'E.10', ''],
            ['Presidential', '33-E.11 DEP ACCT AUTH ', '', ''],
            ['IF NECESS. STATE BASIS OF LOAN', '34-F. ', '', ''],
            ['TREASURER', '35-G. ', '', ''],
            ['SIGNED', '36-G. ', '', ''],
            ['AUTH NAME (Lending Inst Representative)', '37', 'H', ''],
            ['AUTH TITLE (Lending Inst Representative)', '38', 'H', ''],
            ['SIGNED', '39-H. AUTH ', '', ''],
            ['AMENDED', '40', '', ''],
    ]
