class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FEC COMMITTEE ID NUMBER', '2', '', ''],
            ['HAS FILER BEEN DESIG. TO MAKE CORD. EXPEND.', '3-', '', ''],
            ['FEC COMMITTEE ID NUMBER DESIGNATING CMTE', '4', '', ''],
            ['COMMITTEE NAME', '5', '', ''],
            ['STREET 1', '6', '', ''],
            ['STREET 2', '7', '', ''],
            ['CITY', '8', '', ''],
            ['STATE', '9', '', ''],
            ['ZIP', '10', '', ''],
            ['PAYEE', '11-', '', ''],
            ['STREET 1', '12', '', ''],
            ['STREET 2', '13', '', ''],
            ['CITY', '14', '', ''],
            ['STATE', '15', '', ''],
            ['ZIP', '16', '', ''],
            ['FEC CANDIDATE ID NUMBER', '17', '', ''],
            ['CANDIDATE NAME', '18', '', ''],
            ['CAN/OFF', '19', '', ''],
            ['STATE (OF ELECTION)', '20', '', ''],
            ['CAN/DIST', '21', '', ''],
            ['AGG. GEN. ELE. AMOUNT EXPENDED', '22', '', ''],
            ['TRANSDESC', '23', '', ''],
            ['DATE', '24', '', ''],
            ['AMOUNT EXPENDED', '25', '', ''],
            ['AMENDED', '26', '', ''],
    ]
