class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FEC COMMITTEE ID NUMBER', '2', '', ''],
            ['NAT PARTY COMMITTEES %', '3', '', ''],
            ['HSE/SEN PTY COMMITTEES MINIMUM FED %', '4', '', ''],
            ['HSE/SEN PTY COMMITTEES PERCENTAGE ESTIMATED FEDERAL CAN SUPPORT', '5', '', ''],
            ['HSE/SEN PTY COMMITTEES PERCENTAGE ESTIMATED NON-FEDERAL CAN SUPPORT', '6', '', ''],
            ['HSE/SEN PTY COMMITTEES ACTUAL FEDERAL CAN SUPPORT', '7', '', ''],
            ['HSE/SEN PTY COMMITTEES ACTUAL NON-FEDERAL CAN SUPPORT', '8', '', ''],
            ['HSE/SEN PTY COMMITTEES PERCENTAGE ACTUAL FEDERAL', '9', '', ''],
            ['SEP SEG FUNDS & PERCENTAGE NON-CONNECTED COMMITTEES ESTIMATED FEDERAL CANDIDATE SUPPORT', '10', '', ''],
            ['SEP SEG FUNDS & PERCENTAGE NON-CONNECTED COMMITTEES ESTIMATED NON-FEDERAL CANDIDATE SUPPORT', '11', '', ''],
            ['SEP SEG FUNDS & NON-CONNECTED COMMITTEES ACTUAL FEDERAL CANDIDATE SUPPORT', '12', '', ''],
            ['SEP SEG FUNDS & NON-CONNECTED COMMITTEES ACTUAL NON-FEDERAL CANDIDATE SUPPORT', '13', '', ''],
            ['SEP SEG FUNDS & PERCENTAGE NON-CONNECTED COMMITTEES ACTUAL FEDERAL CANDIDATE SUPPORT', '14', '', ''],
            ['BALLOT COMP PRES BLANK OR 1', '15', '1', ''],
            ['BALLOT COMP SEN BLANK OR 1', '16', '2', ''],
            ['BALLOT COMP HSE BLANK OR 1', '17', '3', ''],
            ['SUBTOTAL-FED', '18', '4', ''],
            ['BALLOT COMP GOV BLANK OR 1', '19', '5', ''],
            ['OTHER STATEWIDE', '20', '6', ''],
            ['STATE SENATE', '21', '7', ''],
            ['STATE REP', '22', '8', ''],
            ['LOCAL CANDIDATES BLANK, 1 OR 2', '23', '9', ''],
            ['EXTRA NON-FED POINT BLANK OR 1', '24', '10', ''],
            ['SUBTOTAL', '25', '11', ''],
            ['TOTAL POINTS', '26', '12', ''],
            ['FEDERAL ALLOCATION PERCENTAGE', '27', '', ''],
            ['AMENDED', '28', '', ''],
    ]
