from fec.version.records_base import RecordsBase
class Records(RecordsBase):
    def __init__(self):
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FEC COMMITTEE ID NUMBER', 'number': '2'},
            {'name': 'OF ACCOUNT', 'number': '3-'},
            {'name': 'OF RECEIPT', 'number': '4-'},
            {'name': 'TOTAL AMOUNT TRANSFERED', 'number': '5'},
            {'name': 'ADMIN/VOTER DRIVE', 'number': '6-I)'},
            {'name': 'EVENT', 'number': '7-II) a. '},
            {'name': 'ACTIVITY/EVENT NUMBER', 'number': '8'},
            {'name': 'AMOUNT TRANSFERRED FOR THIS ACTIVITY', 'number': '9'},
            {'name': 'EVENT', 'number': '10-II) b. '},
            {'name': 'ACTIVITY/EVENT NUMBER', 'number': '11'},
            {'name': 'AMOUNT TRANSFERRED FOR THIS ACTIVITY', 'number': '12'},
            {'name': 'EVENT', 'number': '13-II) c. '},
            {'name': 'ACTIVITY/EVENT NUMBER', 'number': '14'},
            {'name': 'AMOUNT TRANSFERRED FOR THIS ACTIVITY', 'number': '15'},
            {'name': 'EVENT', 'number': '16-II) d. '},
            {'name': 'ACTIVITY/EVENT NUMBER', 'number': '17'},
            {'name': 'AMOUNT TRANSFERRED FOR THIS ACTIVITY', 'number': '18'},
            {'name': 'TOT DIRECT FUNDRAISING AMOUNT', 'number': '19'},
            {'name': 'EVENT', 'number': '20-III) a. '},
            {'name': 'ACTIVITY/EVENT NUMBER', 'number': '21'},
            {'name': 'AMOUNT TRANSFERRED FOR THIS ACTIVITY', 'number': '22'},
            {'name': 'EVENT', 'number': '23-III) b. '},
            {'name': 'ACTIVITY/EVENT NUMBER', 'number': '24'},
            {'name': 'AMOUNT TRANSFERRED FOR THIS ACTIVITY', 'number': '25'},
            {'name': 'EVENT', 'number': '26-III) c. '},
            {'name': 'ACTIVITY/EVENT NUMBER', 'number': '27'},
            {'name': 'AMOUNT TRANSFERRED FOR THIS ACTIVITY', 'number': '28'},
            {'name': 'EVENT', 'number': '29-III) d. '},
            {'name': 'ACTIVITY/EVENT NUMBER', 'number': '30'},
            {'name': 'AMOUNT TRANSFERRED FOR THIS ACTIVITY', 'number': '31'},
            {'name': 'TOT EXEMPT ACTIVITY DIRECT CANDIDATE SUPPORT', 'number': '32'},
            {'name': 'AMENDED', 'number': '33'},
    ]
