class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FEC COMMITTEE ID NUMBER', '2', '', ''],
            ['OF ACCOUNT', '3-', '', ''],
            ['OF RECEIPT', '4-', '', ''],
            ['TOTAL AMOUNT TRANSFERED', '5', '', ''],
            ['ADMIN/VOTER DRIVE', '6', 'I)', ''],
            ['EVENT', '7-II) a. ', '', ''],
            ['ACTIVITY/EVENT NUMBER', '8', '', ''],
            ['AMOUNT TRANSFERRED FOR THIS ACTIVITY', '9', '', ''],
            ['EVENT', '10-II) b. ', '', ''],
            ['ACTIVITY/EVENT NUMBER', '11', '', ''],
            ['AMOUNT TRANSFERRED FOR THIS ACTIVITY', '12', '', ''],
            ['EVENT', '13-II) c. ', '', ''],
            ['ACTIVITY/EVENT NUMBER', '14', '', ''],
            ['AMOUNT TRANSFERRED FOR THIS ACTIVITY', '15', '', ''],
            ['EVENT', '16-II) d. ', '', ''],
            ['ACTIVITY/EVENT NUMBER', '17', '', ''],
            ['AMOUNT TRANSFERRED FOR THIS ACTIVITY', '18', '', ''],
            ['TOT DIRECT FUNDRAISING AMOUNT', '19', '', ''],
            ['EVENT', '20-III) a. ', '', ''],
            ['ACTIVITY/EVENT NUMBER', '21', '', ''],
            ['AMOUNT TRANSFERRED FOR THIS ACTIVITY', '22', '', ''],
            ['EVENT', '23-III) b. ', '', ''],
            ['ACTIVITY/EVENT NUMBER', '24', '', ''],
            ['AMOUNT TRANSFERRED FOR THIS ACTIVITY', '25', '', ''],
            ['EVENT', '26-III) c. ', '', ''],
            ['ACTIVITY/EVENT NUMBER', '27', '', ''],
            ['AMOUNT TRANSFERRED FOR THIS ACTIVITY', '28', '', ''],
            ['EVENT', '29-III) d. ', '', ''],
            ['ACTIVITY/EVENT NUMBER', '30', '', ''],
            ['AMOUNT TRANSFERRED FOR THIS ACTIVITY', '31', '', ''],
            ['TOT EXEMPT ACTIVITY DIRECT CANDIDATE SUPPORT', '32', '', ''],
            ['AMENDED', '33', '', ''],
    ]
