class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FEC COMMITTEE ID NUMBER', '2', '', ''],
            ['Bank Account ID Number', '3', '', ''],
            ['NAME of (ACCOUNT)', '4', '', ''],
            ['COVERAGE FROM', '5-', '', ''],
            ['COVERAGE TO', '6-', '', ''],
            ['Total Receipts', '7', '1', ''],
            ['Transfers to FED or allocation account for allocable exp.', '8', '2', ''],
            ['Transfers to state/local Party organizations', '9', '3', ''],
            ['Direct state/local candidate support', '10', '4', ''],
            ['Other Disbursements', '11', '5', ''],
            ['Total Disbursements', '12', '6', ''],
            ['Beginning COH', '13', '7', ''],
            ['Receipts', '14', '8', ''],
            ['Subtotal', '15', '9', ''],
            ['Disbursements', '16', '10', ''],
            ['Ending COH', '17', '11', ''],
            ['Total receipts', '18', '1', ''],
            ['Transfers to FED or allocation account for allocable exp.', '19', '2', ''],
            ['Transfers to state/local Party organizations', '20', '3', ''],
            ['Direct state/local candidate support', '21', '4', ''],
            ['Other Disbursements', '22', '5', ''],
            ['Total Disbursements', '23', '6', ''],
            ['Beginning COH (as of Jan 1)', '24', '7', ''],
            ['Receipts', '25', '8', ''],
            ['Subtotal', '26', '9', ''],
            ['Disbursements', '27', '10', ''],
            ['Ending COH', '28', '11', ''],
            ['AMENDED', '29', '', ''],
    ]
