class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['CHANGE OF ADDRESS', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['ELECTION STATE', '10', '', ''],
            ['ELECTION DISTRICT', '11', '', ''],
            ['REPORT CODE', '12', '', ''],
            ['ELECTION CODE', '13', '', ''],
            ['DATE OF ELECTION', '14', '', ''],
            ['STATE OF ELECTION', '15', '', ''],
            ['COVERAGE FROM DATE', '16', '', ''],
            ['COVERAGE THROUGH DATE', '17', '', ''],
            ['TREASURER LAST NAME', '18', '', ''],
            ['TREASURER FIRST NAME', '19', '', ''],
            ['TREASURER MIDDLE NAME', '20', '', ''],
            ['TREASURER PREFIX', '21', '', ''],
            ['TREASURER SUFFIX', '22', '', ''],
            ['DATE SIGNED', '23', '', ''],
            ['Total Contributions (NO Loans)', '24', '6a', ''],
            ['Total Contribution Refunds', '25', '6b', ''],
            ['Net Contributions', '26', '6c', ''],
            ['Total Operating Expenditures', '27', '7a', ''],
            ['Total Offset to Operating Expenditures', '28', '7b', ''],
            ['NET Operating Expenditures.', '29', '7c', ''],
            ['CASH ON HAND AT CLOSE ...', '30', '8', ''],
            ['DEBTS TO ( Totals from SCH C and/or D)', '31', '9', ''],
            ['DEBTS BY (Totals from SCH C and/or D)', '32', '10', ''],
            ['Individuals Itemized', '33', '11', 'a i.'],
            ['Individuals Unitemized', '34', '11', 'a.ii'],
            ['Individual Contribution Total', '35', '11', 'a.iii'],
            ['Political Party Committees', '36', '11', 'b'],
            ['Other Political Committees', '37', '11', 'c'],
            ['The Candidate', '38', '11', 'd'],
            ['Total Contributions', '39', '11', 'e'],
            ['Transfers From Other Authorized Committees', '40', '12', ''],
            ['Loans made or guarn. by the Candidate', '41', '13', 'a'],
            ['All Other Loans', '42', '13', 'b'],
            ['Total Loans', '43', '13', 'c'],
            ['Offsets to Operating Expenditures', '44', '14', ''],
            ['Other Receipts', '45', '15', ''],
            ['Total Receipts', '46', '16', ''],
            ['Operating Expenditures', '47', '17', ''],
            ['Transfers to Other Authorized Committees', '48', '18', ''],
            ['Of Loans made or guar. by the Cand.', '49', '19', 'a'],
            ['Loan Repayments, All Other Loans', '50', '19', 'b'],
            ['Total Loan Repayments', '51', '19', 'c'],
            ['Refund/Individuals Other than Political Committees', '52', '20', 'a'],
            ['Refund/Political Party Committees', '53', '20', 'b'],
            ['Refund/Other Political Committees', '54', '20', 'c'],
            ['Total Contribution Refunds', '55', '20', 'd'],
            ['Other Disbursements', '56', '21', ''],
            ['Total Disbursements', '57', '22', ''],
            ['Cash Beginning Reporting Period', '58', '23', ''],
            ['Total Receipts this Period', '59', '24', ''],
            ['Subtotals', '60', '25', ''],
            ['Total Disbursements this Period', '61', '26', ''],
            ['Cash on hand at Close Period', '62', '27', ''],
            ['Total Contributions (No Loans)', '63', '6a', ''],
            ['Total Contribution Refunds', '64', '6b', ''],
            ['Net Contributions', '65', '6c', ''],
            ['Total Operating Expenditures', '66', '7a', ''],
            ['Total Offsets to Operating Expenditures', '67', '7b', ''],
            ['NET Operating Expenditures.', '68', '7c', ''],
            ['Individuals Itemized', '69', '11', 'a i.'],
            ['Individuals Unitemized', '70', '11', 'a.ii'],
            ['Individuals Total', '71', '11', 'a.iii'],
            ['Political Party Committees', '72', '11', 'b'],
            ['All Other Political Committees (PACS)', '73', '11', 'c'],
            ['The Candidate', '74', '11', 'd'],
            ['Total Contributions', '75', '11', 'e'],
            ['Transfers From Other AUTH Committees', '76', '12', ''],
            ['Loans made or guarn. by the Candidate', '77', '13', 'a'],
            ['All Other Loans', '78', '13', 'b'],
            ['Total Loans', '79', '13', 'c'],
            ['Offsets to Operating Expenditures', '80', '14', ''],
            ['Other Receipts', '81', '15', ''],
            ['Total Receipts', '82', '16', ''],
            ['Operating Expenditures', '83', '17', ''],
            ['Transfers To Other AUTH Committees', '84', '18', ''],
            ['Loan Repayment By Candidate', '85', '19', 'a'],
            ['Loan Repayments, ALL Other Loans', '86', '19', 'b'],
            ['Total Loan Repayments', '87', '19', 'c'],
            ['Refund/Individuals Other than Political Committees', '88', '20', 'a'],
            ['Refund, Political Party Committees', '89', '20', 'b'],
            ['Refund, Other Political Committees', '90', '20', 'c'],
            ['Total Contributions Refunds', '91', '20', 'd'],
            ['Other Disbursements', '92', '21', ''],
            ['Total Disbursements', '93', '22', ''],
    ]
