class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['CHANGE OF ADDRESS', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['ELECTION STATE', '10', '', ''],
            ['ELECTION DISTRICT', '11', '', ''],
            ['REPORT CODE', '12', '', ''],
            ['DATE OF ELECTION', '13', '', ''],
            ['STATE OF ELECTION', '14', '', ''],
            ['SEMI-ANNUAL PERIOD - Sect 5(c) or (d)', '15', '', ''],
            ['COVERAGE FROM DATE', '16', '', ''],
            ['COVERAGE THROUGH DATE', '17', '', ''],
            ['SEMI-ANNUAL JAN-JUN - Sect 6(b)', '18', '', ''],
            ['SEMI-ANNUAL JUL-DEC - Sect 6(b)', '19', '', ''],
            ['QTR/MON/POST BUNDLED CONTRIBUTIONS', '20', '', ''],
            ['SEMI-ANNUAL BUNDLED CONTRIBS', '21', '', ''],
            ['TREASURER LAST NAME', '22', '', ''],
            ['TREASURER FIRST NAME', '23', '', ''],
            ['TREASURER MIDDLE NAME', '24', '', ''],
            ['TREASURER PREFIX', '25', '', ''],
            ['TREASURER SUFFIX', '26', '', ''],
            ['DATE SIGNED', '27', '', ''],
    ]
