class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['Date - General Election', '3', '', ''],
            ['Date - Day after General Election', '4', '', ''],
            ['Net Contributions', '5', '14', ''],
            ['Net Expenditures', '6', '15', ''],
            ['Federal Funds', '7', '16', ''],
            ['Individuals Itemized', '8', '17', 'a.i'],
            ['Individuals Unitemized', '9', '17', 'a.ii'],
            ['Individual Contribution Total', '10', '17', 'a.iii'],
            ['Political Party Committees', '11', '17', 'b'],
            ['Other Political Committees (PACs)', '12', '17', 'c'],
            ['The Candidate', '13', '17', 'd'],
            ['Total contributions (Other than Loans)', '14', '17', 'e'],
            ['Transfers From Aff/Other Party Committees', '15', '18', ''],
            ['Received from or Guaranteed by Candidate', '16', '19', 'a'],
            ['Other Loans', '17', '19', 'b'],
            ['Total Loans', '18', '19', 'c'],
            ['Operating', '19', '20', 'a'],
            ['Fundraising', '20', '20', 'b'],
            ['Legal and Accounting', '21', '20', 'c'],
            ['Total Offsets to Operating Expenditures', '22', '20', 'd'],
            ['Other Receipts', '23', '21', ''],
            ['Total Receipts', '24', '22', ''],
            ['Operating Expenditures', '25', '23', ''],
            ['Transfers to Other Authorized Committees', '26', '24', ''],
            ['Fundraising Disbursements', '27', '25', ''],
            ['Exempt Legal and Accounting Disbursements', '28', '26', ''],
            ['Made or Guaranteed by the Candidate', '29', '27', 'a'],
            ['Other Repayments', '30', '27', 'b'],
            ['Total Loan Repayments Made', '31', '27', 'c'],
            ['Individuals', '32', '28', 'a'],
            ['Political Party Committees', '33', '28', 'b'],
            ['Other Political Committees', '34', '28', 'c'],
            ['Total Contributions Refunds', '35', '28', 'd'],
            ['Other Disbursements', '36', '29', ''],
            ['Total Disbursements', '37', '30', ''],
            ['ALABAMA', '38', '', ''],
            ['ALASKA', '39', '', ''],
            ['ARIZONA', '40', '', ''],
            ['ARKANSAS', '41', '', ''],
            ['CALIFORNIA', '42', '', ''],
            ['COLORADO', '43', '', ''],
            ['CONNECTICUT', '44', '', ''],
            ['DELAWARE', '45', '', ''],
            ['DIST OF COLUMBIA', '46', '', ''],
            ['FLORIDA', '47', '', ''],
            ['GEORGIA', '48', '', ''],
            ['HAWAII', '49', '', ''],
            ['IDAHO', '50', '', ''],
            ['ILLINOIS', '51', '', ''],
            ['INDIANA', '52', '', ''],
            ['IOWA', '53', '', ''],
            ['KANSAS', '54', '', ''],
            ['KENTUCKY', '55', '', ''],
            ['LOUISIANA', '56', '', ''],
            ['MAINE', '57', '', ''],
            ['MARYLAND', '58', '', ''],
            ['MASSACHUSETTS', '59', '', ''],
            ['MICHIGAN', '60', '', ''],
            ['MINNESOTA', '61', '', ''],
            ['MISSISSIPPI', '62', '', ''],
            ['MISSOURI', '63', '', ''],
            ['MONTANA', '64', '', ''],
            ['NEBRASKA', '65', '', ''],
            ['NEVADA', '66', '', ''],
            ['NEW HAMPSHIRE', '67', '', ''],
            ['NEW JERSEY', '68', '', ''],
            ['NEW MEXICO', '69', '', ''],
            ['NEW YORK', '70', '', ''],
            ['NORTH CAROLINA', '71', '', ''],
            ['NORTH DAKOTA', '72', '', ''],
            ['OHIO', '73', '', ''],
            ['OKLAHOMA', '74', '', ''],
            ['OREGON', '75', '', ''],
            ['PENNSYLVANIA', '76', '', ''],
            ['RHODE ISLAND', '77', '', ''],
            ['SOUTH CAROLINA', '78', '', ''],
            ['SOUTH DAKOTA', '79', '', ''],
            ['TENNESSEE', '80', '', ''],
            ['TEXAS', '81', '', ''],
            ['UTAH', '82', '', ''],
            ['VERMONT', '83', '', ''],
            ['VIRGINIA', '84', '', ''],
            ['WASHINGTON', '85', '', ''],
            ['WEST VIRGINIA', '86', '', ''],
            ['WISCONSIN', '87', '', ''],
            ['WYOMING', '88', '', ''],
            ['PUERTO RICO', '89', '', ''],
            ['GUAM', '90', '', ''],
            ['VIRGIN ISLANDS', '91', '', ''],
            ['TOTALS', '92', '', ''],
    ]
