class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['COMMITTEE/ORG TYPE', '9', '', ''],
            ['COMMITTEE/ORG TYPE - OTHER DESCRIPTION', '10', '', ''],
            ['REPORT CODE', '11', '', ''],
            ['COVERAGE FROM DATE', '12', '', ''],
            ['COVERAGE THROUGH DATE', '13', '', ''],
            ['TREASURER LAST NAME', '14', '', ''],
            ['TREASURER FIRST NAME', '15', '', ''],
            ['TREASURER MIDDLE NAME', '16', '', ''],
            ['TREASURER PREFIX', '17', '', ''],
            ['TREASURER SUFFIX', '18', '', ''],
            ['DATE SIGNED', '19', '', ''],
            ['cash on hand beg. report per.', '20', '6', ''],
            ['Total receipts', '21', '6', ''],
            ['Subtotal', '22', '6', ''],
            ['Total disbursements', '23', '7', ''],
            ['COH CLOSE (COL A)', '24', '8', ''],
            ['Debts to', '25', '9', ''],
            ['Debts by', '26', '10', ''],
            ['Convention expenditures', '27', '11', ''],
            ['refunds/rebates/returns relating to conv exp.', '28', '12', ''],
            ['Expenditures subject to limits', '29', '12', 'a'],
            ['expend. from prior years subject to limits', '30', '12', 'b'],
            ['Federal Funds SCH A', '31', '13', ''],
            ['Itemized', '32', '14', 'a'],
            ['unitemized', '33', '14', 'b'],
            ['subtotal', '34', '14', 'c'],
            ['Transfers from affiliated Committees.', '35', '15', ''],
            ['loans received', '36', '16', 'a'],
            ['loan repayments received', '37', '16', 'b'],
            ['subtotal loans/repayments', '38', '16', 'c'],
            ['Itemized', '39', '17', 'a'],
            ['unitemized', '40', '17', 'b'],
            ['subtotal', '41', '17', 'c'],
            ['Itemized', '42', '18', 'a'],
            ['unitemized', '43', '18', 'b'],
            ['subtotal', '44', '18', 'c'],
            ['Itemized', '45', '19', 'a'],
            ['unitemized', '46', '19', 'b'],
            ['subtotal', '47', '19', 'c'],
            ['total receipts', '48', '20', ''],
            ['Itemized', '49', '21', 'a'],
            ['unitemized', '50', '21', 'b'],
            ['subtotal', '51', '21', 'c'],
            ['Transfers to Affiliated Committees', '52', '22', ''],
            ['loans made', '53', '23', 'a'],
            ['loan repayments made', '54', '23', 'b'],
            ['subtotal', '55', '23', 'c'],
            ['Itemized', '56', '24', 'a'],
            ['unitemized', '57', '24', 'b'],
            ['subtotal', '58', '24', 'c'],
            ['Total disbursements', '59', '25', ''],
            ['Cash on Hand', '60', '6', ''],
            ['YEAR', '61', '6.(a) 19', ''],
            ['Total receipts', '62', '6', ''],
            ['Subtotal', '63', '6', ''],
            ['Total disbursements', '64', '7', ''],
            ['COH CLOSE (COL B)', '65', '8', ''],
            ['Convention expenditures', '66', '11', ''],
            ['refunds/rebates/returns relating to conv exp.', '67', '12', ''],
            ['Expenditures subject to limits', '68', '12', 'a'],
            ['expend. from prior years subject to limits', '69', '12', 'b'],
            ['total expenditures subject to limits', '70', '12', 'c'],
            ['Federal Funds', '71', '13', ''],
            ['subtotal', '72', '14', 'c'],
            ['Transfers from affiliated Committees.', '73', '15', ''],
            ['subtotal loans/repayments', '74', '16', 'c'],
            ['subtotal', '75', '17', 'c'],
            ['subtotal', '76', '18', 'c'],
            ['subtotal', '77', '19', 'c'],
            ['total receipts', '78', '20', ''],
            ['subtotal', '79', '21', 'c'],
            ['Transfers to Affiliated Committees', '80', '22', ''],
            ['subtotal', '81', '23', 'c'],
            ['subtotal', '82', '24', 'c'],
            ['Total disbursements', '83', '25', ''],
    ]
