class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['ORGANIZATION NAME', '4', '', ''],
            ['INDIVIDUAL LAST NAME', '5', '', ''],
            ['INDIVIDUAL FIRST NAME', '6', '', ''],
            ['INDIVIDUAL MIDDLE NAME', '7', '', ''],
            ['INDIVIDUAL PREFIX', '8', '', ''],
            ['INDIVIDUAL SUFFIX', '9', '', ''],
            ['CHANGE OF ADDRESS', '10', '', ''],
            ['STREET 1', '11', '', ''],
            ['STREET 2', '12', '', ''],
            ['CITY', '13', '', ''],
            ['STATE', '14', '', ''],
            ['ZIP', '15', '', ''],
            ['Qualified Non-Profit Corporation', '16-', '', ''],
            ['INDIVIDUAL EMPLOYER', '17', '', ''],
            ['INDIVIDUAL OCCUPATION', '18', '', ''],
            ['REPORT CODE', '19', '', ''],
            ['HOUR 48HOUR CODE', '20', '24', ''],
            ['COVERAGE FROM DATE', '21', '', ''],
            ['COVERAGE THROUGH DATE', '22', '', ''],
            ['TOTAL CONTRIBUTION', '23', '', ''],
            ['TOTAL INDEPENDENT EXPENDITURE', '24', '', ''],
            ['PERSON COMPLETING LAST NAME', '25', '', ''],
            ['PERSON COMPLETING FIRST NAME', '26', '', ''],
            ['PERSON COMPLETING MIDDLE NAME', '27', '', ''],
            ['PERSON COMPLETING PREFIX', '28', '', ''],
            ['PERSON COMPLETING SUFFIX', '29', '', ''],
            ['DATE SIGNED', '30', '', ''],
    ]
