class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['ORIGINAL AMENDMENT DATE', '3', '', ''],
            ['COMMITTEE NAME', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['CANDIDATE ID NUMBER', '10', '', ''],
            ['CANDIDATE LAST NAME', '11', '', ''],
            ['CANDIDATE FIRST NAME', '12', '', ''],
            ['CANDIDATE MIDDLE NAME', '13', '', ''],
            ['CANDIDATE PREFIX', '14', '', ''],
            ['CANDIDATE SUFFIX', '15', '', ''],
            ['CANDIDATE OFFICE', '16', '', ''],
            ['CANDIDATE STATE', '17', '', ''],
            ['CANDIDATE DISTRICT', '18', '', ''],
            ['SIGNER LAST NAME', '19', '', ''],
            ['SIGNER FIRST NAME', '20', '', ''],
            ['SIGNER MIDDLE NAME', '21', '', ''],
            ['SIGNER PREFIX', '22', '', ''],
            ['SIGNER SUFFIX', '23', '', ''],
            ['DATE SIGNED', '24', '', ''],
    ]
