class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['ORGANIZATION NAME', '4', '', ''],
            ['INDIVIDUAL LAST NAME', '5', '', ''],
            ['INDIVIDUAL FIRST NAME', '6', '', ''],
            ['INDIVIDUAL MIDDLE NAME', '7', '', ''],
            ['INDIVIDUAL PREFIX', '8', '', ''],
            ['INDIVIDUAL SUFFIX', '9', '', ''],
            ['CHANGE OF ADDRESS', '10', '', ''],
            ['STREET 1', '11', '', ''],
            ['STREET 2', '12', '', ''],
            ['CITY', '13', '', ''],
            ['STATE', '14', '', ''],
            ['ZIP', '15', '', ''],
            ['INDIVIDUAL EMPLOYER', '16', '', ''],
            ['INDIVIDUAL OCCUPATION', '17', '', ''],
            ['COVERAGE FROM DATE', '18', '', ''],
            ['COVERAGE THROUGH DATE', '19', '', ''],
            ['DATE OF PUBLIC DISTRIBUTION', '20', '', ''],
            ['COMMUNICATION TITLE', '21', '', ''],
            ['FILER CODE', '22', '', ''],
            ['FILER CODE DESCRIPTION', '23', '', ''],
            ['SEGREGATED BANK ACCOUNT', '24', '', ''],
            ['CUSTODIAN LAST NAME', '25', '', ''],
            ['CUSTODIAN FIRST NAME', '26', '', ''],
            ['CUSTODIAN MIDDLE NAME', '27', '', ''],
            ['CUSTODIAN PREFIX', '28', '', ''],
            ['CUSTODIAN SUFFIX', '29', '', ''],
            ['CUSTODIAN STREET 1', '30', '', ''],
            ['CUSTODIAN STREET 2', '31', '', ''],
            ['CUSTODIAN CITY', '32', '', ''],
            ['CUSTODIAN STATE', '33', '', ''],
            ['CUSTODIAN ZIP', '34', '', ''],
            ['CUSTODIAN EMPLOYER', '35', '', ''],
            ['CUSTODIAN OCCUPATION', '36', '', ''],
            ['TOTAL DONATIONS THIS STATEMENT', '37', '9', ''],
            ['TOTAL DISB./OBLIG. THIS STATEMENT', '38', '10', ''],
            ['PERSON COMPLETING LAST NAME', '39', '', ''],
            ['PERSON COMPLETING FIRST NAME', '40', '', ''],
            ['PERSON COMPLETING MIDDLE NAME', '41', '', ''],
            ['PERSON COMPLETING PREFIX', '42', '', ''],
            ['PERSON COMPLETING SUFFIX', '43', '', ''],
            ['DATE SIGNED', '44', '', ''],
    ]
