class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['BACK REFERENCE TRAN ID NUMBER', '4', '', ''],
            ['BACK REFERENCE SCHED NAME', '5', '', ''],
            ['ENTITY TYPE', '6', '', ''],
            ['PAYEE ORGANIZATION NAME', '7', '', ''],
            ['PAYEE LAST NAME', '8', '', ''],
            ['PAYEE FIRST NAME', '9', '', ''],
            ['PAYEE MIDDLE NAME', '10', '', ''],
            ['PAYEE PREFIX', '11', '', ''],
            ['PAYEE SUFFIX', '12', '', ''],
            ['PAYEE STREET 1', '13', '', ''],
            ['PAYEE STREET 2', '14', '', ''],
            ['PAYEE CITY', '15', '', ''],
            ['PAYEE STATE', '16', '', ''],
            ['PAYEE ZIP', '17', '', ''],
            ['ELECTION CODE', '18', '', ''],
            ['ELECTION OTHER DESCRIPTION', '19', '', ''],
            ['EXPENDITURE DATE', '20', '', ''],
            ['EXPENDITURE AMOUNT', '21', '', ''],
            ['EXPENDITURE PURPOSE DESCRIP', '22', '', ''],
            ['PAYEE EMPLOYER', '23', '', ''],
            ['PAYEE OCCUPATION', '24', '', ''],
            ['COMMUNICATION DATE', '25', '', ''],
    ]
