class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID', '3', '', ''],
            ['BACK REFERENCE TRAN ID NUMBER', '4', '', ''],
            ['BACK REFERENCE SCHED NAME', '5', '', ''],
            ['ENTITY TYPE', '6', '', ''],
            ['CONTRIBUTOR ORGANIZATION NAME', '7', '', ''],
            ['CONTRIBUTOR LAST NAME', '8', '', ''],
            ['CONTRIBUTOR FIRST NAME', '9', '', ''],
            ['CONTRIBUTOR MIDDLE NAME', '10', '', ''],
            ['CONTRIBUTOR PREFIX', '11', '', ''],
            ['CONTRIBUTOR SUFFIX', '12', '', ''],
            ['CONTRIBUTOR STREET 1', '13', '', ''],
            ['CONTRIBUTOR STREET 2', '14', '', ''],
            ['CONTRIBUTOR CITY', '15', '', ''],
            ['CONTRIBUTOR STATE', '16', '', ''],
            ['CONTRIBUTOR ZIP', '17', '', ''],
            ['ELECTION CODE', '18', '', ''],
            ['ELECTION OTHER DESCRIPTION', '19', '', ''],
            ['CONTRIBUTION DATE', '20', '', ''],
            ['CONTRIBUTION AMOUNT (F3L Bundled)', '21', '', ''],
            ['CONTRIBUTION AGGREGATE F3L Semi-annual Bundled', '22', '', ''],
            ['CONTRIBUTION PURPOSE DESCRIP', '23', '', ''],
            ['CONTRIBUTOR EMPLOYER', '24', '', ''],
            ['CONTRIBUTOR OCCUPATION', '25', '', ''],
            ['DONOR COMMITTEE FEC ID', '26', '', ''],
            ['DONOR COMMITTEE NAME', '27', '', ''],
            ['DONOR CANDIDATE FEC ID', '28', '', ''],
            ['DONOR CANDIDATE LAST NAME', '29', '', ''],
            ['DONOR CANDIDATE FIRST NAME', '30', '', ''],
            ['DONOR CANDIDATE MIDDLE NAME', '31', '', ''],
            ['DONOR CANDIDATE PREFIX', '32', '', ''],
            ['DONOR CANDIDATE SUFFIX', '33', '', ''],
            ['DONOR CANDIDATE OFFICE', '34', '', ''],
            ['DONOR CANDIDATE STATE', '35', '', ''],
            ['DONOR CANDIDATE DISTRICT', '36', '', ''],
            ['CONDUIT NAME', '37', '', ''],
            ['CONDUIT STREET1', '38', '', ''],
            ['CONDUIT STREET2', '39', '', ''],
            ['CONDUIT CITY', '40', '', ''],
            ['CONDUIT STATE', '41', '', ''],
            ['CONDUIT ZIP', '42', '', ''],
            ['MEMO CODE', '43', '', ''],
            ['MEMO TEXT/DESCRIPTION', '44', '', ''],
            ['Reference to SI or SL system code that identifies the Account', '45', '', ''],
    ]
