class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['BACK REFERENCE TRAN ID NUMBER', '4', '', ''],
            ['BACK REFERENCE SCHED NAME', '5', '', ''],
            ['ENTITY TYPE', '6', '', ''],
            ['PAYEE ORGANIZATION NAME', '7', '', ''],
            ['PAYEE LAST NAME', '8', '', ''],
            ['PAYEE FIRST NAME', '9', '', ''],
            ['PAYEE MIDDLE NAME', '10', '', ''],
            ['PAYEE PREFIX', '11', '', ''],
            ['PAYEE SUFFIX', '12', '', ''],
            ['PAYEE STREET 1', '13', '', ''],
            ['PAYEE STREET 2', '14', '', ''],
            ['PAYEE CITY', '15', '', ''],
            ['PAYEE STATE', '16', '', ''],
            ['PAYEE ZIP', '17', '', ''],
            ['ELECTION CODE', '18', '', ''],
            ['ELECTION OTHER DESCRIPTION', '19', '', ''],
            ['EXPENDITURE DATE', '20', '', ''],
            ['EXPENDITURE AMOUNT (F3L Bundled)', '21', '', ''],
            ['SEMI-ANNUAL REFUNDED BUNDLED AMT', '22', '', ''],
            ['EXPENDITURE PURPOSE DESCRIP', '23', '', ''],
            ['CATEGORY CODE', '24', '', ''],
            ['BENEFICIARY COMMITTEE FEC ID', '25', '', ''],
            ['BENEFICIARY COMMITTEE NAME', '26', '', ''],
            ['BENEFICIARY CANDIDATE FEC ID', '27', '', ''],
            ['BENEFICIARY CANDIDATE LAST NAME', '28', '', ''],
            ['BENEFICIARY CANDIDATE FIRST NAME', '29', '', ''],
            ['BENEFICIARY CANDIDATE MIDDLE NAME', '30', '', ''],
            ['BENEFICIARY CANDIDATE PREFIX', '31', '', ''],
            ['BENEFICIARY CANDIDATE SUFFIX', '32', '', ''],
            ['BENEFICIARY CANDIDATE OFFICE', '33', '', ''],
            ['BENEFICIARY CANDIDATE STATE', '34', '', ''],
            ['BENEFICIARY CANDIDATE DISTRICT', '35', '', ''],
            ['CONDUIT NAME', '36', '', ''],
            ['CONDUIT STREET 1', '37', '', ''],
            ['CONDUIT STREET 2', '38', '', ''],
            ['CONDUIT CITY', '39', '', ''],
            ['CONDUIT STATE', '40', '', ''],
            ['CONDUIT ZIP', '41', '', ''],
            ['MEMO CODE', '42', '', ''],
            ['MEMO TEXT/DESCRIPTION', '43', '', ''],
            ['Reference to SI or SL system code that identifies the Account', '44', '', ''],
    ]
