import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER COMMITTEE ID NUMBER', 'number': '2'},
            {'name': 'TRANSACTION ID NUMBER', 'number': '3'},
            {'name': 'BACK REFERENCE TRAN ID NUMBER', 'number': '4'},
            {'name': 'LENDER ORGANIZATION NAME', 'number': '5'},
            {'name': 'LENDER STREET 1', 'number': '6'},
            {'name': 'LENDER STREET 2', 'number': '7'},
            {'name': 'LENDER CITY', 'number': '8'},
            {'name': 'LENDER STATE', 'number': '9'},
            {'name': 'LENDER ZIP', 'number': '10'},
            {'name': 'LOAN AMOUNT', 'number': '11'},
            {'name': 'LOAN INTEREST RATE %', 'number': '12'},
            {'name': 'LOAN INCURRED DATE', 'number': '13'},
            {'name': 'LOAN DUE DATE', 'number': '14'},
            {'name': 'Loan Restructured', 'number': '15-A1.'},
            {'name': 'Of Original Loan', 'number': '16-A2. '},
            {'name': 'CREDIT AMOUNT THIS DRAW', 'number': '17-B.1.'},
            {'name': 'TOTAL BALANCE', 'number': '18-B.2.'},
            {'name': 'Others liable?', 'number': '19-C. '},
            {'name': 'Collateral?', 'number': '20-D. '},
            {'name': 'Collateral', 'number': '21-D.1 '},
            {'name': 'COLLATERAL VALUE/AMOUNT', 'number': '22-D.2'},
            {'name': 'Perfected Interest?)', 'number': '23-D.3 '},
            {'name': 'Future Income', 'number': '24-E.1 '},
            {'name': 'Specification of the above', 'number': '25-E.2 '},
            {'name': 'ESTIMATED VALUE', 'number': '26-E.3'},
            {'name': 'Depository account established', 'number': '27-E.4 '},
            {'name': 'Account Location', 'number': '28-E.5 '},
            {'name': 'STREET 1', 'number': '29-E.6'},
            {'name': 'STREET 2', 'number': '30-E.7'},
            {'name': 'CITY', 'number': '31-E.8'},
            {'name': 'STATE', 'number': '32-E.9'},
            {'name': 'ZIP', 'number': '33-E.10'},
            {'name': 'Presidential', 'number': '34-E.11 DEP ACCT AUTH '},
            {'name': 'BASIS OF LOAN DESCRIPTION', 'number': '35-F.'},
            {'name': 'TREASURER LAST NAME', 'number': '36-G.'},
            {'name': 'TREASURER FIRST NAME', 'number': '37-G.'},
            {'name': 'TREASURER MIDDLE NAME', 'number': '38-G.'},
            {'name': 'TREASURER PREFIX', 'number': '39-G.'},
            {'name': 'TREASURER SUFFIX', 'number': '40-G.'},
            {'name': 'DATE SIGNED', 'number': '41-G.'},
            {'name': 'AUTHORIZED LAST NAME', 'number': '42-H.'},
            {'name': 'AUTHORIZED FIRST NAME', 'number': '43-H.'},
            {'name': 'AUTHORIZED MIDDLE NAME', 'number': '44-H.'},
            {'name': 'AUTHORIZED PREFIX', 'number': '45-H.'},
            {'name': 'AUTHORIZED SUFFIX', 'number': '46-H.'},
            {'name': 'AUTHORIZED TITLE', 'number': '47-H.'},
            {'name': 'DATE SIGNED', 'number': '48-H.'},
    ]
        self.fields_names = self.hash_names(self.fields)
