class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['BACK REFERENCE TRAN ID NUMBER', '4', '', ''],
            ['BACK REFERENCE SCHED NAME', '5', '', ''],
            ['ENTITY TYPE', '6', '', ''],
            ['PAYEE ORGANIZATION NAME', '7', '', ''],
            ['PAYEE LAST NAME', '8', '', ''],
            ['PAYEE FIRST NAME', '9', '', ''],
            ['PAYEE MIDDLE NAME', '10', '', ''],
            ['PAYEE PREFIX', '11', '', ''],
            ['PAYEE SUFFIX', '12', '', ''],
            ['PAYEE STREET 1', '13', '', ''],
            ['PAYEE STREET 2', '14', '', ''],
            ['PAYEE CITY', '15', '', ''],
            ['PAYEE STATE', '16', '', ''],
            ['PAYEE ZIP', '17', '', ''],
            ['ELECTION CODE', '18', '', ''],
            ['ELECTION OTHER DESCRIPTION', '19', '', ''],
            ['EXPENDITURE DATE', '20', '', ''],
            ['EXPENDITURE AMOUNT', '21', '', ''],
            ['CALENDAR Y-T-D (per election/office)', '22', '', ''],
            ['EXPENDITURE PURPOSE DESCRIP', '23', '', ''],
            ['CATEGORY CODE', '24', '', ''],
            ['PAYEE Committee FEC ID NUMBER', '25', '', ''],
            ['SUPPORT/OPPOSE CODE', '26', '', ''],
            ['S/O CANDIDATE ID NUMBER', '27', '', ''],
            ['S/O CANDIDATE LAST NAME', '28', '', ''],
            ['S/O CANDIDATE FIRST NAME', '29', '', ''],
            ['S/O CANDINATE MIDDLE NAME', '30', '', ''],
            ['S/O CANDIDATE PREFIX', '31', '', ''],
            ['S/O CANDIDATE SUFFIX', '32', '', ''],
            ['S/O CANDIDATE OFFICE', '33', '', ''],
            ['S/O CANDIDATE STATE', '34', '', ''],
            ['S/O CANDIDATE DISTRICT', '35', '', ''],
            ['COMPLETING LAST NAME', '36', '', ''],
            ['COMPLETING FIRST NAME', '37', '', ''],
            ['COMPLETING MIDDLE NAME', '38', '', ''],
            ['COMPLETING PREFIX', '39', '', ''],
            ['COMPLETING SUFFIX', '40', '', ''],
            ['DATE SIGNED', '41', '', ''],
            ['MEMO CODE', '42', '', ''],
            ['MEMO TEXT/DESCRIPTION', '43', '', ''],
    ]
