class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['BACK REFERENCE TRAN ID NUMBER', '4', '', ''],
            ['BACK REFERENCE SCHED NAME', '5', '', ''],
            ['ENTITY TYPE', '6', '', ''],
            ['PAYEE ORGANIZATION NAME', '7', '', ''],
            ['PAYEE LAST NAME', '8', '', ''],
            ['PAYEE FIRST NAME', '9', '', ''],
            ['PAYEE MIDDLE NAME', '10', '', ''],
            ['PAYEE PREFIX', '11', '', ''],
            ['PAYEE SUFFIX', '12', '', ''],
            ['PAYEE STREET 1', '13', '', ''],
            ['PAYEE STREET 2', '14', '', ''],
            ['PAYEE CITY', '15', '', ''],
            ['PAYEE STATE', '16', '', ''],
            ['PAYEE ZIP', '17', '', ''],
            ['ACCOUNT/EVENT IDENTIFIER', '18', '', ''],
            ['EXPENDITURE DATE', '19', '', ''],
            ['TOTAL FED-NONFED AMOUNT', '20', '', ''],
            ['FEDERAL SHARE', '21', '', ''],
            ['NONFEDERAL SHARE', '22', '', ''],
            ['ACTIVITY/EVENT TOTAL YTD', '23', '', ''],
            ['EXPENDITURE PURPOSE DESCRIP', '24', '', ''],
            ['CATEGORY CODE', '25', '', ''],
            ['Activity is Administrative - Only', '26-', '', ''],
            ['Activity is Direct Fundraising', '27-', '', ''],
            ['Activity is an Exempt Activity', '28-', '', ''],
            ['Activity is Generic Voter Drive - Only', '29-', '', ''],
            ['Activity is Direct Candidate Support', '30-', '', ''],
            ['Activity is Party Public Communications Made by PAC', '31-', '', ''],
            ['MEMO CODE', '32', '', ''],
            ['MEMO TEXT/DESCRIPTION', '33', '', ''],
    ]
