class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['RECORD ID NUMBER (for account name)', '4', '', ''],
            ['ACCOUNT NAME', '5', '', ''],
            ['COVERAGE FROM DATE', '6', '', ''],
            ['COVERAGE THROUGH DATE', '7', '', ''],
            ['Itemized Receipts From Persons', '8', '1', ''],
            ['Unitemized Receipts From Persons', '9', '1', ''],
            ['Total Receipts From Persons', '10', '1', ''],
            ['OTHER RECEIPTS', '11', '2', ''],
            ['TOTAL RECEIPTS', '12', '3', ''],
            ['Voter Registration DISBURSEMENTS', '13', '4', 'a'],
            ['Voter ID DISBURSEMENTS', '14', '4', 'b'],
            ['GOTV DISBURSEMENTS', '15', '4', 'c'],
            ['Generic Campaign DISBURSEMENTS', '16', '4', 'd'],
            ['Line 4 Total', '17', '4', 'e'],
            ['OTHER DISBURSEMENTS', '18', '5', ''],
            ['TOTAL DISBURSEMENTS', '19', '6', ''],
            ['CASH ON HAND (Beginning)', '20', '7', ''],
            ['RECEIPTS', '21', '8', ''],
            ['SUBTOTAL', '22', '9', ''],
            ['DISBURSEMENTS', '23', '10', ''],
            ['ENDING CASH ON HAND', '24', '11', ''],
            ['Itemized Receipts From Persons', '25', '1', ''],
            ['Unitemized Receipts From Persons', '26', '1', ''],
            ['Total Receipts From Persons', '27', '1', ''],
            ['OTHER RECEIPTS', '28', '2', ''],
            ['TOTAL RECEIPTS', '29', '3', ''],
            ['Voter Registration DISBURSEMENTS', '30', '4', 'a'],
            ['Voter ID DISBURSEMENTS', '31', '4', 'b'],
            ['GOTV DISBURSEMENTS', '32', '4', 'c'],
            ['Generic Campaign DISBURSEMENTS', '33', '4', 'd'],
            ['Line 4 Total', '34', '4', 'e'],
            ['OTHER DISBURSEMENTS', '35', '5', ''],
            ['TOTAL DISBURSEMENTS', '36', '6', ''],
            ['CASH ON HAND as of Jan 1', '37', '7', ''],
            ['RECEIPTS', '38', '8', ''],
            ['SUBTOTAL', '39', '9', ''],
            ['DISBURSEMENTS', '40', '10', ''],
            ['ENDING CASH ON HAND', '41', '11', ''],
    ]
