import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER COMMITTEE ID NUMBER', 'number': '2'},
            {'name': 'COMMITTEE NAME', 'number': '3'},
            {'name': 'STREET 1', 'number': '4'},
            {'name': 'STREET 2', 'number': '5'},
            {'name': 'CITY', 'number': '6'},
            {'name': 'STATE', 'number': '7'},
            {'name': 'ZIP', 'number': '8'},
            {'name': 'COMMITTEE TYPE', 'number': '9'},
            {'name': 'AFFILIATED - DATE FORM F1 FILED', 'number': '10'},
            {'name': 'AFFILIATED COMMITTEE FEC ID', 'number': '11'},
            {'name': 'AFFILIATED COMMITTEE NAME', 'number': '12'},
            {'name': 'CANDIDATE ID NUMBER', 'number': '13-I'},
            {'name': 'CANDIDATE LAST NAME', 'number': '14-I'},
            {'name': 'CANDIDATE FIRST NAME', 'number': '15-I'},
            {'name': 'CANDIDATE MIDDLE NAME', 'number': '16-I'},
            {'name': 'CANDIDATE PREFIX', 'number': '17-I'},
            {'name': 'CANDIDATE SUFFIX', 'number': '18-I'},
            {'name': 'CANDIDATE OFFICE', 'number': '19-I'},
            {'name': 'CANDIDATE STATE', 'number': '20-I'},
            {'name': 'CANDIDATE DIST', 'number': '21-I'},
            {'name': 'DATE OF CONTRIBUTION', 'number': '22-I'},
            {'name': 'CANDIDATE ID NUMBER', 'number': '23-II'},
            {'name': 'CANDIDATE LAST NAME', 'number': '24-II'},
            {'name': 'CANDIDATE FIRST NAME', 'number': '25-II'},
            {'name': 'CANDIDATE MIDDLE NAME', 'number': '26-II'},
            {'name': 'CANDIDATE PREFIX', 'number': '27-II'},
            {'name': 'CANDIDATE SUFFIX', 'number': '28-II'},
            {'name': 'CANDIDATE OFFICE', 'number': '29-II'},
            {'name': 'CANDIDATE STATE', 'number': '30-II'},
            {'name': 'CANDIDATE DIST', 'number': '31-II'},
            {'name': 'DATE OF CONTRIBUTION', 'number': '32-II'},
            {'name': 'CANDIDATE ID NUMBER', 'number': '33-III'},
            {'name': 'CANDIDATE LAST NAME', 'number': '34-III'},
            {'name': 'CANDIDATE FIRST NAME', 'number': '35-III'},
            {'name': 'CANDIDATE MIDDLE NAME', 'number': '36-III'},
            {'name': 'CANDIDATE PREFIX', 'number': '37-III'},
            {'name': 'CANDIDATE SUFFIX', 'number': '38-III'},
            {'name': 'CANDIDATE OFFICE', 'number': '39-III'},
            {'name': 'CANDIDATE STATE', 'number': '40-III'},
            {'name': 'CANDIDATE DIST', 'number': '41-III'},
            {'name': 'DATE OF CONTRIBUTION', 'number': '42-III'},
            {'name': 'CANDIDATE ID NUMBER', 'number': '43-IV'},
            {'name': 'CANDIDATE LAST NAME', 'number': '44-IV'},
            {'name': 'CANDIDATE FIRST NAME', 'number': '45-IV'},
            {'name': 'CANDIDATE MIDDLE NAME', 'number': '46-IV'},
            {'name': 'CANDIDATE PREFIX', 'number': '47-IV'},
            {'name': 'CANDIDATE SUFFIX', 'number': '48-IV'},
            {'name': 'CANDIDATE OFFICE', 'number': '49-IV'},
            {'name': 'CANDIDATE STATE', 'number': '50-IV'},
            {'name': 'CANDIDATE DIST', 'number': '51-IV'},
            {'name': 'DATE OF CONTRIBUTION', 'number': '52-IV'},
            {'name': 'CANDIDATE ID NUMBER', 'number': '53-V'},
            {'name': 'CANDIDATE LAST NAME', 'number': '54-V'},
            {'name': 'CANDIDATE FIRST NAME', 'number': '55-V'},
            {'name': 'CANDIDATE MIDDLE NAME', 'number': '56-V'},
            {'name': 'CANDIDATE PREFIX', 'number': '57-V'},
            {'name': 'CANDIDATE SUFFIX', 'number': '58-V'},
            {'name': 'CANDIDATE OFFICE', 'number': '59-V'},
            {'name': 'CANDIDATE STATE', 'number': '60-V'},
            {'name': 'CANDIDATE DIST', 'number': '61-V'},
            {'name': 'DATE OF CONTRIBUTION', 'number': '62-V'},
            {'name': 'Of 51st Contributor', 'number': '63-'},
            {'name': 'Of Orig Registration', 'number': '64-'},
            {'name': 'Cmte Met Requirements', 'number': '65-'},
            {'name': 'TREASURER LAST NAME', 'number': '66'},
            {'name': 'TREASURER FIRST NAME', 'number': '67'},
            {'name': 'TREASURER MIDDLE NAME', 'number': '68'},
            {'name': 'TREASURER PREFIX', 'number': '69'},
            {'name': 'TREASURER SUFFIX', 'number': '70'},
            {'name': 'DATE SIGNED', 'number': '71'},
    ]
        self.fields_names = self.hash_names(self.fields)
