class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['CHANGE OF ADDRESS', '4', '', ''],
            ['STREET 1', '5', '', ''],
            ['STREET 2', '6', '', ''],
            ['CITY', '7', '', ''],
            ['STATE', '8', '', ''],
            ['ZIP', '9', '', ''],
            ['ELECTION STATE', '10', '', ''],
            ['ELECTION DISTRICT', '11', '', ''],
            ['REPORT CODE', '12', '', ''],
            ['ELECTION CODE', '13', '', ''],
            ['DATE OF ELECTION', '14', '', ''],
            ['STATE OF ELECTION', '15', '', ''],
            ['COVERAGE FROM DATE', '16', '', ''],
            ['COVERAGE THROUGH DATE', '17', '', ''],
            ['TREASURER LAST NAME', '18', '', ''],
            ['TREASURER FIRST NAME', '19', '', ''],
            ['TREASURER MIDDLE NAME', '20', '', ''],
            ['TREASURER PREFIX', '21', '', ''],
            ['TREASURER SUFFIX', '22', '', ''],
            ['DATE SIGNED', '23', '', ''],
            ['CANDIDATE ID NUMBER', '24', '', ''],
            ['CANDIDATE LAST NAME', '25', '', ''],
            ['CANDIDATE FIRST NAME', '26', '', ''],
            ['CANDIDATE MIDDLE NAME', '27', '', ''],
            ['CANDIDATE PREFIX', '28', '', ''],
            ['CANDIDATE SUFFIX', '29', '', ''],
            ['F3Z-1 REPORT TYPE', '30', '', ''],
            ['Total Contributions (NO Loans)', '31', '6a', ''],
            ['Total Contribution Refunds', '32', '6b', ''],
            ['Net Contributions', '33', '6c', ''],
            ['Total Operating Expenditures', '34', '7a', ''],
            ['Total Offset to Operating Expenditures', '35', '7b', ''],
            ['NET Operating Expenditures.', '36', '7c', ''],
            ['CASH ON HAND AT CLOSE ...', '37', '8', ''],
            ['DEBTS TO ( Totals from SCH C and/or D)', '38', '9', ''],
            ['DEBTS BY (Totals from SCH C and/or D)', '39', '10', ''],
            ['Individuals Itemized', '40', '11', 'a i.'],
            ['Individuals Unitemized', '41', '11', 'a.ii'],
            ['Individual Contribution Total', '42', '11', 'a.iii'],
            ['Political Party Committees', '43', '11', 'b'],
            ['Other Political Committees', '44', '11', 'c'],
            ['The Candidate', '45', '11', 'd'],
            ['Total Contributions', '46', '11', 'e'],
            ['Transfers From Other Authorized Committees', '47', '12', ''],
            ['Loans made or guarn. by the Candidate', '48', '13', 'a'],
            ['All Other Loans', '49', '13', 'b'],
            ['Total Loans', '50', '13', 'c'],
            ['Offsets to Operating Expenditures', '51', '14', ''],
            ['Other Receipts', '52', '15', ''],
            ['Total Receipts', '53', '16', ''],
            ['Operating Expenditures', '54', '17', ''],
            ['Transfers to Other Authorized Committees', '55', '18', ''],
            ['Of Loans made or guar. by the Cand.', '56', '19', 'a'],
            ['Loan Repayments, All Other Loans', '57', '19', 'b'],
            ['Total Loan Repayments', '58', '19', 'c'],
            ['Refund/Individuals Other than Political Committees', '59', '20', 'a'],
            ['Refund/Political Party Committees', '60', '20', 'b'],
            ['Refund/Other Political Committees', '61', '20', 'c'],
            ['Total Contribution Refunds', '62', '20', 'd'],
            ['Other Disbursements', '63', '21', ''],
            ['Total Disbursements', '64', '22', ''],
            ['Cash Beginning Reporting Period', '65', '23', ''],
            ['Total Receipts this Period', '66', '24', ''],
            ['SubTotal', '67', '25', ''],
            ['Total Disbursements this Period', '68', '26', ''],
            ['Cash on hand at Close Period', '69', '27', ''],
            ['Total Contributions (No Loans)', '70', '6a', ''],
            ['Total Contribution Refunds', '71', '6b', ''],
            ['Net Contributions', '72', '6c', ''],
            ['Total Operating Expenditures', '73', '7a', ''],
            ['Total Offsets to Operating Expenditures', '74', '7b', ''],
            ['NET Operating Expenditures.', '75', '7c', ''],
            ['Individuals Itemized', '76', '11', 'a i.'],
            ['Individuals Unitemized', '77', '11', 'a.ii'],
            ['Individuals Total', '78', '11', 'a.iii'],
            ['Political Party Committees', '79', '11', 'b'],
            ['All Other Political Committees (PACS)', '80', '11', 'c'],
            ['The Candidate', '81', '11', 'd'],
            ['Total Contributions', '82', '11', 'e'],
            ['Transfers From Other AUTH Committees', '83', '12', ''],
            ['Loans made or guarn. by the Candidate', '84', '13', 'a'],
            ['All Other Loans', '85', '13', 'b'],
            ['Total Loans', '86', '13', 'c'],
            ['Offsets to Operating Expenditures', '87', '14', ''],
            ['Other Receipts', '88', '15', ''],
            ['Total Receipts', '89', '16', ''],
            ['Operating Expenditures', '90', '17', ''],
            ['Transfers To Other AUTH Committees', '91', '18', ''],
            ['Loan Repayment By Candidate', '92', '19', 'a'],
            ['Loan Repayments, ALL Other Loans', '93', '19', 'b'],
            ['Total Loan Repayments', '94', '19', 'c'],
            ['Refund/Individuals Other than Political Committees', '95', '20', 'a'],
            ['Refund, Political Party Committees', '96', '20', 'b'],
            ['Refund, Other Political Committees', '97', '20', 'c'],
            ['Total Contributions Refunds', '98', '20', 'd'],
            ['Other Disbursements', '99', '21', ''],
            ['Total Disbursements', '100', '22', ''],
            ['Gross Receipts of Authorized Committees (primary)', '101', '', ''],
            ['Aggregate Amount from Personal Funds (primary)', '102', '', ''],
            ['Gross Receipts Minus Personal from Candidate (primary)', '103', '', ''],
            ['Gross Receipts of Authorized Committees (general)', '104', '', ''],
            ['Aggregate Amount from Personal Funds (general)', '105', '', ''],
            ['Gross Receipts Minus Personal from Candidate (general)', '106', '', ''],
    ]
