class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['Date - General Election', '3', '', ''],
            ['Date - Day after General Election', '4', '', ''],
            ['Total Contributions (No Loans)', '5', '6a', ''],
            ['Total Contribution Refunds', '6', '6b', ''],
            ['Net Contributions', '7', '6c', ''],
            ['Total Operating Expenditures', '8', '7a', ''],
            ['Total Offsets to Operating Expenditures', '9', '7b', ''],
            ['NET Operating Expenditures.', '10', '7c', ''],
            ['Individuals Itemized', '11', '11', 'a i.'],
            ['Individuals Unitemized', '12', '11', 'a.ii'],
            ['Individuals Total', '13', '11', 'a.iii'],
            ['Political Party Committees', '14', '11', 'b'],
            ['All Other Political Committees (PACS)', '15', '11', 'c'],
            ['The Candidate', '16', '11', 'd'],
            ['Total Contributions', '17', '11', 'e'],
            ['Transfers From Other AUTH Committees', '18', '12', ''],
            ['Loans made or guarn. by the Candidate', '19', '13', 'a'],
            ['All Other Loans', '20', '13', 'b'],
            ['Total Loans', '21', '13', 'c'],
            ['Offsets to Operating Expenditures', '22', '14', ''],
            ['Other Receipts', '23', '15', ''],
            ['Total Receipts', '24', '16', ''],
            ['Operating Expenditures', '25', '17', ''],
            ['Transfers To Other AUTH Committees', '26', '18', ''],
            ['Loan Repayment By Candidate', '27', '19', 'a'],
            ['Loan Repayments, ALL Other Loans', '28', '19', 'b'],
            ['Total Loan Repayments', '29', '19', 'c'],
            ['Refund/Individuals Other than Political Committees', '30', '20', 'a'],
            ['Refund, Political Party Committees', '31', '20', 'b'],
            ['Refund, Other Political Committees', '32', '20', 'c'],
            ['Total Contributions Refunds', '33', '20', 'd'],
            ['Other Disbursements', '34', '21', ''],
            ['Total Disbursements', '35', '22', ''],
    ]
