class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['ENTITY TYPE', '4', '', ''],
            ['PAYEE ORGANIZATION NAME', '5', '', ''],
            ['PAYEE LAST NAME', '6', '', ''],
            ['PAYEE FIRST NAME', '7', '', ''],
            ['PAYEE MIDDLE NAME', '8', '', ''],
            ['PAYEE PREFIX', '9', '', ''],
            ['PAYEE SUFFIX', '10', '', ''],
            ['PAYEE STREET 1', '11', '', ''],
            ['PAYEE STREET 2', '12', '', ''],
            ['PAYEE CITY', '13', '', ''],
            ['PAYEE STATE', '14', '', ''],
            ['PAYEE ZIP', '15', '', ''],
            ['ELECTION CODE', '16', '', ''],
            ['ELECTION OTHER DESCRIPTION', '17', '', ''],
            ['EXPENDITURE DATE', '18', '', ''],
            ['EXPENDITURE AMOUNT', '19', '', ''],
            ['CALENDAR Y-T-D (per election/office)', '20', '', ''],
            ['EXPENDITURE PURPOSE CODE', '21', '', ''],
            ['EXPENDITURE PURPOSE DESCRIP', '22', '', ''],
            ['CATEGORY CODE', '23', '', ''],
            ['PAYEE Committee FEC ID NUMBER', '24', '', ''],
            ['SUPPORT/OPPOSE CODE', '25', '', ''],
            ['S/O CANDIDATE ID NUMBER', '26', '', ''],
            ['S/O CANDIDATE LAST NAME', '27', '', ''],
            ['S/O CANDIDATE FIRST NAME', '28', '', ''],
            ['S/O CANDINATE MIDDLE NAME', '29', '', ''],
            ['S/O CANDIDATE PREFIX', '30', '', ''],
            ['S/O CANDIDATE SUFFIX', '31', '', ''],
            ['S/O CANDIDATE OFFICE', '32', '', ''],
            ['S/O CANDIDATE STATE', '33', '', ''],
            ['S/O CANDIDATE DISTRICT', '34', '', ''],
    ]
