class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['COMMITTEE NAME', '3', '', ''],
            ['STREET 1', '4', '', ''],
            ['STREET 2', '5', '', ''],
            ['CITY', '6', '', ''],
            ['STATE', '7', '', ''],
            ['ZIP', '8', '', ''],
            ['CASH ON HAND', '9', '1', ''],
            ['AS OF', '10', '1', 'a'],
            ['Total assets to be liquidated', '11', '2', ''],
            ['Total (assets)', '12', '3', ''],
            ['Year to date receipts', '13', '4', ''],
            ['Year to date disbursements', '14', '5', ''],
            ['Total amount of debts owed by committee', '15', '6', ''],
            ['Total number of creditors owed', '16', '7', ''],
            ['Number of creditors in part II of this plan', '17', '8', ''],
            ['Total amount of debts owed to creditors in part II of plan', '18', '9', ''],
            ['Total amount to be paid to creditors', '19', '10', ''],
            ['Is the committee terminating activities', '20-11. ', '', ''],
            ['PLANNED FOR TERMINATION REPORT', '21-11. YES ', '', ''],
            ['If this is an AUTH committee are there other AUTH committees', '22-12. ', '', ''],
            ['DESCRIPTION (IF YES list AUTH COMMITTEE ID/NAMES)', '23', '12', ''],
            ['sufficient funds to pay total amount', '24-13. ', '', ''],
            ['DESCRIPTION (IF NO, steps taken to obtain the funds)', '25', '13', ''],
            ['Has the committee filed previous plans', '26-14. ', '', ''],
            ['After disposing, any residual funds?', '27-15. ', '', ''],
            ['DESCRIPTION (IF YES, how will the funds be disbursed)', '28', '15', ''],
            ['Does committee have sufficient funds to pay the remaining', '29-PART III ', '', ''],
            ['PART III DESCRIPTION (IF NO, steps taken to obtain the funds.)', '30', '', ''],
            ['TREASURER LAST NAME', '31', '', ''],
            ['TREASURER FIRST NAME', '32', '', ''],
            ['TREASURER MIDDLE NAME', '33', '', ''],
            ['TREASURER PREFIX', '34', '', ''],
            ['TREASURER SUFFIX', '35', '', ''],
            ['DATE SIGNED', '36', '', ''],
    ]
