class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['ENTITY TYPE', '4', '', ''],
            ['CREDITOR ORGANIZATION NAME', '5', '', ''],
            ['CREDITOR LAST NAME', '6', '', ''],
            ['CREDITOR FIRST NAME', '7', '', ''],
            ['CREDITOR MIDDLE NAME', '8', '', ''],
            ['CREDITOR PREFIX', '9', '', ''],
            ['CREDITOR SUFFIX', '10', '', ''],
            ['CREDITOR STREET 1', '11', '', ''],
            ['CREDITOR STREET 2', '12', '', ''],
            ['CREDITOR CITY', '13', '', ''],
            ['CREDITOR STATE', '14', '', ''],
            ['CREDITOR ZIP', '15', '', ''],
            ['DATE INCURRED', '16', '', ''],
            ['AMOUNT OWED TO', '17', '', ''],
            ['AMOUNT OFFERED IN', '18', '', ''],
            ['CREDITOR CODE', '19', '', ''],
            ['DESCRIPTION (Initial Terms And Nature Of Debt)', '20', 'A', ''],
            ['DESCRIPTION (Efforts Made By Committee To Pay Debt)', '21', 'B', ''],
            ['DESCRIPTION (Steps Taken By Creditor To Collect)', '22-C.', '', ''],
            ['effort made by creditor to collect...', '23-D. ', '', ''],
            ['DESCRIPTION (IF NO, Explain)', '24-D.', '', ''],
            ['terms of debt settlement comparable...', '25-E. ', '', ''],
            ['DESCRIPTION (IF NO, Explain)', '26-E.', '', ''],
            ['CREDITOR COMMITTEE ID NUMBER', '27', '', ''],
            ['CREDITOR CANDIDATE ID NUMBER', '28', '', ''],
            ['CREDITOR CANDIDATE LAST NAME', '29', '', ''],
            ['CREDITOR CANDIDATE FIRST NAME', '30', '', ''],
            ['CREDITOR CANDIDATE MIDDLE NAME', '31', '', ''],
            ['CREDITOR CANDIDATE PREFIX', '32', '', ''],
            ['CREDITOR CANDIDATE SUFFIX', '33', '', ''],
            ['CREDITOR CANDIDATE OFFICE', '34', '', ''],
            ['CREDITOR CANDIDATE STATE', '35', '', ''],
            ['CREDITOR CANDIDATE DISTRICT', '36', '', ''],
            ['SIGNATURE OF REPRESENTATIVE LAST NAME', '37', '', ''],
            ['SIGNATURE OF REPRESENTATIVE FIRST NAME', '38', '', ''],
            ['SIGNATURE OF REPRESENTATIVE MIDDLE NAME', '39', '', ''],
            ['SIGNATURE OF REPRESENTATIVE PREFIX', '40', '', ''],
            ['SIGNATURE OF REPRESENTATIVE SUFFIX', '41', '', ''],
            ['DATE SIGNED', '42', '', ''],
    ]
