import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER COMMITTEE ID NUMBER', 'number': '2'},
            {'name': 'TRANSACTION ID NUMBER', 'number': '3'},
            {'name': 'RECEIPT LINE NUMBER', 'number': '4'},
            {'name': 'ENTITY TYPE', 'number': '5'},
            {'name': 'LENDER ORGANIZATION NAME', 'number': '6'},
            {'name': 'LENDER LAST NAME', 'number': '7'},
            {'name': 'LENDER FIRST NAME', 'number': '8'},
            {'name': 'LENDER MIDDLE NAME', 'number': '9'},
            {'name': 'LENDER PREFIX', 'number': '10'},
            {'name': 'LENDER SUFFIX', 'number': '11'},
            {'name': 'LENDER STREET 1', 'number': '12'},
            {'name': 'LENDER STREET 2', 'number': '13'},
            {'name': 'LENDER CITY', 'number': '14'},
            {'name': 'LENDER STATE', 'number': '15'},
            {'name': 'LENDER ZIP', 'number': '16'},
            {'name': 'ELECTION CODE', 'number': '17'},
            {'name': 'ELECTION OTHER DESCRIPTION', 'number': '18'},
            {'name': 'LOAN AMOUNT (Original)', 'number': '19'},
            {'name': 'LOAN PAYMENT TO DATE', 'number': '20'},
            {'name': 'LOAN BALANCE', 'number': '21'},
            {'name': 'Terms', 'number': '22-LOAN INCURRED '},
            {'name': 'Terms', 'number': '23-LOAN DUE '},
            {'name': 'LOAN INTEREST RATE % (Terms)', 'number': '24'},
            {'name': 'Secured?', 'number': '25-'},
            {'name': 'Personal Funds', 'number': '26-'},
            {'name': 'LENDER COMMITTEE ID NUMBER', 'number': '27'},
            {'name': 'LENDER CANDIDATE ID NUMBER', 'number': '28'},
            {'name': 'LENDER CANDIDATE LAST NAME', 'number': '29'},
            {'name': 'LENDER CANDIDATE FIRST NAME', 'number': '30'},
            {'name': 'LENDER CANDIDATE MIDDLE NM', 'number': '31'},
            {'name': 'LENDER CANDIDATE PREFIX', 'number': '32'},
            {'name': 'LENDER CANDIDATE SUFFIX', 'number': '33'},
            {'name': 'LENDER CANDIDATE OFFICE', 'number': '34'},
            {'name': 'LENDER CANDIDATE STATE', 'number': '35'},
            {'name': 'LENDER CANDIDATE DISTRICT', 'number': '36'},
            {'name': 'MEMO CODE', 'number': '37'},
            {'name': 'MEMO TEXT/DESCRIPTION', 'number': '38'},
    ]
        self.fields_names = self.hash_names(self.fields)
