class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['BACK REFERENCE TRAN ID NUMBER', '4', '', ''],
            ['BACK REFERENCE SCHED NAME', '5', '', ''],
            ['Has filer been designated to make Coodinated Expenditures?', '6-', '', ''],
            ['DESIGNATING COMMITTEE ID NUMBER', '7', '', ''],
            ['DESIGNATING COMMITTEE NAME', '8', '', ''],
            ['SUBORDINATE COMMITTEE ID NUMBER', '9', '', ''],
            ['SUBORDINATE COMMITTEE NAME', '10', '', ''],
            ['SUBORDINATE STREET 1', '11', '', ''],
            ['SUBORDINATE STREET 2', '12', '', ''],
            ['SUBORDINATE CITY', '13', '', ''],
            ['SUBORDINATE STATE', '14', '', ''],
            ['SUBORDINATE ZIP', '15', '', ''],
            ['ENTITY TYPE', '16', '', ''],
            ['PAYEE ORGANIZATION NAME', '17', '', ''],
            ['PAYEE LAST NAME', '18', '', ''],
            ['PAYEE FIRST NAME', '19', '', ''],
            ['PAYEE MIDDLE NAME', '20', '', ''],
            ['PAYEE PREFIX', '21', '', ''],
            ['PAYEE SUFFIX', '22', '', ''],
            ['PAYEE STREET 1', '23', '', ''],
            ['PAYEE STREET 2', '24', '', ''],
            ['PAYEE CITY', '25', '', ''],
            ['PAYEE STATE', '26', '', ''],
            ['PAYEE ZIP', '27', '', ''],
            ['EXPENDITURE DATE', '28', '', ''],
            ['EXPENDITURE AMOUNT', '29', '', ''],
            ['AGGREGATE GENERAL ELEC EXPENDED', '30', '', ''],
            ['EXPENDITURE PURPOSE CODE', '31', '', ''],
            ['EXPENDITURE PURPOSE DESCRIP', '32', '', ''],
            ['CATEGORY CODE', '33', '', ''],
            ['INCREASED LIMIT', '34', '', ''],
            ['PAYEE COMMITTEE ID NUMBER', '35', '', ''],
            ['PAYEE CANDIDATE ID NUMBER', '36', '', ''],
            ['PAYEE CANDIDATE LAST NAME', '37', '', ''],
            ['PAYEE CANDIDATE FIRST NAME', '38', '', ''],
            ['PAYEE CANDIDATE MIDDLE NAME', '39', '', ''],
            ['PAYEE CANDIDATE PREFIX', '40', '', ''],
            ['PAYEE CANDIDATE SUFFIX', '41', '', ''],
            ['PAYEE CANDIDATE OFFICE', '42', '', ''],
            ['PAYEE CANDIDATE STATE', '43', '', ''],
            ['PAYEE CANDIDATE DISTRICT', '44', '', ''],
            ['MEMO CODE', '45', '', ''],
            ['MEMO TEXT/DESCRIPTION', '46', '', ''],
    ]
