class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['CHANGE OF COMMITTEE NAME', '3', '', ''],
            ['COMMITTEE NAME', '4', '', ''],
            ['CHANGE OF ADDRESS', '5', '', ''],
            ['STREET 1', '6', '', ''],
            ['STREET 2', '7', '', ''],
            ['CITY', '8', '', ''],
            ['STATE', '9', '', ''],
            ['ZIP', '10', '', ''],
            ['COMMITTEE EMAIL', '11', '', ''],
            ['COMMITTEE WEB URL', '12', '', ''],
            ['COMMITTEE FAX NUMBER', '13', '', ''],
            ['SUBMISSION DATE', '14', '', ''],
            ['SIGNATURE LAST NAME', '15', '', ''],
            ['SIGNATURE FIRST NAME', '16', '', ''],
            ['SIGNATURE MIDDLE NAME', '17', '', ''],
            ['SIGNATURE PREFIX', '18', '', ''],
            ['SIGNATURE SUFFIX', '19', '', ''],
            ['DATE SIGNED', '20', '', ''],
            ['COMMITTEE TYPE', '21', '5', ''],
            ['CANDIDATE ID NUMBER', '22', '5', ''],
            ['CANDIDATE LAST NAME', '23', '5', ''],
            ['CANDIDATE FIRST NAME', '24', '5', ''],
            ['CANDIDATE MIDDLE NAME', '25', '5', ''],
            ['CANDIDATE PREFIX', '26', '5', ''],
            ['CANDIDATE SUFFIX', '27', '5', ''],
            ['CANDIDATE OFFICE', '28', '5', ''],
            ['CANDIDATE STATE', '29', '5', ''],
            ['CANDIDATE DISTRICT', '30', '5', ''],
            ['PARTY CODE', '31', '5', ''],
            ['PARTY TYPE', '32', '5', ''],
            ['CUSTODIAN LAST NAME', '33', '7', ''],
            ['CUSTODIAN FIRST NAME', '34', '7', ''],
            ['CUSTODIAN MIDDLE NAME', '35', '7', ''],
            ['CUSTODIAN PREFIX', '36', '7', ''],
            ['CUSTODIAN SUFFIX', '37', '7', ''],
            ['CUSTODIAN STREET 1', '38', '7', ''],
            ['CUSTODIAN STREET 2', '39', '7', ''],
            ['CUSTODIAN CITY', '40', '7', ''],
            ['CUSTODIAN STATE', '41', '7', ''],
            ['CUSTODIAN ZIP', '42', '7', ''],
            ['CUSTODIAN TITLE', '43', '7', ''],
            ['CUSTODIAN TELEPHONE', '44', '7', ''],
            ['TREASURER LAST NAME', '45', '8', ''],
            ['TREASURER FIRST NAME', '46', '8', ''],
            ['TREASURER MIDDLE NAME', '47', '8', ''],
            ['TREASURER PREFIX', '48', '8', ''],
            ['TREASURER SUFFIX', '49', '8', ''],
            ['TREASURER STREET 1', '50', '8', ''],
            ['TREASURER STREET 2', '51', '8', ''],
            ['TREASURER CITY', '52', '8', ''],
            ['TREASURER STATE', '53', '8', ''],
            ['TREASURER ZIP', '54', '8', ''],
            ['TREASURER TITLE', '55', '8', ''],
            ['TREASURER TELEPHONE', '56', '8', ''],
            ['AFFILIATED Committee ID NUM', '57', '6', ''],
            ['AFFILIATED Committee NAME', '58', '6', ''],
            ['AFFILIATED STREET 1', '59', '6', ''],
            ['AFFILIATED STREET 2', '60', '6', ''],
            ['AFFILIATED CITY', '61', '6', ''],
            ['AFFILIATED STATE', '62', '6', ''],
            ['AFFILIATED ZIP', '63', '6', ''],
            ['RELATIONSHIP', '64', '6', ''],
            ['ORGANIZATION TYPE', '65', '6', ''],
            ['AGENT LAST NAME', '66', '8', ''],
            ['AGENT FIRST NAME', '67', '8', ''],
            ['AGENT MIDDLE NAME', '68', '8', ''],
            ['AGENT PREFIX', '69', '8', ''],
            ['AGENT SUFFIX', '70', '8', ''],
            ['AGENT STREET 1', '71', '8', ''],
            ['AGENT STREET 2', '72', '8', ''],
            ['AGENT CITY', '73', '8', ''],
            ['AGENT STATE', '74', '8', ''],
            ['AGENT ZIP', '75', '8', ''],
            ['AGENT TITLE', '76', '8', ''],
            ['AGENT TELEPHONE', '77', '8', ''],
            ['BANK NAME', '78', '9. a', ''],
            ['BANK STREET 1', '79', '9. a', ''],
            ['BANK STREET 2', '80', '9. a', ''],
            ['BANK CITY', '81', '9. a', ''],
            ['BANK STATE', '82', '9. a', ''],
            ['BANK ZIP', '83', '9. a', ''],
            ['BANK NAME', '84', '9. b', ''],
            ['BANK STREET 1', '85', '9. b', ''],
            ['BANK STREET 2', '86', '9. b', ''],
            ['BANK CITY', '87', '9. b', ''],
            ['BANK STATE', '88', '9. b', ''],
            ['BANK ZIP', '89', '9. b', ''],
    ]
