class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['FILER (Principal Campaign) COMMITTEE NAME', '3', '', ''],
            ['COMMITTEE STREET 1', '4', '', ''],
            ['COMMITTEE STREET 2', '5', '', ''],
            ['COMMITTEE CITY', '6', '', ''],
            ['COMMITTEE STATE', '7', '', ''],
            ['COMMITTEE ZIP', '8', '', ''],
            ['CANDIDATE ID NUMBER', '9', '', ''],
            ['CANDIDATE LAST NAME', '10', '', ''],
            ['CANDIDATE FIRST NAME', '11', '', ''],
            ['CANDIDATE MIDDLE NAME', '12', '', ''],
            ['CANDIDATE PREFIX', '13', '', ''],
            ['CANDIDATE SUFFIX', '14', '', ''],
            ['CANDIDATE OFFICE', '15', '', ''],
            ['CANDIDATE STATE', '16', '', ''],
            ['CANDIDATE DIST', '17', '', ''],
            ['PREVIOUS EXPENDITURE AGGREGATE', '18', '', ''],
            ['EXPENDITURE TOTAL THIS REPORT', '19', '', ''],
            ['EXPENDITURE TOTAL CYCLE-TO-DATE', '20', '', ''],
            ['MEETS F6 FILING FILING REQUIREMENTS', '21', '', ''],
            ['CANDIDATE EMPLOYER', '22', '', ''],
            ['CANDIDATE OCCUPATION', '23', '', ''],
            ['TREASURER LAST NAME', '24', '', ''],
            ['TREASURER FIRST NAME', '25', '', ''],
            ['TREASURER MIDDLE NAME', '26', '', ''],
            ['TREASURER PREFIX', '27', '', ''],
            ['TREASURER SUFFIX', '28', '', ''],
            ['DATE SIGNED', '29', '', ''],
    ]
