class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['AFFILIATED Committee ID NUM', '3', '6', ''],
            ['AFFILIATED Committee NAME', '4', '6', ''],
            ['AFFILIATED STREET 1', '5', '6', ''],
            ['AFFILIATED STREET 2', '6', '6', ''],
            ['AFFILIATED CITY', '7', '6', ''],
            ['AFFILIATED STATE', '8', '6', ''],
            ['AFFILIATED ZIP', '9', '6', ''],
            ['RELATIONSHIP', '10', '6', ''],
            ['ORGANIZATION TYPE', '11', '6', ''],
            ['AGENT LAST NAME', '12', '8', ''],
            ['AGENT FIRST NAME', '13', '8', ''],
            ['AGENT MIDDLE NAME', '14', '8', ''],
            ['AGENT PREFIX', '15', '8', ''],
            ['AGENT SUFFIX', '16', '8', ''],
            ['AGENT STREET 1', '17', '8', ''],
            ['AGENT STREET 2', '18', '8', ''],
            ['AGENT CITY', '19', '8', ''],
            ['AGENT STATE', '20', '8', ''],
            ['AGENT ZIP', '21', '8', ''],
            ['AGENT TITLE', '22', '8', ''],
            ['AGENT TELEPHONE', '23', '8', ''],
            ['BANK NAME', '24', '9', ''],
            ['BANK STREET 1', '25', '9', ''],
            ['BANK STREET 2', '26', '9', ''],
            ['BANK CITY', '27', '9', ''],
            ['BANK STATE', '28', '9', ''],
            ['BANK ZIP', '29', '9', ''],
    ]
