class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER CANDIDATE ID NUMBER', '2', '', ''],
            ['CANDIDATE LAST NAME', '3', '', ''],
            ['CANDIDATE FIRST NAME', '4', '', ''],
            ['CANDIDATE MIDDLE NAME', '5', '', ''],
            ['CANDIDATE PREFIX', '6', '', ''],
            ['CANDIDATE SUFFIX', '7', '', ''],
            ['CHANGE OF ADDRESS', '8', '', ''],
            ['CANDIDATE STREET 1', '9', '', ''],
            ['CANDIDATE STREET 2', '10', '', ''],
            ['CANDIDATE CITY', '11', '', ''],
            ['CANDIDATE STATE', '12', '', ''],
            ['CANDIDATE ZIP', '13', '', ''],
            ['CANDIDATE PARTY CODE', '14', '', ''],
            ['CANDIDATE OFFICE', '15', '', ''],
            ['CANDIDATE STATE', '16', '', ''],
            ['CANDIDATE DISTRICT', '17', '', ''],
            ['YEAR OF ELECTION 1900-2999', '18', '', ''],
            ['PCC COMMITTEE ID NUMBER', '19', '', ''],
            ['PCC COMMITTEE NAME', '20', '', ''],
            ['PCC STREET 1', '21', '', ''],
            ['PCC STREET 2', '22', '', ''],
            ['PCC CITY', '23', '', ''],
            ['PCC STATE', '24', '', ''],
            ['PCC ZIP', '25', '', ''],
            ['AUTH COMMITTEE ID NUMBER', '26', '', ''],
            ['AUTH COMMITTEE NAME', '27', '', ''],
            ['AUTH STREET 1', '28', '', ''],
            ['AUTH STREET 2', '29', '', ''],
            ['AUTH CITY', '30', '', ''],
            ['AUTH STATE', '31', '', ''],
            ['AUTH ZIP', '32', '', ''],
            ['PRI PERSONAL FUNDS DECLARED', '33', '', ''],
            ['GEN PERSONAL FUNDS DECLARED', '34', '', ''],
            ['CANDIDATE SIGNATURE LAST NAME', '35', '', ''],
            ['CANDIDATE SIGNATURE FIRST NAME', '36', '', ''],
            ['CANDIDATE SIGNATURE MIDDLE NAME', '37', '', ''],
            ['CANDIDATE SIGNATURE PREFIX', '38', '', ''],
            ['CANDIDATE SIGNATURE SUFFIX', '39', '', ''],
            ['DATE SIGNED', '40', '', ''],
    ]
