import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER COMMITTEE ID NUMBER', 'number': '2'},
            {'name': 'Date - General Election', 'number': '3'},
            {'name': 'Date - Day after General Election', 'number': '4'},
            {'name': 'Net Contributions', 'number': '5-14.'},
            {'name': 'Net Expenditures', 'number': '6-15.'},
            {'name': 'Federal Funds', 'number': '7-16.'},
            {'name': 'Individuals', 'number': '8-17(a)'},
            {'name': 'Political Party Committees', 'number': '9-17(b)'},
            {'name': 'Other Political Committees (PACs)', 'number': '10-17(c)'},
            {'name': 'The Candidate', 'number': '11-17(d)'},
            {'name': 'Total contributions (Other than Loans)', 'number': '12-17(e)'},
            {'name': 'Transfers From Aff/Other Party Committees', 'number': '13-18.'},
            {'name': 'Received from or Guaranteed by Candidate', 'number': '14-19(a)'},
            {'name': 'Other Loans', 'number': '15-19(b)'},
            {'name': 'Total Loans', 'number': '16-19(c)'},
            {'name': 'Operating', 'number': '17-20(a)'},
            {'name': 'Fundraising', 'number': '18-20(b)'},
            {'name': 'Legal and Accounting', 'number': '19-20(c)'},
            {'name': 'Total Offsets to Operating Expenditures', 'number': '20-20(d)'},
            {'name': 'Other Receipts', 'number': '21-21.'},
            {'name': 'Total Receipts', 'number': '22-22.'},
            {'name': 'Operating Expenditures', 'number': '23-23.'},
            {'name': 'Transfers to Other Authorized Committees', 'number': '24-24.'},
            {'name': 'Fundraising Disbursements', 'number': '25-25.'},
            {'name': 'Exempt Legal and Accounting Disbursements', 'number': '26-26.'},
            {'name': 'Made or Guaranteed by the Candidate', 'number': '27-27(a)'},
            {'name': 'Other Repayments', 'number': '28-27(b)'},
            {'name': 'Total Loan Repayments Made', 'number': '29-27(c)'},
            {'name': 'Individuals', 'number': '30-28(a)'},
            {'name': 'Political Party Committees', 'number': '31-28(b)'},
            {'name': 'Other Political Committees', 'number': '32-28(c)'},
            {'name': 'Total Contributions Refunds', 'number': '33-28(d)'},
            {'name': 'Other Disbursements', 'number': '34-29.'},
            {'name': 'Total Disbursements', 'number': '35-30.'},
            {'name': 'ALABAMA', 'number': '36'},
            {'name': 'ALASKA', 'number': '37'},
            {'name': 'ARIZONA', 'number': '38'},
            {'name': 'ARKANSAS', 'number': '39'},
            {'name': 'CALIFORNIA', 'number': '40'},
            {'name': 'COLORADO', 'number': '41'},
            {'name': 'CONNECTICUT', 'number': '42'},
            {'name': 'DELAWARE', 'number': '43'},
            {'name': 'DIST OF COLUMBIA', 'number': '44'},
            {'name': 'FLORIDA', 'number': '45'},
            {'name': 'GEORGIA', 'number': '46'},
            {'name': 'HAWAII', 'number': '47'},
            {'name': 'IDAHO', 'number': '48'},
            {'name': 'ILLINOIS', 'number': '49'},
            {'name': 'INDIANA', 'number': '50'},
            {'name': 'IOWA', 'number': '51'},
            {'name': 'KANSAS', 'number': '52'},
            {'name': 'KENTUCKY', 'number': '53'},
            {'name': 'LOUISIANA', 'number': '54'},
            {'name': 'MAINE', 'number': '55'},
            {'name': 'MARYLAND', 'number': '56'},
            {'name': 'MASSACHUSETTS', 'number': '57'},
            {'name': 'MICHIGAN', 'number': '58'},
            {'name': 'MINNESOTA', 'number': '59'},
            {'name': 'MISSISSIPPI', 'number': '60'},
            {'name': 'MISSOURI', 'number': '61'},
            {'name': 'MONTANA', 'number': '62'},
            {'name': 'NEBRASKA', 'number': '63'},
            {'name': 'NEVADA', 'number': '64'},
            {'name': 'NEW HAMPSHIRE', 'number': '65'},
            {'name': 'NEW JERSEY', 'number': '66'},
            {'name': 'NEW MEXICO', 'number': '67'},
            {'name': 'NEW YORK', 'number': '68'},
            {'name': 'NORTH CAROLINA', 'number': '69'},
            {'name': 'NORTH DAKOTA', 'number': '70'},
            {'name': 'OHIO', 'number': '71'},
            {'name': 'OKLAHOMA', 'number': '72'},
            {'name': 'OREGON', 'number': '73'},
            {'name': 'PENNSYLVANIA', 'number': '74'},
            {'name': 'RHODE ISLAND', 'number': '75'},
            {'name': 'SOUTH CAROLINA', 'number': '76'},
            {'name': 'SOUTH DAKOTA', 'number': '77'},
            {'name': 'TENNESSEE', 'number': '78'},
            {'name': 'TEXAS', 'number': '79'},
            {'name': 'UTAH', 'number': '80'},
            {'name': 'VERMONT', 'number': '81'},
            {'name': 'VIRGINIA', 'number': '82'},
            {'name': 'WASHINGTON', 'number': '83'},
            {'name': 'WEST VIRGINIA', 'number': '84'},
            {'name': 'WISCONSIN', 'number': '85'},
            {'name': 'WYOMING', 'number': '86'},
            {'name': 'PUERTO RICO', 'number': '87'},
            {'name': 'GUAM', 'number': '88'},
            {'name': 'VIRGIN ISLANDS', 'number': '89'},
            {'name': 'TOTALS', 'number': '90'},
    ]
        self.fields_names = self.hash_names(self.fields)
