class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER (PCC)', '2', '', ''],
            ['COMMITTEE NAME (PCC)', '3', '', ''],
            ['COVERAGE FROM DATE', '4', '', ''],
            ['COVERAGE THROUGH DATE', '5', '', ''],
            ['COMMITTEE ID NUMBER (Auth)', '6', '', ''],
            ['COMMITTEE NAME (Auth)', '7', '', ''],
            ['individuals total', '8-(a)', '11(a)iii', ''],
            ['Political party committees', '9-(b)', '11(b)', ''],
            ['other pol. committees (PACs)', '10-(c)', '11(c)', ''],
            ['the candidate', '11-(d)', '11(d)', ''],
            ['total contributions', '12-(e)', '11(e)', ''],
            ['Transfers from other auth Committees', '13', '(f) 12', ''],
            ['made or guarn. by candidate', '14-(g)', '13(a)', ''],
            ['all other loans', '15-(h)', '13(b)', ''],
            ['total loans', '16-(i)', '13(c)', ''],
            ['offsets to operating expend', '17', '(j) 14', ''],
            ['Other receipts', '18', '(k) 15', ''],
            ['total receipts', '19', '(l) 16', ''],
            ['Operating Expenditures', '20', '(m) 17', ''],
            ['Transfers to other auth Committees', '21', '(n) 18', ''],
            ['made or guaranteed by cand', '22-(o)', '19(a)', ''],
            ['all other loans', '23-(p)', '19(b)', ''],
            ['total loan repayments', '24-(q)', '19(c)', ''],
            ['total refunds individuals', '25-(r)', '20(a)', ''],
            ['Refunds Political Party Committees', '26-(s)', '20(b)', ''],
            ['Refunds other Political Committees', '27-(t)', '20(c)', ''],
            ['total contribution refunds', '28-(u)', '20(d)', ''],
            ['Other disbursements', '29', '(v) 21', ''],
            ['Total disbursements', '30', '(w) 22', ''],
            ['COH beginning reporting period', '31', '(x) 23', ''],
            ['COH at close of period', '32', '(y) 27', ''],
            ['Debts to', '33', '(z) 9', ''],
            ['Debts by', '34', '(aa) 12', ''],
            ['net contributions', '35-(bb)', '6(c)', ''],
            ['net operating expenditures', '36-(cc)', '7(c)', ''],
    ]
