import fechbase
class Records(fechbase.RecordsBase):
    def __init__(self):
        fechbase.RecordsBase.__init__(self)
        self.fields = [
            {'name': 'FORM TYPE', 'number': '1'},
            {'name': 'FILER COMMITTEE ID NUMBER', 'number': '2'},
            {'name': 'TRANSACTION ID NUMBER', 'number': '3'},
            {'name': 'ENTITY TYPE', 'number': '4'},
            {'name': 'CREDITOR ORGANIZATION NAME', 'number': '5'},
            {'name': 'CREDITOR LAST NAME', 'number': '6'},
            {'name': 'CREDITOR FIRST NAME', 'number': '7'},
            {'name': 'CREDITOR MIDDLE NAME', 'number': '8'},
            {'name': 'CREDITOR PREFIX', 'number': '9'},
            {'name': 'CREDITOR SUFFIX', 'number': '10'},
            {'name': 'CREDITOR STREET 1', 'number': '11'},
            {'name': 'CREDITOR STREET 2', 'number': '12'},
            {'name': 'CREDITOR CITY', 'number': '13'},
            {'name': 'CREDITOR STATE', 'number': '14'},
            {'name': 'CREDITOR ZIP', 'number': '15'},
            {'name': 'DATE INCURRED', 'number': '16'},
            {'name': 'AMOUNT OWED TO', 'number': '17'},
            {'name': 'AMOUNT OFFERED IN', 'number': '18'},
            {'name': 'CREDITOR CODE', 'number': '19'},
            {'name': 'DESCRIPTION (Initial Terms And Nature Of Debt)', 'number': '20-A.'},
            {'name': 'DESCRIPTION (Efforts Made By Committee To Pay Debt)', 'number': '21-B.'},
            {'name': 'DESCRIPTION (Steps Taken By Creditor To Collect)', 'number': '22-C.'},
            {'name': 'effort made by creditor to collect...', 'number': '23-D. '},
            {'name': 'DESCRIPTION (IF NO, Explain)', 'number': '24-D.'},
            {'name': 'terms of debt settlement comparable...', 'number': '25-E. '},
            {'name': 'DESCRIPTION (IF NO, Explain)', 'number': '26-E.'},
            {'name': 'CREDITOR COMMITTEE ID NUMBER', 'number': '27'},
            {'name': 'CREDITOR CANDIDATE ID NUMBER', 'number': '28'},
            {'name': 'CREDITOR CANDIDATE LAST NAME', 'number': '29'},
            {'name': 'CREDITOR CANDIDATE FIRST NAME', 'number': '30'},
            {'name': 'CREDITOR CANDIDATE MIDDLE NAME', 'number': '31'},
            {'name': 'CREDITOR CANDIDATE PREFIX', 'number': '32'},
            {'name': 'CREDITOR CANDIDATE SUFFIX', 'number': '33'},
            {'name': 'CREDITOR CANDIDATE OFFICE', 'number': '34'},
            {'name': 'CREDITOR CANDIDATE STATE', 'number': '35'},
            {'name': 'CREDITOR CANDIDATE DISTRICT', 'number': '36'},
            {'name': 'SIGNATURE OF REPRESENTATIVE LAST NAME', 'number': '37'},
            {'name': 'SIGNATURE OF REPRESENTATIVE FIRST NAME', 'number': '38'},
            {'name': 'SIGNATURE OF REPRESENTATIVE MIDDLE NAME', 'number': '39'},
            {'name': 'SIGNATURE OF REPRESENTATIVE PREFIX', 'number': '40'},
            {'name': 'SIGNATURE OF REPRESENTATIVE SUFFIX', 'number': '41'},
            {'name': 'DATE SIGNED', 'number': '42'},
    ]
        self.fields_names = self.hash_names(self.fields)
