class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['ENTITY TYPE', '3', '', ''],
            ['ORGANIZATION NAME', '4', '', ''],
            ['INDIVIDUAL LAST NAME', '5', '', ''],
            ['INDIVIDUAL FIRST NAME', '6', '', ''],
            ['INDIVIDUAL MIDDLE NAME', '7', '', ''],
            ['INDIVIDUAL PREFIX', '8', '', ''],
            ['INDIVIDUAL SUFFIX', '9', '', ''],
            ['CHANGE OF ADDRESS', '10', '', ''],
            ['STREET 1', '11', '', ''],
            ['STREET 2', '12', '', ''],
            ['CITY', '13', '', ''],
            ['STATE', '14', '', ''],
            ['ZIP', '15', '', ''],
            ['INDIVIDUAL EMPLOYER', '16', '', ''],
            ['INDIVIDUAL OCCUPATION', '17', '', ''],
            ['COVERAGE FROM DATE', '18', '', ''],
            ['COVERAGE THROUGH DATE', '19', '', ''],
            ['DATE OF PUBLIC DISTRIBUTION', '20', '', ''],
            ['COMMUNICATION TITLE', '21', '', ''],
            ['QUALIFIED NON-PROFIT', '22', '', ''],
            ['SEGREGATED BANK ACCOUNT', '23', '', ''],
            ['CUSTODIAN LAST NAME', '24', '', ''],
            ['CUSTODIAN FIRST NAME', '25', '', ''],
            ['CUSTODIAN MIDDLE NAME', '26', '', ''],
            ['CUSTODIAN PREFIX', '27', '', ''],
            ['CUSTODIAN SUFFIX', '28', '', ''],
            ['CUSTODIAN STREET 1', '29', '', ''],
            ['CUSTODIAN STREET 2', '30', '', ''],
            ['CUSTODIAN CITY', '31', '', ''],
            ['CUSTODIAN STATE', '32', '', ''],
            ['CUSTODIAN ZIP', '33', '', ''],
            ['CUSTODIAN EMPLOYER', '34', '', ''],
            ['CUSTODIAN OCCUPATION', '35', '', ''],
            ['TOTAL DONATIONS THIS STATEMENT', '36', '9', ''],
            ['TOTAL DISB./OBLIG. THIS STATEMENT', '37', '10', ''],
            ['PERSON COMPLETING LAST NAME', '38', '', ''],
            ['PERSON COMPLETING FIRST NAME', '39', '', ''],
            ['PERSON COMPLETING MIDDLE NAME', '40', '', ''],
            ['PERSON COMPLETING PREFIX', '41', '', ''],
            ['PERSON COMPLETING SUFFIX', '42', '', ''],
            ['DATE SIGNED', '43', '', ''],
    ]
