class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['BACK REFERENCE TRAN ID NUMBER', '4', '', ''],
            ['BACK REFERENCE SCHED NAME', '5', '', ''],
            ['ENTITY TYPE', '6', '', ''],
            ['PAYEE ORGANIZATION NAME', '7', '', ''],
            ['PAYEE LAST NAME', '8', '', ''],
            ['PAYEE FIRST NAME', '9', '', ''],
            ['PAYEE MIDDLE NAME', '10', '', ''],
            ['PAYEE PREFIX', '11', '', ''],
            ['PAYEE SUFFIX', '12', '', ''],
            ['PAYEE STREET 1', '13', '', ''],
            ['PAYEE STREET 2', '14', '', ''],
            ['PAYEE CITY', '15', '', ''],
            ['PAYEE STATE', '16', '', ''],
            ['PAYEE ZIP', '17', '', ''],
            ['ELECTION CODE', '18', '', ''],
            ['ELECTION OTHER DESCRIPTION', '19', '', ''],
            ['EXPENDITURE DATE', '20', '', ''],
            ['EXPENDITURE AMOUNT', '21', '', ''],
            ['EXPENDITURE PURPOSE CODE', '22', '', ''],
            ['EXPENDITURE PURPOSE DESCRIP', '23', '', ''],
            ['CATEGORY CODE', '24', '', ''],
            ['REFUND OR DISPOSAL OF EXCESS', '25', '', ''],
            ['COMMUNICATION DATE', '26', '', ''],
            ['PAYEE COMMITTEE FEC ID', '27', '', ''],
            ['PAYEE CANDIDATE FEC ID', '28', '', ''],
            ['PAYEE CANDIDATE LAST NAME', '29', '', ''],
            ['PAYEE CANDIDATE FIRST NAME', '30', '', ''],
            ['PAYEE CANDIDATE MIDDLE NAME', '31', '', ''],
            ['PAYEE CANDIDATE PREFIX', '32', '', ''],
            ['PAYEE CANDIDATE SUFFIX', '33', '', ''],
            ['PAYEE CANDIDATE OFFICE', '34', '', ''],
            ['PAYEE CANDIDATE STATE', '35', '', ''],
            ['PAYEE CANDIDATE DISTRICT', '36', '', ''],
            ['CONDUIT NAME', '37', '', ''],
            ['CONDUIT STREET 1', '38', '', ''],
            ['CONDUIT STREET 2', '39', '', ''],
            ['CONDUIT CITY', '40', '', ''],
            ['CONDUIT STATE', '41', '', ''],
            ['CONDUIT ZIP', '42', '', ''],
            ['MEMO CODE', '43', '', ''],
            ['MEMO TEXT/DESCRIPTION', '44', '', ''],
            ['Reference to SI or SL system code that identifies the Account', '45', '', ''],
    ]
