class Records:
    def __init__(self):
        self.fields = [
            ['FORM TYPE', '1', '', ''],
            ['FILER COMMITTEE ID NUMBER', '2', '', ''],
            ['TRANSACTION ID NUMBER', '3', '', ''],
            ['RECEIPT LINE NUMBER', '4', '', ''],
            ['ENTITY TYPE', '5', '', ''],
            ['LENDER ORGANIZATION NAME', '6', '', ''],
            ['LENDER LAST NAME', '7', '', ''],
            ['LENDER FIRST NAME', '8', '', ''],
            ['LENDER MIDDLE NAME', '9', '', ''],
            ['LENDER PREFIX', '10', '', ''],
            ['LENDER SUFFIX', '11', '', ''],
            ['LENDER STREET 1', '12', '', ''],
            ['LENDER STREET 2', '13', '', ''],
            ['LENDER CITY', '14', '', ''],
            ['LENDER STATE', '15', '', ''],
            ['LENDER ZIP', '16', '', ''],
            ['ELECTION CODE', '17', '', ''],
            ['ELECTION OTHER DESCRIPTION', '18', '', ''],
            ['LOAN AMOUNT (Original)', '19', '', ''],
            ['LOAN PAYMENT TO DATE', '20', '', ''],
            ['LOAN BALANCE', '21', '', ''],
            ['Terms', '22-LOAN INCURRED ', '', ''],
            ['Terms', '23-LOAN DUE ', '', ''],
            ['LOAN INTEREST RATE % (Terms)', '24', '', ''],
            ['Secured?', '25-', '', ''],
            ['LENDER COMMITTEE ID NUMBER', '26', '', ''],
            ['LENDER CANDIDATE ID NUMBER', '27', '', ''],
            ['LENDER CANDIDATE LAST NAME', '28', '', ''],
            ['LENDER CANDIDATE FIRST NAME', '29', '', ''],
            ['LENDER CANDIDATE MIDDLE NM', '30', '', ''],
            ['LENDER CANDIDATE PREFIX', '31', '', ''],
            ['LENDER CANDIDATE SUFFIX', '32', '', ''],
            ['LENDER CANDIDATE OFFICE', '33', '', ''],
            ['LENDER CANDIDATE STATE', '34', '', ''],
            ['LENDER CANDIDATE DISTRICT', '35', '', ''],
    ]
